Image viewer
rust379/MApp pull request #127
Opened 2021-10-06 18:35 UTC by strizh78

https://user-images.githubusercontent.com/38105548/136262159-406c40c2-3d80-4ba8-949f-298de9cd73f8.mov

такс, это набросок
зум надо ещё доработать (но хочу посмотреть его у тебя на ноуте, может просто мой косячит)
рисовать можно (это всего одна изи функция, так что решила сделать), но я не уверена что это надо сохранять
пока оставила без сохранения
если думаешь что сохранять надо - давай научусь сохранять) [кажется это посложнее будет чутка]

и ещё кажется что сохранять зазумленность точно не надо, ни один известный мне простенький редактор этого не делает

ещё пришлось немного поправить форму файла
там стояли странные политики растяжения в паре мест, из-за этого вьювер странно выглядел

2021-10-06 19:42 UTC, rust379 commented
1 - Сохранять зум не надо
2 - Если есть возможность рисовать, стоит добавить и стиралку
3 - Кажется, пока можно обойтись без сохранения, т.е. использовать карандаш как способ выделить для себя какие-то моменты (например при просмотре рентгена)

2021-10-06 20:12 UTC, strizh78 commented
> 1 - Сохранять зум не надо
> 
> 2 - Если есть возможность рисовать, стоит добавить и стиралку
> 
> 3 - Кажется, пока можно обойтись без сохранения, т.е. использовать карандаш как способ выделить для себя какие-то моменты (например при просмотре рентгена)

1 - ура)
2 - да, посмотрю; думала об этом, но за вечер не успела
3 - хорошо

2021-10-06 20:21 UTC, rust379 requested changes

2021-10-06 20:21 UTC, rust379 commented on interface/appointment/appointmentForm.ui
> +    <height>450</height>
точно необходимые изменения?

2021-10-06 20:21 UTC, rust379 commented on interface/imagePainter/painterView.h
> +
Надо подумать над названием, оказывается этот класс не только рисует, но и отлавливает события мыши, 
может как-то более абстрактно назвать?

2021-10-06 20:59 UTC, strizh78 commented on interface/imagePainter/painterView.cpp
> +        if (drawPoint == QPoint(-1, -1)) {
Ок

2021-10-06 21:00 UTC, strizh78 commented on interface/appointment/appointmentForm.ui
> +    <height>450</height>
Qt не даёт вернуть обратно, я пробовала
Я ничего не меняла в этой форме, просто переоткрыла qt

2021-10-06 21:00 UTC, strizh78 commented on interface/imagePainter/imageEditor.h
> +
Потому что viewer занято в другом месте 
Ок, будет painter

2021-10-06 21:02 UTC, strizh78 commented on interface/imagePainter/painterView.h
> +
Тут 2 объяснения
1. GraphicsView --> PainterView
2. Paint это известное приложение для всего

То что класс для выполнения своих функций отслеживает мышь - точно не должно быть в его названии
Это ж деталь реализации

2021-10-06 21:05 UTC, strizh78 commented on interface/imagePainter/imageEditor.ui
> +   </item>
Ок, думала об этом, а потом забыла)

2021-10-08 10:14 UTC, strizh78 commented
Я бы ешё добавила перемещение изображения с зажатой мышью
сейчас иногда сталкиваюсь что хочется так сделать, а не получается

2021-10-09 08:17 UTC, strizh78 commented
Убрала всё про рисование, как договаривались
Вольём отдельно потом

2021-10-20 06:07 UTC, rust379 approved these changes

2021-10-20 07:09 UTC, merged