prodDB - Add MySQL DB.
rust379/MApp pull request #146
Opened 2022-03-08 02:27 UTC by rust379

- [x] Инициализация БД
- [x] Создание таблиц
- [x] ~~Фильтр при запросе записей~~ - Будет сделано в #153 
- [x] Работа с данными (Добавление / Удаление / Изменение)
- [x] БД интерфейс файлов
- [x] Проверить работу Получения, Добавления, Изменения во всех интерфейсах.
   - [x] Файлы
   - [x] Приемы
   - [x] События
   - [x] Гомеопатия
   - [x] Лекарства  
    - [x] Пациенты
    - [x] Услуги
- [x] Перенести базовые классы в отдельный файл
- [x] Разобраться с коннектом к базе (убрать возможное дублирование)

2022-03-09 15:26 UTC, strizh78 commented on database/prod/databaseProd.cpp
> +const QString ROOT_PASSWORD = "S9kTZm~LG";
в env?

2022-03-09 15:26 UTC, strizh78 commented on database/prod/databaseProd.cpp
> +const QString ROOT_PASSWORD = "S9kTZm~LG";
в env?

2022-03-09 15:28 UTC, rust379 commented on database/prod/databaseProd.cpp
> +#include "databaseProd.h"
databaseSQL

2022-05-04 12:46 UTC, rust379 commented on database/prod/config.h
> +    const QString CONNECTION_NAME = "mapp";
Таб

2022-05-04 12:46 UTC, rust379 commented on database/prod/itemProdInterface.h
> +const QString DEFAULT_LIST_QUERY = "SELECT %1 FROM `%2`";
LIST_QUERY_TEMPLATE

2022-05-04 12:54 UTC, rust379 commented on database/prod/appointmentDB.cpp
> +    columnsShift += homeopathyDb_->columns_.size();
В шаблонную функцию

2022-05-04 12:55 UTC, rust379 commented on database/prod/appointmentDB.cpp
> +        {"isConducted", QString("%1").arg(item.isConducted)},
уже написаны функции

2022-05-04 12:58 UTC, rust379 commented on database/prod/appointmentDB.cpp
> +    qDebug() << res << "\n";
Убрать

2022-05-04 13:16 UTC, rust379 commented on utils/utils.h
> +
Есть готовый в QString

2022-05-13 12:31 UTC, rust379 commented on database/prod/patientDB.cpp
> +    result.nameInfo = Patient::NameInfo(
Добавить поле с инициалами

2022-05-24 16:04 UTC, strizh78 requested changes

2022-05-24 16:04 UTC, strizh78 commented on database/prod/patientDB.cpp
> +    result.nameInfo = Patient::NameInfo(
пинг

2022-05-24 16:04 UTC, strizh78 commented on database/prod/appointmentDB.cpp
> +    result.date = row.value(2 + startPos).toDateTime();
```suggestion
    setDeleted(result, row.value(1 + startPos).toBool());
    
    result.date = row.value(2 + startPos).toDateTime();
```

// в других базах этот отступ есть, добавляю для единообразия

2022-05-24 16:04 UTC, strizh78 commented on database/prod/serviceDB.cpp
> +    setDeleted(result, row.value(1 + startPos).toBool());
```suggestion
    setDeleted(result, row.value(1 + startPos).toBool());
    
```

2022-05-24 16:04 UTC, strizh78 commented on database/test/itemTestInterface.h
> +    }
договаривались что сначала функции, а потом переменные
независимо от приватности

или я не так запомнила?

2022-05-24 16:04 UTC, strizh78 commented on main.cpp
> +//    a.installTranslator(&qtTranslator);
верни перевод кнопочек)

2022-05-24 16:04 UTC, strizh78 commented on main.cpp
> +    DatabasePtr db = std::make_shared<DatabaseProd>();
тут скорее надо просто у database тип поменять

2022-05-24 16:04 UTC, strizh78 commented on utils/utils.h
> +
пинг

2022-05-24 16:05 UTC, strizh78 commented
ещё вот эти файлики в ревью попали, это ожидаемо?
не могу их откомментить
<img width="367" alt="Снимок экрана 2022-05-24 в 18 59 11" src="https://user-images.githubusercontent.com/38105548/170081519-f42b607c-2703-493f-a0a4-ca58ddb04ec2.png">

2022-05-25 20:21 UTC, strizh78 commented
Он пишет про конфликт(в ревью) только с main.cpp, но на самом деле надо проверить бы всё расписание
Когда на маке драйвер sql завёлся, я пробовала смержить базу в бетовую ветку и оно там падало при запуске где-то в коде расписания

2022-06-03 15:54 UTC, strizh78 commented on database/prod/databaseProd.cpp
> +bool DatabaseProd::initConnection() {
если тут устанавливается соединение, то давай в деструкторе его явно закроем?

2022-07-08 17:34 UTC, rust379 commented on database/prod/create_tables_queries.txt
> +CREATE TABLE `files` ( `id` int NOT NULL AUTO_INCREMENT, `name` varchar(45) NOT NULL, `extension` tinytext, `uploadTime` datetime NOT NULL, `lastEditTime` datetime NOT NULL, `isDeleted` tinyint unsig
Добавлено

2022-07-08 17:36 UTC, rust379 commented on database/prod/itemProdInterface.h
> +const QString DEFAULT_LIST_QUERY = "SELECT %1 FROM `%2`";
В реализации базовых классов запросов, запрос разделен на части, переименование не актуально

2022-07-10 03:35 UTC, rust379 commented on database/prod/config.h
> +#if LAUNCH_MODE == PRODUCTION
Как первая версия, если не придумается что-то простое по ходу дела

2022-07-10 03:40 UTC, rust379 commented on database/prod/databaseProd.cpp
> +void createDatabaseIfNotExist() {
Да, такой порядок был бы хорош, но тут функции не описаны в .h и чтоб вызвать - надо описать до
(заголовки не хотел дополнительно наверх добавлять)

2022-07-10 03:42 UTC, rust379 commented on database/prod/dbUtils/dbUtils.h
> +namespace queryFormat {
Почему он не в неймспейсе? все же ок с этим

2022-07-10 03:44 UTC, rust379 commented on database/prod/homeopathyDB.cpp
> +    if (str == "ANIMALS") {
А свичи работают со строками?

2022-07-14 10:32 UTC, rust379 commented
По 
> Разобраться с коннектом к базе (убрать возможное дублирование)
Решил оставить как есть

2022-07-15 15:49 UTC, strizh78 requested changes

2022-07-15 15:49 UTC, strizh78 commented on database/prod/appointmentDB.cpp
> +const QString ID_FIELD = "id";
пинг

2022-07-15 15:49 UTC, strizh78 commented on database/prod/databaseSQL.cpp
> +    auto appointmentProd = new AppointmentDB(homeopathyProd, medicineProd, serviceProd, patientProd);
кастами попробуй?

2022-07-15 15:49 UTC, strizh78 commented on database/prod/dbUtils/dbUtils.h
> +namespace queryFormat {
с большой буковки?

2022-07-15 15:49 UTC, strizh78 commented on database/prod/homeopathyDB.cpp
> +
лишняя пустая строка

2022-07-15 15:49 UTC, strizh78 commented on database/prod/itemProdInterface.h
> +#include "query.h"
инклудик наверх поднять

2022-07-15 15:49 UTC, strizh78 commented on database/prod/query.cpp
> +    return  false;
2 пробела

2022-07-15 15:49 UTC, strizh78 commented on database/prod/query.cpp
> +    auto columnFullName { [&](const std::pair<QString, QString>& item) {
ты нашёл этот момент

2022-07-15 15:49 UTC, strizh78 commented on database/prod/query.h
> +    QString WHERE_PART_TEMPLATE = "\nWHERE\n %1";
константу?

2022-07-15 15:49 UTC, strizh78 commented on database/prod/query.h
> +    const std::string INNER_SEPARATOR = ",\n\t";
QString

2022-07-15 15:49 UTC, strizh78 commented on main.cpp
> +//    a.installTranslator(&qtTranslator);
пинг?

2022-07-15 15:49 UTC, strizh78 commented on utils/utils.cpp
> +std::vector<QString> split(const QString& str, std::string sep) {
const QString&

2022-07-15 15:49 UTC, strizh78 commented on utils/utils.cpp
> +std::vector<QString> split(const QString& str, std::string sep) {
или просто сделай функцию ListToVector или что-то типа того

2022-07-15 15:49 UTC, strizh78 commented on database/prod/dbUtils/dbUtils.cpp
> +        return  "<>";
2 пробела

2022-07-15 15:49 UTC, strizh78 commented on database/prod/fileDB.h
> +    const  QString appoinmentFilesTable_ = "appointment_files";
2 пробела

2022-07-15 15:49 UTC, strizh78 commented on database/prod/patientDB.cpp
> +    result.address =  split(row.value(startPos + 7).toString(), MULTIPLE_VALUE_SEPARATOR);
2 пробела

2022-07-19 05:25 UTC, rust379 commented on database/test/itemTestInterface.h
> +    }
Вроде договаривались, первичный порядок - приватность (public - protected - private), а внутри - сначала методы, потом поля

2022-07-20 07:40 UTC, strizh78 requested changes

2022-07-20 14:15 UTC, rust379 commented on database/prod/appointmentDB.cpp
> +    query.leftJoin(medicineDb_->getTable(), "id", "prescribed medications", "medicine");
Сначала мы коннектим таблицу с этими лекарствами к приему, получаем айдишники лекарств, потом джойним лекарства

2022-07-20 14:19 UTC, rust379 commented on database/prod/fileDB.cpp
> +void FileDB::add(File& file, FileData& data, int parentCode) {
С шаблонами

2022-07-21 05:43 UTC, rust379 commented on database/prod/databaseSQL.cpp
> +    event = new EventDB;
Как именно это тут сдеать?

2022-07-21 05:59 UTC, rust379 commented
> ещё вот эти файлики в ревью попали, это ожидаемо? не могу их откомментить <img alt="Снимок экрана 2022-05-24 в 18 59 11" width="367" src="https://user-images.githubusercontent.com/38105548/170081519-f42b607c-2703-493f-a0a4-ca58ddb04ec2.png">

- [ ] Убрать файлы

2022-07-23 08:24 UTC, strizh78 approved these changes

2022-07-23 13:19 UTC, merged