Timetable
rust379/MApp pull request #151
Opened 2022-04-05 20:44 UTC by strizh78

2022-04-05 20:50 UTC, strizh78 commented on interface/timetable/timetableTop/dailyTimeline/widgets/dailiTimelineForm.cpp
> +#include "dailiTimelineForm.h"
переименовать файлик

2022-04-05 22:08 UTC, strizh78 commented
я ещё по мелочи буду доделывать что-то, но в целом будет круто, если посмотришь
может быстрее найдешь что фиксить)

2022-04-06 08:06 UTC, strizh78 commented
@rust379 
Тут рисуночек связи классов, можно смотреть не скопом все файлики, а по схеме
начиная с какого-то одного поддерева, например
названия файлов/папок в целом согласуются с этой картинкой
<img width="1067" alt="Снимок экрана 2022-04-06 в 10 58 32" src="https://user-images.githubusercontent.com/38105548/161925255-1ca39890-71ae-4959-878e-bb83fdcb77b6.png">
<img width="1210" alt="Снимок экрана 2022-04-06 в 11 05 30" src="https://user-images.githubusercontent.com/38105548/161926494-794c0ca4-9e13-4a1b-9754-b888e55e73c5.png">

**дополнительно:**
пока не делала комбобокс универсальным,
цвета задаются не умно

по этим штукам заведу отдельные тикеты

2022-04-08 18:13 UTC, strizh78 commented
поправила тайтл на винде, чтобы не было месяца с большой буквы
должно стать лучше с попапом у таймлайна (он теперь не должен так часто случайно оставаться, когда мышь уже не там)
теперь в таймлайне максимальный час по дефолту 20, но может стать больше, если есть приёмы на более позднее время

https://user-images.githubusercontent.com/38105548/162497872-68ab5bb1-2c17-4234-a547-f41047f2c2e8.mov

<img width="1696" alt="Снимок экрана 2022-04-08 в 21 12 59" src="https://user-images.githubusercontent.com/38105548/162498394-6d6dabf5-2d70-44e3-a39f-df57f61b10ee.png">

2022-04-09 17:50 UTC, strizh78 commented on interface/timetable/dailyTimetable/dailyTimetable.cpp
> +    lay->setContentsMargins(25, 25 /*тут должно быть -9, если АРХИВ НЕ ПЕРВЫЙ*/, 50, /*не согласовано*/20);
```suggestion
    lay->setContentsMargins(25, 25, 40, /*не согласовано*/20);
```

2022-04-09 17:52 UTC, strizh78 commented on interface/timetable/dailyTimetable/dailyTimetable.cpp
> +            (QDate::currentDate() == date_ && tevents[i].end >= QTime(13, 37)/*QTime::currentTime()*/)) {
```suggestion
            (QDate::currentDate() == date_ && tevents[i].end >= QTime::currentTime())) {
```

2022-04-11 10:45 UTC, strizh78 commented
поправила что в паре мест осталось 13:37 вместо текущего времени
поправила на винде пару шрифтов

2022-04-11 13:44 UTC, strizh78 commented
пока как-то так получается
<img width="1812" alt="Снимок экрана 2022-04-11 в 16 44 29" src="https://user-images.githubusercontent.com/38105548/162752973-800d0001-fe25-4df4-99d8-386208b30466.png">

2022-05-01 23:40 UTC, rust379 requested changes
Комменты в основном по стилю, 
Заметил много достаточно длинных функций (в основном конструкторы), может их как-то раскидать на более атомарные функции?

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/dailyTimetable/events/dailyTimetableEvent.h
> +    DailyTimetableEvent(const TimetableEvent& ev, std::shared_ptr<DatabaseInterface> database, QWidget *parent);
в database/databaseInterface.h
есть же using DatabasePtr = std::shared_ptr<DatabaseInterface>;

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/dailyTimetable/events/dailyTimetableEvent.h
> +#include <database/databaseInterface.h>
Тут разве не "database/databaseInterface.h" должно быть?

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/dailyTimetable/events/dailyTimetableEvent.cpp
> +        event_.begin <= QTime::currentTime() && event_.end >= QTime::currentTime()) {
"{" на следующей строке

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/dailyTimetable/events/dailyTimetableEvent.cpp
> +}
116-117, 121-122 строки дублируются

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/timetableForm.cpp
> +
?

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/timetableForm.cpp
а точно нужно столько пустых строк?

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/timetableTop/dailyTimeline/dailyTimeline.cpp
> +    connect (selectedEventForm_->acceptedButton, &QPushButton::clicked, parentWidget(), [&]() { parentWidget()->setFixedHeight(152); } );
Строки очень похожи, их никак нельзя сделать функцией?
[&]() { parentWidget()->setFixedHeight(236); [&]() { parentWidget()->setFixedHeight(152);
Нельзя ли эту функцию определить выше типа
auto foo = [&](int h) { parentWidget()->setFixedHeight(h); ?

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/timetableTop/dailyTimeline/dailyTimeline.h
> +#include <database/databaseInterface.h>
#include "database/databaseInterface.h"

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/timetableTop/dailyTimeline/dailyTimeline.h
> +    void setDatabase(std::shared_ptr<DatabaseInterface> database);
В инклуде определено using DatabasePtr = std::shared_ptr<DatabaseInterface>;
Нужна ли эта функция, почему бы не в конструктор передать базу, как в других формах?

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/timetableTop/dailyTimeline/widgets/dailyTimelineForm.cpp
> +    QString boxesStyleSheet = "border: none;"
2 пустых строки тоно нужны?

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/timetableTop/dailyTimeline/widgets/dailyTimelineLine.h
> +#include <QObject>
Нужно ли так много пустых строк? 
Кажется, инклуд базы можно к утилсу прилепить, и логика сохранится

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/timetableTop/timetableTop.cpp
> +
Посмотри QString.arg() кажется с ним это запишется в более красивой форме
Что-то вроде
QString("<span style=\"color: %1; font-size:18px;font-weight:400;\">"
        "%2"
        "</span>"
).arg(QColor(128, 130, 135).name()  ,date.toString("dddd"));

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/timetableTop/timetableTop.h
> +    void setDatabase(std::shared_ptr<DatabaseInterface> database);
using DatabasePtr = std::shared_ptr<DatabaseInterface>;

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/timetableTop/dailyTimeline/widgets/dailyTimelineLine.cpp
> +            (QDate::currentDate() == date_ && time >= QTime::currentTime())) {
"{" на новую строчку бы

2022-05-01 23:40 UTC, rust379 commented on interface/timetable/timetableTop/dailyTimeline/widgets/dailyTimelineLine.cpp
> +    painter.drawText(startXCoord + 21 + painter.fontMetrics().horizontalAdvance(time) + 21 + painter.fontMetrics().horizontalAdvance(hovered_->shortName) + 21,
очень длинная строчка

2022-05-24 16:16 UTC, strizh78 commented on MApp.pro
> +    interface/timetable/calendarWidget/calendarWidget.cpp \
он переедет с табиками вместе, следующим ревью

2022-05-24 16:18 UTC, strizh78 commented on interface/timetable/timetableForm.cpp
да, они же из совсем разных уровней/сути/подпапок

2022-05-24 16:20 UTC, strizh78 commented on interface/timetable/calendarWidget/calendarWidget.h
> +    void setSelectedDate(QDate date);
потому что там внутри сложная магия, а не просто изменение значения переменной 
(нам отправить всякие сигналы что дата изменилась и т д)

2022-05-24 16:21 UTC, strizh78 commented on interface/timetable/dailyTimetable/dailyTimetable.cpp
> +    archiveWidget->setObjectName("archiveWidget" + date_.toString("dd.mm"));
да, оно строится на один день,
при изменении дня мы всё равно все удалим и пересчитаем

2022-05-24 16:22 UTC, strizh78 commented on interface/timetable/dailyTimetable/dailyTimetable.cpp
> +            (QDate::currentDate() == date_ && tevents[i].end >= QTime::currentTime())) {
my fail)

2022-05-24 16:27 UTC, strizh78 commented on interface/timetable/dailyTimetable/events/dailyTimetableEvent.h
> +#include <database/databaseInterface.h>
это qt автоматом ставит, поменяла

2022-05-24 16:31 UTC, strizh78 commented on interface/timetable/timetableTop/dailyTimeline/dailyTimeline.cpp
> +    connect (selectedEventForm_->acceptedButton, &QPushButton::clicked, parentWidget(), [&]() { parentWidget()->setFixedHeight(152); } );
кажется, не прокатит(
он будет ожидать что h будет передано в сигнале клика

2022-05-25 19:34 UTC, rust379 approved these changes

2022-05-25 19:34 UTC, rust379 commented on interface/timetable/timetableTop/dailyTimeline/widgets/dailyTimelineLine.cpp
> +                         painter.fontMetrics().horizontalAdvance(hovered_->shortName) + 21,
а painter должен быть с таким отступом, не прямо под startXCoord  ?

2022-05-25 20:11 UTC, strizh78 commented on interface/timetable/timetableTop/dailyTimeline/widgets/dailyTimelineLine.cpp
> +                         painter.fontMetrics().horizontalAdvance(hovered_->shortName) + 21,
да, лучше пусть так будет
это разбиение верхней строчки на кусочки

а если сделаю отступ около startXCoord, то будет как будто это новый аргумент функции

2022-05-25 20:11 UTC, merged

2022-05-25 20:19 UTC, strizh78 commented
замержила,
там есть часть штук которые надо будет поправить, но они в основном ждут Андрея
чуть позже заведу тикет с списочком / на каждый свой тикет