add main.yml config with check build actions; fix errors
rust379/MApp pull request #161
Opened 2022-06-07 10:49 UTC by strizh78

2022-06-17 15:21 UTC, rust379 approved these changes

2022-07-14 10:30 UTC, rust379 commented on interface/appointment/appointmentForm.h
> +#include <optional>
А это для чего?

2022-07-14 10:30 UTC, rust379 commented on .github/workflows/main.yml
> +          nmake
А почему тут в 2 строки?

2022-07-14 10:30 UTC, rust379 commented on .github/workflows/main.yml
> +        uses: jurplel/install-qt-action@v2
Почему разный порядок шагов? (в винде. сначала идет установка, потом чекаут), это на что-то влияет?

2022-07-14 10:30 UTC, rust379 commented on .github/workflows/main.yml
> +        uses: actions/checkout@v2-beta
А в винде actions/checkout@v2 - почему так?
+ в винде указываем v2.9.0 при установке Qt, а в линуксе и. маке нет, может использовать одно и то же, или так нельзя?

2022-07-14 10:30 UTC, rust379 commented on .github/workflows/main.yml
> +          modules: 'qtcharts qtwebengine'
в винде это использовать не нужно?

2022-07-14 10:30 UTC, rust379 commented on .github/workflows/main.yml
> +          version: '5.15.2'
Может версию вынести. наверх? 
```
version: &version 5.12.5

with:
  version: *version
```
или 
```
qt_version: &version
 version: 5.12.5

with:
  *version
```

2022-07-23 16:58 UTC, strizh78 commented on .github/workflows/main.yml
> +          version: '5.15.2'
а где ты такое видел? я не вижу ничего подобного в официальной доке гита по этой штуке

2022-07-27 07:48 UTC, rust379 requested changes

2022-07-27 07:48 UTC, rust379 commented on .github/workflows/main.yml
> +          version: '5.15.2'
а причем тут гит, это же ямл
2-3 [пункты](https://bestprogrammer.ru/bez-rubriki/shpargalka-po-rasshirennomu-sintaksisu-yaml)

2022-07-27 07:48 UTC, rust379 commented on .github/workflows/main.yml
> +      - name: Checkout
тут и в маке имя шага `Checkout `,  а в винде - `Checkout code` - может выберем одно название?

2022-07-27 07:48 UTC, rust379 commented on .github/workflows/main.yml
> +          version: '5.15.2'
+ Тут шаги одинаковы, их тоже можно вынести (каждый шаг в свой псевдоним), и что-то переопределить по необходимости

2022-07-27 07:48 UTC, rust379 commented on interface/service/servicesListForm.ui
> +   <header>interface/basicForms/mappTable.h</header>
А как он раньше такое кушал, ему норм было?

2022-07-29 18:07 UTC, rust379 approved these changes

2022-07-29 18:09 UTC, merged