constructorByPath - File constructor by path.
rust379/MApp pull request #182
Opened 2022-08-02 05:21 UTC by rust379

#171
![2022-08-02 08-12-50 MApp](https://user-images.githubusercontent.com/38105637/182297536-cccc4a5f-9a10-4ba3-a6f0-d44b5cbeceb0.png)

2022-08-02 05:27 UTC, rust379 commented
Добавил [тикет ](https://github.com/rust379/MApp/issues/183)на переделку формы с выводом таких ошибок, эта сюда не очень подходит, но пусть пока будет

2022-08-02 07:45 UTC, strizh78 requested changes

2022-08-02 07:45 UTC, strizh78 commented on file/file.cpp
> +    init();
Может тогда переименовать в initDate() ?

2022-08-02 07:45 UTC, strizh78 commented on file/file.cpp
> +        throw std::ios_base::failure(qFile.errorString().toStdString());
Почему именно такая ошибка? Может свой эксепшен сделать тогда уж?

2022-08-02 07:45 UTC, strizh78 commented on file/file.cpp
>  File::File(const QString& name, const QString& extension)
А если у нас FileData теперь внутри файла, то почему она не передаётся в конструктор? Нам ок?

2022-08-02 07:45 UTC, strizh78 commented on file/file.h
> +private:
Вроде бы договаривались что функции перед всеми переменными, независимо от приватности

Чтобы в больших классах не получалось что у тебя 50+ функций, а между ними прячутся 2 переменных, которые глазами не видно даже

2022-08-02 07:45 UTC, strizh78 commented on interface/file/filesListForm.cpp
> +#include <ios>
А зачем оно тут?

2022-08-02 07:45 UTC, strizh78 commented on interface/file/filesListForm.cpp
> +        QErrorMessage* errorMessage = new QErrorMessage(this);
Я не уверена что нужна такая форма, давай это обсудим сегодня

Мне кажется что она не даёт пользы пользователю, ибо он в жизни не поймёт что за ошибка (особенно "iostream error" если напишет), но заставляет смиренно кликнуть на "закрыть"
Вечером покажу как это сделано у внутренних сервисов, может с них скопипастим?

2022-08-02 08:08 UTC, rust379 commented on file/file.cpp
>  File::File(const QString& name, const QString& extension)
Этот конструктор,  думаю можно выпилить

2022-08-02 08:09 UTC, strizh78 commented on file/file.cpp
>  File::File(const QString& name, const QString& extension)
Выпилишь?)

2022-08-02 08:10 UTC, rust379 commented on file/file.h
> +private:
Но это [не соблюдается ](https://github.com/rust379/MApp/blob/050fe30c9062792230ffe25084293e82f282eef9/drugs/dosage.h#L24)
Давай на встрече это обсудим и зафиксируем

2022-08-02 08:11 UTC, rust379 commented on interface/file/filesListForm.cpp
> +#include <ios>
Для [std::ios_base::failure](https://en.cppreference.com/w/cpp/io/ios_base/failure)

2022-08-02 08:12 UTC, rust379 commented on interface/file/filesListForm.cpp
> +        QErrorMessage* errorMessage = new QErrorMessage(this);
Она показывает и человеческую ошибку, так что пока норм
а другая форма да, нужна, я завел тикет на это https://github.com/rust379/MApp/pull/182#issuecomment-1202033335

2022-08-02 08:14 UTC, rust379 commented on file/file.cpp
> +        throw std::ios_base::failure(qFile.errorString().toStdString());
Что именно ты имеешь в виду?

2022-08-02 08:15 UTC, rust379 commented on file/file.cpp
> +    init();
да, ок,
думал это будет некая общая фукнция, но там только датавремя)

2022-08-02 08:18 UTC, strizh78 commented on file/file.cpp
> +        throw std::ios_base::failure(qFile.errorString().toStdString());
Почему мы кидаем ошибку ios_base::... ? Можно же сделать свой класс (условно, унаследовав его от базового эксепшена) File...Exception и кидать ее

Плюс, думаю можно посмотреть на кутешные эксепшены
Если они чем то лучше встроенных, то наследоваться от них

2022-08-02 08:19 UTC, strizh78 commented on file/file.h
> +private:
То что оно где-то не соблюдается - надо пофиксить)

2022-08-02 08:20 UTC, strizh78 commented on interface/file/filesListForm.cpp
> +        QErrorMessage* errorMessage = new QErrorMessage(this);
А где человеческая ошибка?
Я не увидела, видимо(

2022-08-02 08:24 UTC, rust379 commented on file/file.cpp
> +        throw std::ios_base::failure(qFile.errorString().toStdString());
Да, это хорошая идея и я тоже за то, чтоб сделать свой класс, но не в этой задаче)

2022-08-02 08:25 UTC, strizh78 requested changes

2022-08-02 08:25 UTC, strizh78 commented on interface/file/filesListForm.cpp
> +            QString("Произошла ошибка при добавлении фалйа: %1")
Опечатка в слове "файла"

2022-08-02 08:26 UTC, rust379 commented on interface/file/filesListForm.cpp
> +        QErrorMessage* errorMessage = new QErrorMessage(this);
QString("Произошла ошибка при добавлении фалйа: %1").arg(e.what())
+ Вывод показан на скрине в описании

2022-08-02 08:31 UTC, strizh78 commented on interface/file/filesListForm.cpp
> +        QErrorMessage* errorMessage = new QErrorMessage(this);
давай обсудим на встрече)

2022-08-02 08:32 UTC, strizh78 commented on file/file.cpp
> +        throw std::ios_base::failure(qFile.errorString().toStdString());
там же одна строчка буквально, нет? зачем отдельная задача сейчас?

условно class ClassName : public Exception {
ClassName(Exception у) = default();
};

2022-08-02 08:33 UTC, strizh78 commented on file/file.h
> +private:
* на встрече быстренько обсудим, я записала себе, чтобы не забыть

2022-08-06 20:48 UTC, rust379 commented on file/file.cpp
>  File::File(const QString& name, const QString& extension)
А нет, конструктор используется в тестовой базе, добавлю в него данные

2022-08-06 21:04 UTC, strizh78 approved these changes

2022-08-06 21:04 UTC, strizh78 commented on interface/file/filesListForm.cpp
> +        addFile(file);
На будущее: давай переименуем addFile в условный addFileToTable
мне сейчас пришлось идти в код, чтобы понять что это за добавление и куда)

2022-08-06 21:11 UTC, merged