allFilesAsDefault - Set all files as first point.
rust379/MApp pull request #184
Opened 2022-08-02 05:57 UTC by rust379

2022-08-02 08:05 UTC, strizh78 requested changes

2022-08-02 08:30 UTC, rust379 commented on file/file.cpp
> +        "All files (*.*)",
Файлы без расширения?

2022-08-02 08:41 UTC, strizh78 commented on file/file.cpp
> +        "All files (*.*)",
> Файлы без расширения?  

у меня половина txt файлов без расширения валяется)
особенно если я их через консоль завожу

> Тут еще возникает момент, а как обрабатывать файлы, которые мы не умеем отображать,
Если раньше, позволяли выбрать только "хорошие" файлы, то сейчас - свобода выбора  

а как тебе такая идея:
1. автоматом предлагаем выбрать только из всех "хороших файлов" (т е не *.*, а перечисление подходящих расширений)
действительно, предлагать абсолютно все файлы, а потом выдавать на них ошибки - странно
2. позволить переключить на выбор всех файлов, если пользователь того хочет (на свой страх и риск, так сказать) [см сноску *]

[сноска * ] тут надо сначала подготовить приложение под это, мне кажется сейчас с неправильным расширением/без него оно рухнет просто
например, говорить(формочкой) что мы не можем определить тип файла и предлагать пользователю самому выбрать картинка/текст/etc

2022-08-02 08:44 UTC, rust379 commented on file/file.cpp
> +        "All files (*.*)",
Да, ок, давай так сделаем,
1-2 сейчас, сноску потом

2022-08-02 08:49 UTC, strizh78 commented on file/file.cpp
> +        "All files (*.*)",
может тогда 2 пока не включать вообще? или оно будет работать?

ты проверял что будет, если добавить файл с неподдерживаемым расширением? он отобразится? оно не рухнет?
например вордовский или ico/другой тип картинки
tsc/csv?

2022-08-02 08:53 UTC, rust379 commented on file/file.cpp
> +        "All files (*.*)",
А, неправильно прочитал) думал во 2 - просто переключить на конкретный тип файлов, тогда 2 не надо делать, совсем
Пусть все файлы == все "хорошие"
Но нет, с другими форматами он не рухнет, все нормально запишет в базу (файлу же не важно расширение), но отображаться он не будет

2022-08-02 08:57 UTC, strizh78 commented on file/file.cpp
> +        "All files (*.*)",
> но отображаться он не будет
ну значит нам такого точно не надо
"записать в базу без возможности использования" равноценно "не записать в базу" с точки зрения пользователя)

// а разве не рухнет при попытке отобразить?

2022-08-02 09:43 UTC, rust379 commented on file/file.cpp
> +        "All files (*.*)",
Я случайно ткнул на питоновский файл, он скушал норм

2022-08-06 19:10 UTC, strizh78 reviewed
Было бы круто в будущем как-то автоматом конкатенацию делать

2022-08-06 19:10 UTC, strizh78 approved these changes

2022-08-06 21:34 UTC, merged