Logger - Logger class.
rust379/MApp pull request #188
Opened 2022-08-18 05:44 UTC by rust379

Close #68

2022-08-18 05:46 UTC, rust379 commented on database/prod/databaseSQL.cpp
> -            qCritical() << query.lastError();
Qt не нравится взаимодействие QTextStream и QSqlError, в некоторых местах разделил на 2 ошибки, где-то оставил только текст ошибки от  БД

2022-08-18 05:47 UTC, rust379 commented on utils/logger/logger.cpp
> +    }
Вот если выскочило это исключение, непонятно, куда писать об этом (файл лога может быть переполнен),

2022-08-18 05:55 UTC, rust379 commented on database/prod/itemProdInterface.h
>  #include <QDebug>
Убрать

2022-08-18 05:57 UTC, rust379 commented on utils/logger/logger.h
> +    const int LOG_FILES = 5; // Number of files existing at the same time
Поставил бОльшие ограничения, 100кб очень быстро заполняются, даже на тестовых выводах

2022-08-18 07:12 UTC, rust379 commented on database/prod/databaseSQL.cpp
>  #include <QDebug>
убрать

2022-08-18 07:21 UTC, rust379 commented on utils/logger/logger.h
> +
лишняя пустая строка

2022-08-24 16:33 UTC, strizh78 requested changes

2022-08-25 05:46 UTC, strizh78 requested changes

2022-08-25 05:46 UTC, strizh78 commented on logger/logger.cpp
> +Logger::Logger() {
Конструктор ниже, чем функции?

2022-08-25 05:46 UTC, strizh78 commented on logger/logger.cpp
> +    out_.setFieldWidth(12);
а почему 12?

2022-08-25 05:46 UTC, strizh78 commented on logger/logger.h
> +    };
я вижу что ты тут поменял уровни логгирования, но в дефайнах LOG_XXX и вызовах в базе всё ещё LOG_CRITICAL

так задумано?

2022-08-27 18:02 UTC, rust379 commented on logger/logger.cpp
> +Logger::Logger() {
https://github.com/rust379/MApp/issues/190

2022-08-27 18:08 UTC, strizh78 approved these changes

2022-08-27 18:08 UTC, strizh78 commented on logger/logger.cpp
> +    //check file size and if needed create new log!
А нужен ли этот комментарий?

2022-08-27 18:13 UTC, rust379 commented on logger/logger.cpp
> +    //check file size and if needed create new log!
Да, давай удал., и так понятно, что там происходит

2022-08-27 20:13 UTC, merged