Tabs [пока можно не смотреть, проверяю сборку]
rust379/MApp pull request #194
Opened 2022-08-31 13:48 UTC by strizh78

2022-08-31 19:53 UTC, strizh78 commented on interface/timetable/timetableTop/dailyTimeline/widgets/dailyTimelineForm.cpp
> -    name_->SetAlignment(Qt::AlignCenter);
добавить styleSheet

2022-08-31 19:54 UTC, strizh78 commented on interface/timetable/timetableTop/dailyTimeline/widgets/dailyTimelineForm.cpp
> -#include "appointment/appointment.h"
вернуть и удалить отдельно

2022-09-09 18:59 UTC, strizh78 commented on interface/timetable/timetableForm.cpp
> -    ui->monthComboBox->SetAlignment(Qt::AlignRight | Qt::AlignVCenter);
календарь уехал из расписания в табик + кнопочки сегодня/завтра/вчера/выбор месяцев переехали в сам календарь

2022-09-09 20:48 UTC, strizh78 commented
- [ ] Пофиксить календарь (растяжение месяца и года)
- [ ] Добавить в календарь адекватную логику для будущих лет
- [ ] 
- [ ] Пофиксить дублирование в креэйторе
- [ ] Пофиксить дублирование в мейн виндоу?
- [ ] 
- [ ] Проверить итогово

2022-09-10 13:29 UTC, strizh78 commented on database/prod/config.h
> +    const QString DATABASE_NAME = "mapp-test-template-files-v1.0";
исправлю перед мержем

2022-09-10 13:29 UTC, strizh78 commented on interface/basicForms/basicForms.pri
> +include(calendarWidget/calendarWidget.pri)
календарь переехал в basicForms

labeledComponents - компонентики с припиской(лейблом) сверху - у нас это табики/список приёмов в расписании/потом ещё в самой форме приёма будут
сейчас добавила их для табиков, но уже существующие штуки не заменяла (будет отдельным ревью)

2022-09-10 13:29 UTC, strizh78 commented on interface/basicForms/basicForms.pri
> -$$PWD/comboBox.h \
он пока не нужен, смогла 90% сделать через QComboBox

2022-09-10 13:29 UTC, strizh78 commented on interface/basicForms/calendarWidget/calendarBodyWidget.cpp
> -#include "calendarWidget.h"
был calendarWidget, сейчас он разделился на

class calendarWidget {
calendarBodyWidget;
CalendarHeaderWidget;
}

2022-09-10 13:29 UTC, strizh78 commented on interface/basicForms/calendarWidget/calendarHeaderWidget.h
> +    int minYear_ = 2020;
если понадобится, то сделаем их Q_PROPERTY и сможем задавать через qss

2022-09-10 13:29 UTC, strizh78 commented on interface/basicForms/labeledComponents/labeledButton/labeledButton.h
> +class PushButtonWithDoubleClick : public QPushButton {
по дефолту дабл клика у кнопки неть, пришлось добавить)

2022-09-10 13:29 UTC, strizh78 commented on interface/service/serviceForm.cpp
> -        setWindowTitle("Услуга " + service_.name);
мы (временно) для объектов, у которых ещё нет дизайна для табов, берем в качестве текста таба их windowTitle
Со словом услуга они получались слишком длинными и мешали

2022-09-10 13:29 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
> +QWidget* createDefaultSmallForm(const QString& buttonText, TabButton* tab) {
это временная дефолтная штука, ибо для многих табов нет дизайна
можешь особо не вчитываться, потом все равно уйдет

2022-09-10 13:29 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
> +        tab->connect(pinBtn, &QPushButton::clicked, tab, &TabButton::pinClicked);
суть: каждый объект в креэйторе сможет сам решать надо ли ему уметь в пины/закрытие/ещё что-то
(например, календарь не хочет уметь закрываться)

кажется, что так намного проще, чем передавать миллион параметров покажи кнопку/не показывай кнопку плюс у нас у разных штук может быть разное поведение
например, календарь показывает иконки всегда, а остальные табы нет
плюс разный порядок иконок у них

2022-09-10 13:29 UTC, strizh78 commented on database/prod/config.h
> +    const QString DATABASE_NAME = "mapp-test-template-files-v1.0";
можно прямо тут предложить исправление, я его после апрува/перед окну

2022-10-03 14:10 UTC, strizh78 commented
![IMAGE 2022-10-03 17:10:34](https://user-images.githubusercontent.com/38105548/193598753-25d8465f-7626-4b03-805a-369207d26f67.jpg)

2022-10-28 15:39 UTC, strizh78 commented on interface/tabs/tabsWidget/tabButton.cpp
> +    if (currentForm_ ==smallForm_) {
```suggestion
    if (currentForm_ == smallForm_) {
```

2022-10-28 15:41 UTC, strizh78 commented on interface/tabs/tabsWidget/tabsListWidget.cpp
> +    if (!name2Button_.contains(tabName)) {
тут можно заюзать контейнс, который ниже?

2022-10-28 15:43 UTC, strizh78 commented on interface/tabs/tabsWidget/tabsListWidget.cpp
> +    delete button;
[вопрос к Свете]

а этот делит нужен?
наверное да?

2022-10-28 15:52 UTC, strizh78 commented on interface/tabs/tabsManager/tabsManager.pri
> +$$PWD/tabsManager.h
табуляции перед файлами в pri файликах

2022-10-28 16:16 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
> +
разделить по cpp

2022-10-28 16:17 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
> +        layTexts->insertLayout(layTexts->count(), layDate);
разбить по функциям

2022-10-28 16:27 UTC, strizh78 commented on interface/mainwindow.h
> +    TimetableForm* timetable = nullptr;
убрать тут nullptr

2022-10-28 16:29 UTC, strizh78 commented on interface/mainwindow.cpp
> +#include <interface/basicForms/calendarWidget/calendarWidget.h>
кавычечки

2022-10-28 16:51 UTC, strizh78 commented on interface/mainwindow.cpp
> +        auto* currentWidget = ui->formLayout->itemAt(1)->widget();
убер звездочки, Свет

2022-10-28 17:10 UTC, strizh78 commented on interface/basicForms/calendarWidget/calendarhHeaderWidget.cpp
> +#include "calendarHeaderWidget.h"
h лишняя

2022-10-28 17:13 UTC, strizh78 commented on interface/basicForms/calendarWidget/calendarWidget.h
> +    void setSelectedDate(QDate date) {
вынести

2022-10-28 17:22 UTC, rust379 requested changes

2022-10-28 17:22 UTC, rust379 commented on interface/basicForms/labeledComponents/labeledFrame.cpp
> +void LabeledFrame::setWidget(QWidget *son) {
```suggestion
void LabeledFrame::setWidget(QWidget* son) {
```

2022-10-28 17:22 UTC, rust379 commented on interface/basicForms/labeledComponents/labeledButton/labeledButton.cpp
> +    button_->setStyleSheet(" QPushButton#LabeledButtonButton { background: none; border: none; border-radius: 20px; }");
Давай каждый атрибут на своей строке?)

2022-10-28 17:22 UTC, rust379 commented on interface/basicForms/calendarWidget/calendarhHeaderWidget.cpp
> +void CalendarHeaderWidget::setSelectedDate(QDate date) {
константная ссылка?

2022-10-28 17:22 UTC, rust379 commented on interface/basicForms/calendarWidget/calendarBodyWidget.cpp
> +    CalendarDayButton(QString s, QWidget* parent);
```suggestion
    CalendarDayButton(const QString& s, QWidget* parent);
```

2022-10-28 17:22 UTC, rust379 commented on interface/basicForms/calendarWidget/calendarBodyWidget.cpp
> +void CalendarDayButton::paintEvent(QPaintEvent *e) {
```suggestion
void CalendarDayButton::paintEvent(QPaintEvent* e) {
```

2022-10-28 17:29 UTC, strizh78 commented on interface/tabs/tabsWidget/tabsWidget.cpp
> +    return nullptr;
сделать else

2022-10-29 09:26 UTC, strizh78 commented on interface/mainwindow.cpp
> +        ui->widget->triggerSelectedAction();
leftMenu, надо переименовать, но не тут, думаю

2022-10-29 09:28 UTC, strizh78 commented on interface/mainwindow.h
>      template <class F>
ответила вчера

2022-10-29 09:33 UTC, strizh78 commented on interface/tabs/tabsWidget/tabsListWidget.cpp
> +    return name2Button_[tabName];
вроде уже обсуждали
сейчас не может

если кто-то захочет ее впихнуть - его проблемы, отлаживается это не сложно
а постоянные проверки такое себе

2022-10-29 09:38 UTC, strizh78 commented on interface/tabs/tabsWidget/tabsWidget.cpp
> +    return nullptr;
тут можно сделать вместо двух ифов else if

но делать

if (basic->contains) return basic->get;
return pinned->get 

не хочется
это во первых менее очевидно, как будто у нас пины это какой-то дефолт, где всё есть (тут хотя бы явный nullptr), и второе - если мы изменим реализацию внутри basic и pinned и они станут с массивами, то тут UB
в текущей реализации мы не зависим от того как внутри устроены basic и pin

2022-11-06 13:47 UTC, rust379 commented on interface/tabs/tabsWidget/tabsWidget.cpp
> +                                  "border-bottom-left-radius: 20px; }"
```suggestion
                                  "border-bottom-left-radius: 20px; 
                                  }"
```

2022-11-06 14:36 UTC, rust379 requested changes

2022-11-06 14:36 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.h
> +template<class TabBase, class TabFullForm>
`TabBase` - Это тип объекта, который передаем? 
из названия непонятно, пришлось искать использование, может более очевидное название подберем, `TabItemType` (не настаиваю на таком)
Ну и аналогично с `TabFullForm` - тут понятно в целом, что это такое, но может аналогично `ItemFullForm` или не `Item`, а `Object`

2022-11-06 14:36 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
> +                               "padding: 20px 0px 20px 30px;");
2 раза `padding`

2022-11-06 14:36 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
>      delB->setIcon(QIcon(":/icons/burgerMenu/close.png"));
delB == delete button?
а почему `delete`, а иконка `close` может это `closeButton`?

2022-11-06 14:36 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
>      auto pinBtn = new QPushButton();
Наверху просто `B`, тут `Btn` может что-то одно?) для полного `Button`  места тоже хватает)

2022-11-06 14:36 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/calendarTab.cpp
> +                             "}");
А вот ниже и в остальных местах, насколько помню - не было `+=` а все одной строкой, может и тут так же?

2022-11-06 14:36 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/calendarTab.cpp
> +                             "}");
Может тут придерживаться такого же стиля, как в `.css` с пустыми строками?
Ниже в файлах это еще встречается, вроде

2022-11-06 14:36 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/appointmentTab.cpp
> +    changeFont(patientLabel, 16, QFont::Medium);
16 - как шрифт часто тут упоминается, давай его вынесем в константу

2022-11-06 14:36 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/appointmentTab.cpp
> +    delBtn->setStyleSheet(styleSheet);
Или `closeBtn`?

2022-11-06 14:36 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/appointmentTab.cpp
> +    lay->addLayout(buttonsLay);
`infoLay` и `buttonsLay` может их сразу в `addLayout` инициализировать?

2022-11-06 14:36 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/appointmentTab.cpp
> +QLayout* setupDateTimeLay(const QDateTime& date, const QTime& duration) {
setup - установка, а мы в рамках этой функции, не устанавливаем его, а просто создаем, 
давай тут либо `create` либо вообще без глагола `dateTimeLay`

2022-11-06 14:36 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/appointmentTab.cpp
> +QWidget* setupPatientWidget(const Patient& patient) {
аналогично выше про `setup`

2022-11-06 14:36 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/appointmentTab.cpp
> +QLayout* setupTextInfo(const Appointment& appointment) {
аналогично выше про `setup`

2022-11-06 14:36 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/appointmentTab.cpp
> +QLayout* setupButtons(TabButton* tab) {
аналогично выше про `setup`

2022-11-06 14:36 UTC, rust379 commented on interface/basicForms/calendarWidget/calendarHeaderWidget.h
> +    int maxYear_;
А они вообще зачем?

2022-11-06 14:36 UTC, rust379 commented on interface/basicForms/calendarWidget/calendarBodyWidget.cpp
> +                              "color: " + color.name());
Повторяет строчки 91-93, эти стили и должны быть одинаковы или "Так получилось" и они не связаны?
Просто если есть связь, то может в функцию вынести, зависящей от цвета?

2022-11-07 10:24 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.h
> +template<class TabBase, class TabFullForm>
Не хочу уходить к итемам/объектам
Мало ли для чего мы захотим табы делать (календарь вот не особо объект)
Можем сделать TabBase->TabBaseClass, но фиг знает

2022-11-07 10:25 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
>      delB->setIcon(QIcon(":/icons/burgerMenu/close.png"));
close потому что я пока не заменяла иконки андрея
и крестик из-за этого называется close
кнопка при этом больше про delete.

2022-11-07 10:25 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
>      auto pinBtn = new QPushButton();
будет Btn

2022-11-07 10:26 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/calendarTab.cpp
> +                             "}");
а не смешается слишком много всего?

2022-11-07 10:26 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/calendarTab.cpp
> +                             "}");
если где-то встречается - надо убрать
когда переедем в .qss, то там сделаем пустые строки между разными элементами)

2022-11-07 10:29 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/appointmentTab.cpp
> +    changeFont(patientLabel, 16, QFont::Medium);
я не выносила, потому что шрифт разных элементов вроде как
т е мы вполне можем когда-то захотеть изменить один шрифт, но не изменять другой
мы хотим такое объединять?

при этом суть константы не очень понятна тут (мне)
тип по длине мы только символов добавим, а по сути понятнее не станет (и так ясно что за цифра)

2022-11-07 10:32 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/appointmentTab.cpp
> +QLayout* setupDateTimeLay(const QDateTime& date, const QTime& duration) {
set - установка
setup - больше про настройку всё же, имхо (например настраивающие экзешники называют setup.exe), у qt если класс с ui формой, то создание+настройка_стиля называется setupUi(), поэтому мне кажется что сетап тут консистентнее с остальным
create всё же чисто про создание, в нем меньше ожидаешь настройки всякие


// без глагола мне совсем не нравится, выглядит как геттер внешний

2022-11-07 10:34 UTC, strizh78 commented on interface/basicForms/calendarWidget/calendarBodyWidget.cpp
> +                              "color: " + color.name());
связи не особо есть
они вполне могут меняться независимо в будущем

2022-11-07 10:35 UTC, strizh78 commented on interface/basicForms/calendarWidget/calendarHeaderWidget.h
> +    int maxYear_;
ась?
мы же их в конструкторе инициализируем, на их основе заполняем выбор года и проверяем какой год пользователь выбрал, вроде

2022-11-07 14:24 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.h
> +template<class TabBase, class TabFullForm>
`Item` - довольно нейтральное слово, да и календарь вполне себе объект
Можно и `class`

2022-11-07 14:27 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
>      delB->setIcon(QIcon(":/icons/burgerMenu/close.png"));
Но потом и коннект идет к `close`
`tab->connect(delB, &QPushButton::clicked, tab, &TabButton::closeClicked);`
А почему кнопка больше про удаление, если табик мы закрываем, а не удаляем?

2022-11-07 14:28 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/calendarTab.cpp
> +                             "}");
Нигде не смешивалось (особенно с пустыми строками), да и `+=` не добавляет читаемости

2022-11-07 14:34 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/appointmentTab.cpp
> +QLayout* setupDateTimeLay(const QDateTime& date, const QTime& duration) {
Именно, 

> setup - больше про настройку всё же

QT штука setupUi() - она внутри что-то устанавливает, но ничего не возвращает, а в этих функциях происходит не установка, а создание какого-то. элемента, который будет установлен позже

2022-11-07 14:43 UTC, strizh78 commented on interface/basicForms/calendarWidget/calendarHeaderWidget.h
> +    int maxYear_;
зачем?
чтобы был огромный список? какая цель у него, кроме лишней прокрутки? 
мы прием можем назначить только на +4, поэтому задала так

можно minYear зафиксировать, но это надо отдельно обсудить и отдельным тикетом тогда

2022-11-07 14:47 UTC, strizh78 commented on interface/basicForms/calendarWidget/calendarHeaderWidget.h
> +    int maxYear_;
давай завтра быстренько обсудим вопросики все, ок?

2022-11-08 17:19 UTC, strizh78 commented on interface/basicForms/calendarWidget/calendarHeaderWidget.h
> +    int maxYear_;
обсудить с андреем отдельно

2022-11-10 17:53 UTC, strizh78 commented on interface/tabs/tabsWidget/tabsWidget.h
> +    void changeBasicAreaWidgetsVisibility();
заменила, но мне всё ещё не очень нравится set тут)

2022-11-10 17:59 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/appointmentTab.cpp
> +    lay->addLayout(buttonsLay);
всё же мне не очень хочется смешивать создание и добавление
оставлю на свой вкус

2022-11-10 18:07 UTC, strizh78 commented
поправила

2022-11-18 17:46 UTC, rust379 approved these changes

2022-11-18 18:00 UTC, merged