remove friends
rust379/MApp pull request #219
Opened 2022-10-29 12:42 UTC by strizh78

2022-10-29 12:43 UTC, strizh78 commented on database/prod/serviceDB.h
>      friend class FileDB;
файлы убрать не получается

<img width="1125" alt="Снимок экрана 2022-10-29 в 15 39 05" src="https://user-images.githubusercontent.com/38105548/198832018-43e639d8-7aef-467e-b1b6-a05fc806901b.png">

2022-11-06 14:40 UTC, rust379 requested changes

2022-11-06 14:40 UTC, rust379 commented on database/prod/serviceDB.h
>      friend class FileDB;
использование tableName_ стоит заменить на корректный метод, `getTableName`, но второй handle... придется так и оставить, переносить в паблик некорректно

2022-11-06 14:42 UTC, strizh78 commented on database/prod/serviceDB.h
>      friend class FileDB;
На это вроде тикет завели?
Если нет, то надо завести, это не очень связано с убиранием друзей, учитывая что хендл остаётся

2022-11-06 14:52 UTC, rust379 commented on database/prod/serviceDB.h
>      friend class FileDB;
Это просто место рядом, раз наткнулась)

2022-11-10 18:11 UTC, strizh78 commented
поправила

2022-11-18 17:36 UTC, rust379 approved these changes

2022-11-18 17:39 UTC, merged