union homeopathy and medicine classes
rust379/MApp pull request #224
Opened 2022-10-30 12:29 UTC by strizh78

Посмотри, там мы хотим или как-то иначе?

2022-11-08 10:56 UTC, rust379 requested changes

2022-11-08 10:56 UTC, rust379 commented on drugs/drug.h
> +    QString getActiveSubstance() const;
давай тут покажем, что это full active substance, иначе может быть недопонимание, чем это отличается от просто взятия значения из `activeSubstance`

2022-11-08 10:56 UTC, rust379 commented on drugs/drugs.pri
>  $$PWD/medicines.h \
их не стоит в подпапки закинуть?

2022-11-08 10:56 UTC, rust379 commented on drugs/homeopathy.cpp
> -QString Drug::getFullName() const {
а почему убрано, договорились же оставить? 

> Можно сделать метод гетАктВещ(), который будет строить строку (которая с обоими языками и скобками)
И разрешить им переопределять гетНейм, там гомеопатия будет вызывать гетАктВещ(), а лекарство еще будет уточнять наличие наименований торговых

2022-11-08 10:56 UTC, rust379 commented on drugs/homeopathy.cpp
> -QString Drug::getFullName() const {
getFullName тогда можно как виртуальную в `drug.h`

2022-11-08 11:45 UTC, strizh78 commented on drugs/homeopathy.cpp
> -QString Drug::getFullName() const {
потому что ревью 9 дней, а договорились позавчера)

2022-11-10 18:20 UTC, strizh78 commented on drugs/drugs.pri
>  $$PWD/medicines.h \
мне кажется нет, они родные друг другу и их не так уж много
можно будет подумать об этом в рамках переезда всех объектов в общую папку, но конкретно у лекарств мне не кажется это нужным сейчас

2022-11-10 18:21 UTC, strizh78 commented
поправила

2022-11-18 17:37 UTC, rust379 approved these changes

2022-11-18 17:38 UTC, closed without merging