saveDrugs - Fix medicines saving.
rust379/MApp pull request #230
Opened 2022-11-19 20:29 UTC by rust379

#191

2022-11-19 20:32 UTC, strizh78 requested changes

2022-11-19 20:32 UTC, strizh78 commented on database/prod/appointmentDB.cpp
> +    for (const auto& medicine : item.medicines) {
а если мы сначала выписали лекарство, а потом передумали и удалили, то тут оно не удалится же?
[и можем ли мы "передумать" или откладываем это до реализации удаления]

2022-11-19 20:32 UTC, strizh78 commented on database/prod/appointmentDB.cpp
> +    query.leftJoin(PRESCRIBED_MEDICATIONS_TABLE, "appointment", "id");
необязательно:
а не лучше как в файлах, что такие таблицы это не глобальная штука, а переменная класса?

2022-11-19 20:36 UTC, rust379 commented on database/prod/appointmentDB.cpp
> +    for (const auto& medicine : item.medicines) {
Добавление лекарства происходит только в момент сохранения приема после проведения, а это происходит только 1 раз. 
Удалять назначенные лекарства, насколько я понимаю, мы не даем (после проведения)

2022-11-19 20:37 UTC, strizh78 commented on database/prod/appointmentDB.cpp
> +    for (const auto& medicine : item.medicines) {
логично, окей
не подумала)

2022-11-19 20:38 UTC, rust379 commented on database/prod/appointmentDB.cpp
> +    query.leftJoin(PRESCRIBED_MEDICATIONS_TABLE, "appointment", "id");
Чтоб оно наружу не торчало?

2022-11-19 20:40 UTC, strizh78 commented on database/prod/appointmentDB.cpp
> +    query.leftJoin(PRESCRIBED_MEDICATIONS_TABLE, "appointment", "id");
скорее для консистентности с файловой бд, раз там уже начали связанные таблицы в классе хранить

наружу оно торчать не будет вроде бы, но будет отжирать чуточку места для хранения глобальной переменной

2022-11-19 20:41 UTC, rust379 commented on database/prod/appointmentDB.cpp
> +    query.leftJoin(PRESCRIBED_MEDICATIONS_TABLE, "appointment", "id");
Ок

2022-11-20 14:21 UTC, strizh78 requested changes

2022-11-20 14:21 UTC, strizh78 commented on database/prod/appointmentDB.h
> +    const QString prescribedMedicationsTable = "prescribed_medications";
Тут как будто нижнее подчеркивание последнее пропало?
В использовании переменной оно вроде есть

Или путаю что-то?

2022-11-20 14:25 UTC, rust379 commented on database/prod/appointmentDB.h
> +    const QString prescribedMedicationsTable = "prescribed_medications";
Почему-то не захватилось это изменение

2022-11-20 14:26 UTC, strizh78 commented on database/prod/appointmentDB.h
> +    const QString prescribedMedicationsTable = "prescribed_medications";
Поправишь?
Я с телефона не могу изменение предложить(

2022-11-20 14:26 UTC, rust379 commented on database/prod/appointmentDB.h
> +    const QString prescribedMedicationsTable = "prescribed_medications";
Да, уже

2022-11-20 14:31 UTC, strizh78 approved these changes

2022-11-20 15:14 UTC, merged