v0 of dateTimePicker popup
rust379/MApp pull request #240
Opened 2022-11-23 11:12 UTC by strizh78

опять же, примерно 0 дизайна (только некоторые фиксы шрифта/размеров, просто чтобы оно не разлеталось)
и сделано было давно, я просто в отдельное ревью вынесла

не уверена ок ли мне так
посмотри, тебе норм? или может стоит как-то по другому классам ответственность пораздавать?

2022-12-06 14:55 UTC, rust379 requested changes

2022-12-06 14:55 UTC, rust379 commented on interface/basicForms/dateTimeSelector/dateTimeSelector.cpp
> +std::vector<TimetableEvent> getEventsForDate(DatabasePtr database, QDateTime date) {
тут `const` не нужен?

2022-12-06 14:55 UTC, rust379 commented on interface/basicForms/dateTimeSelector/dateTimeSelector.cpp
> +    for (auto& v : events) {
аналогично вопрос про нейминг) давай `e`?

2022-12-06 14:55 UTC, rust379 commented on interface/basicForms/dateTimeSelector/dateTimeSelector.cpp
> +    };
а для чего тут перенос строк? вроде и в 1 читаемо

2022-12-06 14:55 UTC, rust379 commented on interface/basicForms/dateTimeSelector/dateTimeSelector.cpp
> +    selectorLay->addLayout(createTimeLayout());
Может тут разбить на блоки по 2 строки, сливаются строки?

2022-12-06 14:55 UTC, rust379 commented on interface/appointment/appointmentForm.h
> +    DateTimeSelector* dateTimeSelector;
`_`в постфиксе

2022-12-06 14:55 UTC, rust379 commented on interface/appointment/appointmentForm.cpp
> +    ui->dateTime->setTopLeftXShift(-750);
неожиданное значение)

2022-12-07 15:09 UTC, strizh78 commented on interface/basicForms/dateTimeSelector/dateTimeSelector.cpp
> +        tevents[i].color = colors[i % colors.size()];
предполагалось что возможно они будут таки своих обычных цветов, а не одного, так что было с заделом
но пока уберу

2022-12-07 15:09 UTC, strizh78 commented on interface/appointment/appointmentForm.cpp
> +    ui->dateTime->setTopLeftXShift(-750);
вопросы к магии и Андрею)
потом попробую сделать формулкой с выводом, но пока не прокатило

2022-12-12 21:37 UTC, rust379 approved these changes

2022-12-13 09:09 UTC, strizh78 commented on interface/basicForms/dateTimeSelector/dateTimeSelector.cpp
> +    sort (tevents.begin(), tevents.end(), [](const TimetableEvent& a, const TimetableEvent& b) { return a.begin < b.begin; });
```suggestion
    sort (tevents.begin(), tevents.end(), [] (const TimetableEvent& a, const TimetableEvent& b) { return a.begin < b.begin; });
```

2022-12-13 09:09 UTC, strizh78 commented on interface/basicForms/dateTimeSelector/dateTimeSelector.cpp
> +    sort (tevents.begin(), tevents.end(), [](const TimetableEvent& a, const TimetableEvent& b) { return a.begin < b.begin; });
потому что исправляла.
видимо не подтянулось

2022-12-13 09:10 UTC, merged