New object tabs design
rust379/MApp pull request #241
Opened 2022-11-23 17:28 UTC by strizh78

чутка переделала разные табики

там будет ещё одно ревью
оно сделает ховер-кнопочки вместо текущих и уберет кусочки дублирования ещё
просто объединять не хотелось, чтобы разные штуки не намешивать

2022-11-23 17:31 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/eventTab.cpp
> +QLayout* createTextInfo(const Event& event) {
вот эти 2 функции очень похожи у эвента и приёма
пока забить на это, ибо одна из них почти самоудалится, когда сделаем ховерные иконки (их не так надо будет в лейаут вставлять),
а вторая объединится, когда приём и эвент станут родственными

2022-11-23 17:32 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
> +                            "border: none;"
все вот эти мелкие styleSheet и changeFont надеюсь скоро нас тут покинут и уедут в qss

2022-11-23 17:33 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
> +QLayout *createDateTimeLay(const QDateTime &date, const QTime &duration) {
оно просто переехало их приёма, ибо нужно ещё и эвенту
обединим их - можно будет тут тоже как-то по-другому переделать, но отдельно уже

2022-12-06 14:34 UTC, rust379 requested changes

2022-12-06 14:34 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/calendarTab.cpp
> +    todayButton->connect(todayButton, &QPushButton::clicked, calendar, [calendar] () { calendar->setSelectedDate(QDate::currentDate()); });
Немного непривычно видеть пробелы `[calendar] () {`, ощущение, что это несвязные между собой штуки, но ок

2022-12-06 17:04 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/serviceTab.cpp
> +    QString tabType = "услуга";
тексты теперь с маленькой буквы
в фигме оно тоже поменялось, вроде
с Андреем согласовывала

2022-12-07 15:23 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
> +QLayout *createDateTimeLay(const QDateTime &date, const QTime &duration) {
частично объединила

там можно ещё объединить, но давай немного подождем и отдельно сделаем
там просто кнопки изменят часть и общая форма приёма/события не знаю как повлияет
и ещё обновление данных не знаю как учтётся
не хочется сейчас объединить так, что потом придется откатывать

2022-12-12 21:43 UTC, rust379 approved these changes

2022-12-12 21:43 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
> +QWidget* createDefaultSmallForm(QWidget* tabDataWidget, TabButton* tab) {
тут const не нужен?

2022-12-13 09:11 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
> +QWidget* createDefaultSmallForm(QWidget* tabDataWidget, TabButton* tab) {
вроде нет, у него при добавлении в лейаут перезаписываются внутренние значения parent/размеров

2022-12-13 09:26 UTC, merged