Observer - Second helpful manager.
rust379/MApp pull request #252
Opened 2023-01-07 20:40 UTC by rust379

#200

2023-01-07 20:43 UTC, rust379 commented on observer/observer.cpp
> +}
Принимаются предложения как можно без такого обойтись)

2023-01-07 20:44 UTC, rust379 commented on observer/observer.cpp
> +void dynamicConnect(const QObject* sender, const QObject* receiver, const QByteArray& methodName) {
Штука выглядит полезной, может когда-нибудь в `utils` переедет

2023-01-07 20:47 UTC, rust379 commented on observer/subscriptions.h
> +#pragma once
Это файлик с частями подписок (объекты и действия), возможно стоит назвать по другому
Вынес эти штуки отдельно, чтоб основной файл не засорять

2023-01-10 15:20 UTC, strizh78 commented on observer/observer.cpp
> +    dynamicConnect(&database->appointment->actionSender, this, QString("databaseMagic(DB_ACTIONS, Appointment)").toLatin1());
toLatin1 в dynamicConnect

2023-01-10 15:20 UTC, strizh78 commented on observer/observer.h
> +
```suggestion
```

2023-01-10 15:23 UTC, strizh78 commented on database/itemDatabaseInterface.h
> +Q_OBJECT
```suggestion
    Q_OBJECT
```

2023-01-10 15:23 UTC, strizh78 commented on database/prod/appointmentDB.cpp
> -
верни строчку)

2023-01-10 15:24 UTC, strizh78 commented on database/prod/appointmentDB.cpp
> +    emit this->actionSender.databaseMagic(DB_ACTIONS::UPDATE, item);
```suggestion
    emit actionSender.databaseMagic(DB_ACTIONS::UPDATE, item);
```

2023-01-10 15:24 UTC, strizh78 commented on database/prod/itemProdInterface.h
> +#include "observer/observer.h"
порядок инклудов

2023-01-10 15:24 UTC, strizh78 commented on database/prod/itemProdInterface.h
> +        emit this->actionSender.databaseMagic(DB_ACTIONS::ADD, item);
```suggestion
        emit actionSender.databaseMagic(DB_ACTIONS::ADD, item);
```

2023-01-10 15:24 UTC, strizh78 commented on database/prod/itemProdInterface.h
> +        emit this->actionSender.databaseMagic(DB_ACTIONS::UPDATE, editedItem);
```suggestion
        emit actionSender.databaseMagic(DB_ACTIONS::UPDATE, editedItem);
```

2023-01-10 15:29 UTC, strizh78 commented on database/test/fileTestDB.cpp
> +    emit this->actionSender.databaseMagic(DB_ACTIONS::ADD, file);
```suggestion
    emit actionSender.databaseMagic(DB_ACTIONS::ADD, file);
```

2023-01-10 15:29 UTC, strizh78 commented on database/test/fileTestDB.cpp
> +    emit this->actionSender.databaseMagic(DB_ACTIONS::UPDATE, editedFile);
```suggestion
    emit actionSender.databaseMagic(DB_ACTIONS::UPDATE, editedFile);
```

2023-01-10 15:31 UTC, strizh78 commented on database/test/itemTestInterface.h
> +        emit this->actionSender.databaseMagic(DB_ACTIONS::ADD, item);
```suggestion
        emit actionSender.databaseMagic(DB_ACTIONS::ADD, item);
```

2023-01-10 15:31 UTC, strizh78 commented on database/test/itemTestInterface.h
> +        emit this->actionSender.databaseMagic(DB_ACTIONS::UPDATE, editedItem);
```suggestion
        emit actionSender.databaseMagic(DB_ACTIONS::UPDATE, editedItem);
```

2023-01-10 15:33 UTC, strizh78 commented on observer/observer.cpp
> +    return toString(parts).toLatin1();
toLatin1?
если оно и надо (не факт), то давай это вызывающая сторона будет делать?
тогда если функцию уедет в утилс, ее будет легче использовать остальным

2023-01-10 15:49 UTC, strizh78 commented on observer/observer.h
> +#include "events/appointment.h"
в декларацию

2023-01-10 15:51 UTC, strizh78 commented on observer/observer.h
> +            LOG_ERROR_WITH_CAT("OBSERVER") << "Failed to invoke method " + signalName;
```suggestion
            LOG_ERROR_WITH_CAT("OBSERVER") << "Failed to invoke signal " + signalName;
```

2023-01-10 15:58 UTC, strizh78 commented on observer/observer.cpp
> +void dynamicConnect(const QObject* sender, const QObject* receiver, const QByteArray& methodName) {
название)

2023-01-17 20:28 UTC, rust379 commented on observer/observer.cpp
> +void dynamicConnect(const QObject* sender, const QObject* receiver, const QByteArray& methodName) {
Не нашел ничего лучше, оставил как есть

2023-01-17 20:38 UTC, rust379 commented on database/prod/itemProdInterface.h
> +        emit this->actionSender.databaseMagic(DB_ACTIONS::ADD, item);
Тут оставлено как есть, падают мак и линукс билды

2023-01-17 20:38 UTC, rust379 commented on database/prod/itemProdInterface.h
> +        emit this->actionSender.databaseMagic(DB_ACTIONS::UPDATE, editedItem);
Тут оставлено как есть, падают мак и линукс билды

2023-01-17 20:38 UTC, rust379 commented on database/test/itemTestInterface.h
> +        emit this->actionSender.databaseMagic(DB_ACTIONS::ADD, item);
Тут оставлено как есть, падают мак и линукс билды

2023-01-19 13:08 UTC, strizh78 commented on database/prod/itemProdInterface.h
> +        emit this->actionSender.databaseQueryExecuted(DB_ACTIONS::ADD, item);
а мы так и не поняли почему тут не прокатывает без this?
// я помню что там ошибка компиляции, просто интересно почему так

2023-01-19 13:09 UTC, strizh78 commented on main.cpp
> +#include "observer/observer.h"
```suggestion
#include "observer/observer.h"

#include "utils/utils.h"
```

2023-01-19 13:10 UTC, strizh78 commented on observer/observer.h
> +class Observer: public QObject {
а может переименовать в условный ObjectsObserver или DatabaseActionsObserver?
(не настаиваю)

2023-01-19 13:15 UTC, strizh78 requested changes

2023-01-19 13:15 UTC, strizh78 commented on utils/utils.h
> +    static const QString message;
а зачем ей быть статиком? почему она не может быть просто константой класса?

2023-01-19 13:15 UTC, strizh78 commented on MApp.pro
>  include(events/events.pri)
в целом вопрос: а можешь тут кратко сказать что нужно сейчас сделать, чтобы оно заработало

например, у меня есть форма приёма и я хочу знать когда изменится пациент или добавится новый
какие методы(слоты?) появятся в форме приёма? у них есть требования к неймингу?
нужно будет в условном конструкторе подписаться на это изменение?

2023-01-20 13:47 UTC, rust379 commented on database/prod/itemProdInterface.h
> +        emit this->actionSender.databaseQueryExecuted(DB_ACTIONS::ADD, item);
Давай заведем на это задачу, как-нибудь потом разберемся

2023-01-20 13:53 UTC, rust379 commented on observer/observer.h
> +class Observer: public QObject {
Думаю не надо, это класс который может в будущем следить не только за базой и объектами, но и действиями и чем-то еще, достаточно только в `subscriptions.h` дописать вещи, за которыми будем следить (например открытие форм, клик по кнопкам)

2023-01-20 13:54 UTC, rust379 commented on utils/utils.h
> +    static const QString message;
Используется в статик методах

2023-01-20 14:05 UTC, rust379 commented on MApp.pro
>  include(events/events.pri)
https://github.com/rust379/MApp/issues/200#issuecomment-1398441281

2023-01-21 08:24 UTC, strizh78 approved these changes

2023-01-21 10:43 UTC, merged