Titles
rust379/MApp pull request #255
Opened 2023-01-12 19:50 UTC by strizh78

2023-01-20 22:33 UTC, strizh78 commented on interface/basicForms/basicForms.pri
> +    $$PWD/basicObjectForm/basicObjectForm.pri
```suggestion
```

2023-01-20 22:36 UTC, strizh78 commented on interface/events/appointment/appointmentForm.ui
> +    <width>465</width>
это оно само, я эту часть не трогала

2023-01-20 22:37 UTC, strizh78 commented on interface/homeopathy/homeopathyDrugForm.cpp
> +        ui->title->addButton(createButton("Сохранить",
* тут будет ещё добавление в архив для существующего лекарства (и у остальных также), но пока не умеем - его и нет

2023-01-26 20:09 UTC, rust379 requested changes

2023-01-26 20:09 UTC, rust379 commented on interface/medicine/medicineDrugForm.h
> +    QPushButton* createButton(const QString& text, F slot, const QString& objectName) {
А в BasicObjectForm не такой же метод?

2023-01-26 20:09 UTC, rust379 commented on interface/medicine/medicineDrugForm.cpp
> +                                          "titleCloseButton"));
Можно вынести вне ифа

2023-01-26 20:09 UTC, rust379 commented on interface/patient/patientForm.cpp
> +                                          "titleCloseButton"));
Можно вынести вне ифа

2023-01-26 20:09 UTC, rust379 commented on interface/service/serviceForm.cpp
> +                                          "titleCloseButton"));
Можно вынести вне ифа

2023-01-26 20:10 UTC, strizh78 commented on interface/basicForms/basicObjectForm/basicObjectForm.h
> +    QPushButton* createButton(const QString& text, void(F::* slot)(), const QString& objectName) {
Поищу, но сама нашла на SO)
Это ссылка на функцию-метод
F-базовый класс
void - возвращаемое значение

Если я правильно помню
Завтра смогу посмотреть подробнее

2023-01-26 20:11 UTC, strizh78 commented on interface/events/appointment/appointmentForm.ui
> +   <header location="global">interface/basicForms/titleWidget/titleWidget.h</header>
(В куте дизайнере)

2023-01-26 20:12 UTC, strizh78 commented on interface/events/personalEvent/personalEventForm.cpp
> +                                          "titleCloseButton"));
Сейчас - да
А когда появится кнопка "в архив", то порядок нарушится и я не уверена что стоит выносить сейчас, учитывая что это не смысловое обьединение, а просто "ну похоже код сейчас совпадает"

2023-01-26 20:15 UTC, rust379 commented on interface/events/appointment/appointmentForm.ui
> +   <header location="global">interface/basicForms/titleWidget/titleWidget.h</header>
Чтоб могли извне обратиться именно к этому виджету?

2023-01-26 20:17 UTC, strizh78 commented on interface/events/appointment/appointmentForm.ui
> +   <header location="global">interface/basicForms/titleWidget/titleWidget.h</header>
В куте дизайнере ты сначала ставишь на "площадь" просто QWidget
Потом нажимаешь "преобразовать в"

Вот чтобы в этом "преобразовать в" был виден виджет тайтла и не надо было для него каждый раз заново вводить путь и название класса - делаем его видимым, да

2023-01-26 20:17 UTC, rust379 commented on interface/events/personalEvent/personalEventForm.cpp
> +                                          "titleCloseButton"));
А когда появится "В архив", как изменятся эти кнопки? у них будет разное поведение?

2023-01-26 20:19 UTC, strizh78 commented on interface/events/personalEvent/personalEventForm.cpp
> +                                          "titleCloseButton"));
Мы уже договаривались что в данный момент хардкодить их порядок мы не хотим
Их вынесение хардкодит их порядок - мы не сможем вставлять удаление и перенесение в архив между ними



Плюс появится состояние "в архиве", когда мы вообще кнопку сохранить не заходим видеть
Только возвращение из архива и закрытие

2023-01-26 20:24 UTC, rust379 commented on interface/events/personalEvent/personalEventForm.cpp
> +                                          "titleCloseButton"));
Я бы тогда еще раз это обсудил, мы создаем одну и ту же кнопку в 2 разных местах только потому что "порядок",
пока мне это не нравится

2023-01-26 20:26 UTC, strizh78 commented on interface/events/personalEvent/personalEventForm.cpp
> +                                          "titleCloseButton"));
Может пока оставим так, а обсудив сделаю отдельное ревью?
Хочется тайтлики в проде)

2023-01-26 20:35 UTC, strizh78 commented on interface/events/personalEvent/personalEventForm.cpp
> +                                          "titleCloseButton"));
Я даже готова пока вынести из под ифа)

2023-01-27 10:58 UTC, strizh78 commented on interface/events/personalEvent/personalEventForm.cpp
> +                                          "titleCloseButton"));
>  только потому что "порядок"
что значит только потому что порядок?
мы не знаем в каком порядке кнопки в итоге будут максимально удобны
мы не знаем будут ли ещё кнопки в будущем
мы не знаем не захотим ли мы в каких-то местах их переименовать или перекрасить

мы не уверены везде ли будут кнопки сохранить/закрыть
например когда что-то в архиве, то там нет сохранения
если мы проводим приём - там нет закрытия

-------------
я вынесла из ифа пока
но потом оно все равно в него попадет (вообще, вероятно это будут отдельные функции setupCreateUi/setup..UI/..)

2023-01-29 10:07 UTC, rust379 approved these changes

2023-01-29 10:07 UTC, merged