mv buttons from basicForms to buttons dir
rust379/MApp pull request #265
Opened 2023-01-20 21:43 UTC by strizh78

кнопочки переехали
одна переименовалась (у меня кровь из глаз потекла от того как длинно и страшно выглядел путь к предыдущему имени)

потом они наверное ещё как-то совместятся и может их  станет меньше, но это уже другая история)

2023-01-26 20:10 UTC, rust379 commented on interface/tabs/tabsWidget/tabButton.h
> +#include "interface/basicForms/buttons/labeledButton/labeledButton.h"
надо будет что-то потом сделать с такими длинными путями

2023-01-26 20:14 UTC, rust379 requested changes

2023-01-26 20:14 UTC, rust379 commented on interface/basicForms/buttons/buttonWithEvents/buttonWithEvents.h
> +class ButtonWithEvents : public QPushButton {
Почему бы не просто Button? Не вижу необходимости в `WithEvents`, приписка не дает доп инфы

2023-01-26 20:14 UTC, strizh78 commented on interface/tabs/tabsWidget/tabButton.h
> +#include "interface/basicForms/buttons/labeledButton/labeledButton.h"
Да, но думаю отдельным тикетом
У нас уже есть один "баг" про капец длинный путь, думаю можно к нему прилинковать

2023-01-26 20:15 UTC, strizh78 commented on interface/basicForms/buttons/buttonWithEvents/buttonWithEvents.h
> +class ButtonWithEvents : public QPushButton {
Тут буквально в следующем ревью появится обработчик всех эвентов, чтобы лучше ховер обрабатывать
Поэтому так назвала

Лучше просто Button?

2023-01-26 20:17 UTC, rust379 commented on interface/tabs/tabsWidget/tabButton.h
> +#include "interface/basicForms/buttons/labeledButton/labeledButton.h"
Да, конечно отдельным)

2023-01-26 20:19 UTC, rust379 commented on interface/basicForms/buttons/buttonWithEvents/buttonWithEvents.h
> +class ButtonWithEvents : public QPushButton {
Кажется, у любой кнопки есть какие-то события, так что да, просто `Button` будет достаточно

2023-01-26 20:20 UTC, strizh78 commented on interface/basicForms/buttons/buttonWithEvents/buttonWithEvents.h
> +class ButtonWithEvents : public QPushButton {
Ок)

2023-01-29 10:09 UTC, rust379 approved these changes

2023-01-29 10:09 UTC, merged