add basic for stub
rust379/MApp pull request #268
Opened 2023-01-21 18:39 UTC by strizh78

сомневаюсь в названии класса
может просто Stub сделать?

2023-02-15 15:03 UTC, rust379 requested changes

2023-02-15 15:03 UTC, rust379 commented on interface/basicForms/notFoundStub/notFoundStub.h
> +    void addButton(QPushButton* button);
а предполагаются заглушки, которые будут изменяться? почему бы эти параметры сразу не задать в контрукторе?

2023-02-15 15:03 UTC, rust379 commented on interface/file/filesTabbedEditor/filesTabbedEditor.cpp
> +    auto loadButton = new QPushButton(QIcon(":/icons/load.png"), "");
может `upload`?

2023-02-15 15:05 UTC, rust379 commented
> сомневаюсь в названии класса может просто Stub сделать?

просто Stub очень абстрактно, под разные задачи могут быть разные заглушки, но notFound довольно узкоспециализированная)
если пока нет мест, где бы еще были заглушки, давай Stub сделаем, когда поймем, что нужна еще одна, но с другим дизайном, будем думать

2023-02-15 17:22 UTC, strizh78 commented on interface/basicForms/notFoundStub/notFoundStub.h
> +    void addButton(QPushButton* button);
их много + создание виджета обычно в списке инициализации, не хочется там спамить 5-6 строк подробностей его внешнего вида
методы позволяют отделить создание+настройку_принадлежности от деталей внешнего вида

2023-02-15 17:22 UTC, strizh78 commented on interface/basicForms/notFoundStub/notFoundStub.cpp
> +    title_->setWordWrap(true);
+

2023-02-21 20:27 UTC, rust379 commented on interface/basicForms/notFoundStub/notFoundStub.h
> +    void addButton(QPushButton* button);
Не будет такого происходить, что в случае создания и настройки внешнего вида, начнутся проблемы с размерами? тип либо сразу создастся с нужными размерами, либо он ставит что-то дефолтное, а потом уже картинка/кнопки не влезут, например?

2023-02-21 20:43 UTC, strizh78 commented on interface/basicForms/notFoundStub/notFoundStub.h
> +    void addButton(QPushButton* button);
Мммм, он вроде умеет понимать что изменился внутренний виджет и изменяет размеры внешнего если это возможно

2023-03-12 03:44 UTC, rust379 approved these changes
А коммиты  "Merge branch ... into stubs" откуда взялись? после  git pull?

2023-03-12 12:36 UTC, strizh78 commented
> А коммиты "Merge branch ... into stubs" откуда взялись? после git pull?

да, в гитхабе какие-то предложенные изменения были вкоммичены были, а локально другие

2023-03-12 12:43 UTC, merged