Fill data base tool
rust379/MApp pull request #275
Opened 2023-02-12 19:09 UTC by rust379

#273

2023-02-12 19:09 UTC, rust379 commented on interface/mainwindow.cpp
> +    addElementToMenu(QIcon(":/icons/leftMenu/database.png"), "Fill database",
Надо будет потом кнопку с тулзами красиво показывать

2023-02-16 15:49 UTC, strizh78 commented on database/prod/config.h
> +#if LAUNCH_MODE == DEVELOPMENT
а почему если девелопмент, то прод базу юзаем?

2023-02-16 15:53 UTC, strizh78 commented on database/prod/config.h
> +#if LAUNCH_MODE == DEVELOPMENT
что-то странно
я локально вернула этот иф как было, при этом остальное не трогала
т е (см скрины) и на них видно что он всё равно юзает прод-базу и прод-ветку-ифа
<img width="270" alt="Снимок экрана 2023-02-16 в 18 52 19" src="https://user-images.githubusercontent.com/38105548/219418036-fe5acc03-c66a-425b-8fea-74d8901b9d62.png">
<img width="378" alt="Снимок экрана 2023-02-16 в 18 52 30" src="https://user-images.githubusercontent.com/38105548/219418079-2bac4547-2bd5-4067-be88-374ee23139b7.png">

2023-02-16 15:55 UTC, strizh78 commented on database/prod/config.h
> +#if LAUNCH_MODE == DEVELOPMENT
больше скажу, я в новом файле поменяла все названия, а он этого даже не заметил (я пересобрала совсем с нуля)
т е "prod/config.h" использует не те же самые LAUNCH_MODE и остальное
<img width="316" alt="Снимок экрана 2023-02-16 в 18 55 12" src="https://user-images.githubusercontent.com/38105548/219418840-f3b7c234-9ae1-4e00-b1a4-055e6c86ec6c.png">

<img width="434" alt="Снимок экрана 2023-02-16 в 18 55 21" src="https://user-images.githubusercontent.com/38105548/219418880-8eaee398-98d4-46e2-9303-be5d866b8b78.png">

2023-02-16 15:57 UTC, strizh78 commented on database/prod/config.h
> +#if LAUNCH_MODE == DEVELOPMENT
@rust379 из-за чего так может быть?
у меня есть 3 предположения, расположены по убыванию вероятности
 - #include "config.h" в "prod/config.h"  - он же ищет ближайший такой файл по идее и вдруг он тут не внешний config.h подключает, а сам себя?
 - просто конфликт имен
 - видимость дефайна может какая-то не та?

2023-02-16 16:00 UTC, strizh78 commented on database/prod/config.h
> +#if LAUNCH_MODE == DEVELOPMENT
но оно плохо объясняет почему если я переоименовываю переменные, то оно не падает или хотя бы не говорит об этом (может они по дефолту все 0 и получаем 0 == 0 = true?)

кароч, может стоит ещё на #ifdef переменных этих проверять?

2023-02-19 12:14 UTC, rust379 commented on tools/fillDatabaseTool/fillDatabaseTool.cpp
> +    QSqlDatabase db = QSqlDatabase::addDatabase("QMYSQL", "fillDatabaseToolConnection");
Тут не очень красиво, что используются 2 подключения к базе (общее, через DatabaseInterface и вот это новое), но расширять стандартный интерфейс, добавляя возможность удаления - не хочу, но и дублировать его возможности в новом подключении для вставки и получения элементов тоже. 
Наследование от DatabaseSQL, не очень хорошо работает, так как идет повторная инициализация подключения (с тем же именем), и судя по предупреждениям, предыдущее подключение обрывается, 
Пока так работает, пусть будет, потом может придумаем что-то лучше

2023-02-19 12:16 UTC, rust379 commented on tools/fillDatabaseTool/fillDatabaseTool.cpp
> +        dropData();
Если понадобится, можно будет добавить какое-нибудь сообщение об ошибке, если что-то пошло не так, но пока этот момент опустил,
ошибки можно посмотреть в логах

2023-02-19 12:31 UTC, rust379 commented on database/prod/config.h
> +#if LAUNCH_MODE == DEVELOPMENT
замена на треугольные скобки вылечила проблему

2023-03-02 15:59 UTC, strizh78 requested changes

2023-03-02 15:59 UTC, strizh78 commented on MApp.pro
> +
давай хедерс перед sources поставим?

2023-03-02 15:59 UTC, strizh78 commented on MApp.pro
> +
а то они уже за всеми настройками и подобным оказались

2023-03-02 15:59 UTC, strizh78 commented on interface/mainwindow.cpp
> +    addElementToMenu(QIcon(":/icons/leftMenu/database.png"), "Fill database",
может назовём ее на русском пока?
а то всё на русском и тут внезапный fill)

2023-03-02 15:59 UTC, strizh78 commented on interface/mainwindow.cpp
> +
```suggestion
```

2023-03-02 15:59 UTC, strizh78 commented on interface/mainwindow.cpp
> +    FillDatabaseTool().run(database_, true);
давай добавим в комментарии что за true здесь?
что-то типа
FillDatabaseTool().run(database_, /*текст*/ true);

2023-03-02 15:59 UTC, strizh78 commented on interface/mainwindow.h
> +#if LAUNCH_MODE == DEVELOPMENT
может в самый низ убрать? или хотя бы после openWidget?
чтобы не прерывались значимые для прода функции на всякие ифы дева

2023-03-02 15:59 UTC, strizh78 commented on tools/fillDatabaseTool/fillDatabaseTool.cpp
> +QByteArray getFileBytes(const QString& fileName) {
у нас вроде эта функция есть в утилс уже?
а если нет, то давай ее туда вынесем (если ее нет там, то можно не в этом пр)? а то во всех местах загрузки файла одну и ту же функцию пишем

2023-03-02 15:59 UTC, strizh78 commented on tools/fillDatabaseTool/fillDatabaseTool.pri
> +    $$PWD/fillDatabaseTool.h
пока у нас табуляций нет, есть отдельный тикет на их добавление

2023-03-10 10:22 UTC, rust379 commented on tools/fillDatabaseTool/fillDatabaseTool.pri
> +    $$PWD/fillDatabaseTool.h
Почему бы в новых .pri не ставить сразу корректные табы?

2023-03-11 07:21 UTC, strizh78 approved these changes

2023-03-11 07:21 UTC, strizh78 commented on tools/fillDatabaseTool/fillDatabaseTool.cpp
> +    db.exec("SET FOREIGN_KEY_CHECKS = 0;");
Отключаем проверку ключей, чтобы не хардкодить порядок табличек?

А оно не навсегда применяется (в смысле того не надо ли вызвать потом обратно сет_...=1;)?

2023-03-11 07:48 UTC, rust379 commented on tools/fillDatabaseTool/fillDatabaseTool.cpp
> +    db.exec("SET FOREIGN_KEY_CHECKS = 0;");
Нет, оно применяется в рамках одного подключения, так что распространяется только на эту тулзу

2023-03-11 07:49 UTC, merged