tab hover icons
rust379/MApp pull request #277
Opened 2023-02-15 09:09 UTC by strizh78

кнопочки теперь именно ховером над основным табом, а не сдвигают его контент вбок
<img width="497" alt="Снимок экрана 2023-02-15 в 12 09 23" src="https://user-images.githubusercontent.com/38105548/218983396-bcc87e18-9f76-466c-a86b-78faa172d689.png">

2023-02-15 18:22 UTC, strizh78 commented
MAPP-2

2023-02-15 18:25 UTC, strizh78 commented
https://tracker.yandex.ru/MAPP-2

2023-02-17 12:23 UTC, rust379 requested changes

2023-02-17 12:23 UTC, rust379 commented on interface/basicForms/buttons/labeledButtonWithHover/labeledButtonWithHover.h
> +class HoverWidget : public QFrame {
а нет желания этот класс куда-то в подпапку засунуть?

2023-02-17 12:23 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
> +    auto createHoverButton = [] (const QString& iconPath, const QString& color) {
такое точно стоит делать лямбдой, а не полноценной функцией?

2023-02-17 12:23 UTC, rust379 commented on interface/basicForms/buttons/labeledButtonWithHover/labeledButtonWithHover.cpp
> +    hoverWidget_->setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(255, 255, 255, 210), stop:0.3 rgba(255, 255, 255, 255));"
какая-то магия)
а эта строка не супер длинная получилась?

2023-03-02 16:00 UTC, strizh78 commented on interface/basicForms/buttons/labeledButtonWithHover/labeledButtonWithHover.h
> +class HoverWidget : public QFrame {
есть, но пока не знаю точно куда
пусть пока тут побудет
мне надо немного посмотреть за ним и его изменением)

2023-03-02 16:02 UTC, strizh78 commented on interface/basicForms/buttons/labeledButtonWithHover/labeledButtonWithHover.cpp
> +    hoverWidget_->setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(255, 255, 255, 210), stop:0.3 rgba(255, 255, 255, 255));"
авто-сгенерированная каким-то онлайн генератором градиентов + подправленная под куте)
делить градиент на 2 строки не хочется, он и так страшный и непонятный
думаю просто чуть подождать пока оно уедет в .qss файл и там уже разбираться

(в последнее время прохожу, собираю такие штуки в qss, тут просто ещё нет готового под эту строку)

2023-03-02 16:04 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
> +    auto createHoverButton = [] (const QString& iconPath, const QString& color) {
[по крайней мере пока] оно используется только тут, смысловая нагрузка у неё нулевая, просто способ убрать часть дублирования при создании схожих кнопочек
кажется вполне подходит для использования как лямбды

2023-03-23 16:42 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
> +    auto createHoverButton = [] (const QString& iconPath, const QString& color) {
сделала

2023-03-23 16:43 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.cpp
> +    auto createHoverButton = [] (const QString& iconPath, const QString& color) {
посмотришь ревью?)

2023-03-23 17:07 UTC, rust379 requested changes
Немного разверну комментарий про расположение `createHoverButton`, вот у нас есть 
`LabeledButton `- кнопка с лейблом, может сделать так же `HoveredButton`, тогда `createHoverButton` будет не нужно, а `labeledButtonWithHover` просто отнаследовать от этих двух классов, т.е. мы делаем класс-опцию, а потом их комбинируем

2023-03-23 17:10 UTC, strizh78 commented
> Немного разверну комментарий про расположение `createHoverButton`, вот у нас есть 
> 
> `LabeledButton `- кнопка с лейблом, может сделать так же `HoveredButton`, тогда `createHoverButton` будет не нужно, а `labeledButtonWithHover` просто отнаследовать от этих двух классов, т.е. мы делаем класс-опцию, а потом их комбинируем

LabeledButton имеет свое особое поведение, для него класс осмыслен
ХоверБаттон имеет всего лишь другой стайлшит, который в будущем переедет в .qss файлик 
Для ховербаттона не вижу смысла в отдельном классе, по крайней мере на данный момент

2023-03-23 17:14 UTC, strizh78 commented on interface/interfaceUtils.cpp
> +                                "}";
```suggestion
    QString hoveredStyleSheet = "QPushButton {"
                                    "border: 0;"
                                    "background: #DCDCDC;"
                                    "border-radius: 8px;"
                                "}"
                                "QPushButton:hover {"
                                    "background-color: %1;"
                                "}";
```

2023-03-23 17:15 UTC, strizh78 commented on interface/interfaceUtils.cpp
> +                                "}";
поправила, посмотришь?)

2023-03-28 08:35 UTC, rust379 approved these changes

2023-03-28 08:35 UTC, merged