files Tabbed Editor Refactoring
rust379/MApp pull request #278
Opened 2023-02-15 13:19 UTC by strizh78

2023-03-29 09:01 UTC, rust379 requested changes

2023-03-29 14:59 UTC, strizh78 commented on interface/basicForms/buttonsExclusiveList/buttonsExclusiveList.h
> +        for (auto& button : menuButtonsGroup_->buttons()) {
кнопка удаляется из лейаута -> у кнопки меняется родитель -> не const вроде

2023-03-31 20:34 UTC, strizh78 commented on interface/basicForms/stackedWidget/stackedWidgetHeader.h
> +    QWidget* tabContent(const QString& tabName);
```suggestion
    QWidget* tabContent(const QString& tabName) const;
```

2023-03-31 20:34 UTC, strizh78 commented on interface/basicForms/stackedWidget/stackedWidgetHeader.cpp
> +QWidget* StackedWidgetHeader::tabContent(const QString& tabName) {
```suggestion
QWidget* StackedWidgetHeader::tabContent(const QString& tabName) const {
```

2023-03-31 20:35 UTC, rust379 approved these changes

2023-03-31 20:35 UTC, rust379 commented on interface/basicForms/stackedWidget/stackedWidgetHeader.h
> +    QWidget* tabContent(const QString& tabName);
константный метод?

2023-03-31 20:37 UTC, strizh78 commented on interface/basicForms/stackedWidget/stackedWidgetHeader.h
> +    QWidget* tabContent(const QString& tabName) const;
```suggestion
    QWidget* tabContent(const QString& tabName);
```

2023-03-31 20:37 UTC, strizh78 commented on interface/basicForms/stackedWidget/stackedWidgetHeader.cpp
> +QWidget* StackedWidgetHeader::tabContent(const QString& tabName) const {
```suggestion
QWidget* StackedWidgetHeader::tabContent(const QString& tabName) {
```

2023-03-31 20:46 UTC, merged