v0.0 of editableList
rust379/MApp pull request #282
Opened 2023-02-16 09:55 UTC by strizh78

тут ещё надо будет доработать поведение
есть вопросы по нему к Андрею, но базово версия работает
ну и плюс вероятно нужны будут ховерики, но это потом

иконку тоже уже существующую взяла, не заменяла пока

вот как выглядит сейчас
<img width="1024" alt="Снимок экрана 2023-02-16 в 12 51 34" src="https://user-images.githubusercontent.com/38105548/219330609-d7fd5db0-223b-4e28-9157-55a39e75c741.png">

<img width="991" alt="Снимок экрана 2023-02-16 в 12 52 45" src="https://user-images.githubusercontent.com/38105548/219330971-9cae43e8-25e1-492f-829c-2e636c5abdc1.png">

2023-03-03 07:51 UTC, rust379 requested changes

2023-03-03 07:51 UTC, rust379 commented on interface/basicForms/editableList/editableList.cpp
> +void EditableList::setRegExp(const QRegExp &regExp) {
Может понятнее обозвать метод, что тут установка именно валидатора поля

2023-03-03 07:51 UTC, rust379 commented on interface/basicForms/editableList/editableList.cpp
> +    lineEdit->setAttribute(Qt::WA_MacShowFocusRect, false);
Это только для мака флаг? а для винды есть что-то подобное или там не надо?

2023-03-03 07:51 UTC, rust379 commented on interface/basicForms/editableList/editableList.qss
> +    font-family: "Montserrat", "Montserrat Medium";
А то что мы в мейне (или где-то там), на уровне приложения, устанавливаем шрифт (семейство), тут не срабатывает?

2023-03-03 07:51 UTC, rust379 commented on interface/basicForms/editableList/editableList.h
>      void setDataList(const std::vector<QString>& data);
Конечно эти строчки не менялись, но все же, 
нужен ли тут суффикс "List" ?

2023-03-03 08:35 UTC, strizh78 commented on interface/basicForms/editableList/editableList.cpp
> +    lineEdit->setAttribute(Qt::WA_MacShowFocusRect, false);
только для мака
я же тебе рассказывала, у мака по дефолту при фокусе на lineEdit появляется странная синяя рамка вокруг, эта штука её убирает

2023-03-03 08:41 UTC, strizh78 commented on interface/basicForms/editableList/editableList.cpp
> +void EditableList::setRegExp(const QRegExp &regExp) {
setRegExpForValidator звучит очень длинно)

2023-03-03 08:42 UTC, strizh78 commented on interface/basicForms/editableList/editableList.h
>      void setDataList(const std::vector<QString>& data);
возможно в версии v.0.1 этого листа)
он же скоро должен эволюционировать чтобы поддерживать 2 колонки и копирование при нажатии

2023-03-12 04:00 UTC, rust379 commented on interface/basicForms/editableList/editableList.cpp
> +void EditableList::setRegExp(const QRegExp &regExp) {
setValidator ? то, что принимает регулярку - понятно из типа аргумента

2023-03-12 04:05 UTC, rust379 commented on interface/basicForms/editableList/editableList.h
>      void setDataList(const std::vector<QString>& data);
Как будто и при нескольких колонках он не нужен, мы находимся в контексте какого-то списка (editableList) и устанавливаем какие-то данные, еще раз говорить, что мы находимся в списке - не нужно

2023-03-22 14:17 UTC, rust379 requested changes

2023-03-22 14:17 UTC, rust379 commented on interface/basicForms/editableList/editableList.cpp
> +    lay_->setVerticalSpacing(0);
Как будто я где-то уже это видел)

2023-03-22 14:17 UTC, rust379 commented on interface/basicForms/editableList/editableList.cpp
> +void EditableList::setLabelText(const QString &labelText) {
```suggestion
void EditableList::setLabelText(const QString& labelText) {
```

2023-03-22 14:17 UTC, rust379 commented on interface/basicForms/editableList/editableList.cpp
> +void EditableList::setData(const std::vector<QString> &data) {
```suggestion
void EditableList::setData(const std::vector<QString>& data) {
```

2023-03-22 14:17 UTC, rust379 commented on interface/basicForms/editableList/editableList.cpp
> +void EditableList::addRow(const QString &rowData) {
```suggestion
void EditableList::addRow(const QString& rowData) {
```

2023-03-22 16:39 UTC, strizh78 commented on interface/basicForms/editableList/editableList.cpp
> +void EditableList::setLabelText(const QString &labelText) {
надо бы разобраться как заставить qt генерить нормально код

2023-03-22 16:40 UTC, strizh78 commented on interface/basicForms/editableList/editableList.h
> +    std::vector<QString> getData();
да, и ты там сказал что сделаем это отдельным pr)

2023-03-23 11:48 UTC, rust379 approved these changes

2023-03-23 11:50 UTC, merged