Event form design
rust379/MApp pull request #284
Opened 2023-03-25 20:04 UTC by strizh78

пока без красивого выбора времени
для него хочется пару штук сделать сначала, ревью стало бы слишком разнородным)

тут данные переносятся в одну строку, появляются пара красивостей и файлики

2023-03-29 09:38 UTC, rust379 requested changes

2023-03-29 09:38 UTC, rust379 commented on database/prod/fileDB.h
> +    void link(const File& file, const PersonalEvent& event) override;
Еще бы тут анлинк, 
\+ прорастить вплоть до удаления файла (но это когда-то потом)

2023-03-29 09:38 UTC, rust379 commented on database/prod/fileDB.h
> +    void filesByEvent(const PersonalEvent&, std::vector<File>&) override;
константный метод

2023-03-29 09:38 UTC, rust379 commented on database/prod/fileDB.cpp
> +void FileDB::filesByEvent(const PersonalEvent &event, std::vector<File> &receiver) {
```suggestion
void FileDB::filesByEvent(const PersonalEvent& event, std::vector<File>& receiver) {
```

2023-03-29 09:38 UTC, rust379 commented on database/prod/fileDB.cpp
> +void FileDB::link(const File &file, const PersonalEvent &event) {
```suggestion
void FileDB::link(const File& file, const PersonalEvent& event) {
```

2023-03-29 11:05 UTC, strizh78 commented on interface/interfaceUtils.h
> +std::optional<File> selectFileFromDisk(QWidget* parent = nullptr);
File все же про сущность файла 
А это про интерфейс - показать меню выбора->проверить->обработать

2023-03-29 11:06 UTC, strizh78 commented on database/prod/fileDB.h
> +    void filesByEvent(const PersonalEvent&, std::vector<File>&) override;
методы выше не помечены константными 
Кажется это лучше делать вместе всё

2023-03-29 11:06 UTC, strizh78 commented on database/prod/fileDB.h
> +    void link(const File& file, const PersonalEvent& event) override;
У приема же нет анлинка
И кнопочки для удаления нет пока

Может вместе с удалением все же это делать?

2023-03-29 14:55 UTC, rust379 commented on interface/interfaceUtils.h
> +std::optional<File> selectFileFromDisk(QWidget* parent = nullptr);
Про сущность - да, но и про то, как с ним работать, а добавление с диска - довольно важный момент в работе с файлом. С интерфейсом, конечно, есть взаимодействие, но это не наш интерфейс, а взаимодействие с чем-то внешним, так что ок - если будет в самом файле

2023-03-29 14:56 UTC, rust379 commented on database/prod/fileDB.h
> +    void filesByEvent(const PersonalEvent&, std::vector<File>&) override;
Новые/затрагиваемые методы в пр можно уже делать "как надо"

2023-03-29 14:56 UTC, strizh78 commented on interface/interfaceUtils.h
> +std::optional<File> selectFileFromDisk(QWidget* parent = nullptr);
нуу, фиг знает
мне кажется всё же не нужно интерфейс тащить в объекты

2023-03-29 15:00 UTC, rust379 commented on interface/interfaceUtils.h
> +std::optional<File> selectFileFromDisk(QWidget* parent = nullptr);
Тут немного посредственный интерфейс, раз используем внешний сервис, но ладно, давай пока оставим

2023-03-29 15:01 UTC, strizh78 commented on database/prod/fileDB.h
> +    void filesByEvent(const PersonalEvent&, std::vector<File>&) override;
но если начнем делать ту задачку, то заходя в файл будешь видеть - нет константных, значит до этого файла ещё не добрались и его надо проверять
а если смесь, то ничего не понятно будет и надо проверять вообще все файлы заново будет

2023-03-31 09:34 UTC, strizh78 commented on database/prod/fileDB.h
> +    void link(const File& file, const PersonalEvent& event) override;
https://tracker.yandex.ru/MAPP-68

2023-03-31 09:40 UTC, strizh78 commented on database/prod/fileDB.h
> +    void filesByEvent(const PersonalEvent&, std::vector<File>&) override;
так просто сделать конст только этот новый метод нельзя
он использует handleListResult, который не конст

2023-03-31 20:26 UTC, strizh78 commented on interface/interfaceUtils.cpp
> +
```suggestion
```

2023-03-31 20:29 UTC, rust379 approved these changes

2023-03-31 20:37 UTC, merged