File buttons change type
rust379/MApp pull request #287
Opened 2023-04-02 07:46 UTC by strizh78

Используем LabeledButtonWithHover как базу для FIleButton
зачем: потому что у этих кнопочек будет ховер :)
он нужен в том числе для печати, например

внешне пока ничего не меняется

2023-04-07 08:27 UTC, rust379 requested changes

2023-04-07 08:27 UTC, rust379 commented on interface/file/filesTabbedEditor/fileButton.cpp
> +    : LabeledButtonWithHover("", parent)
Может сделать доп конструктор, чтоб не передавать пустые аргументы?

2023-04-07 08:27 UTC, rust379 commented on interface/basicForms/labeledComponents/labeledFrameStyle.qss
> -
это была лишняя строчка? одна пустая в конце файла осталась?

2023-04-07 08:27 UTC, rust379 commented on interface/basicForms/labeledComponents/labeledFrame.cpp
> +    auto marginTop = isVisible ? 5 : 0;
1 - Может ли лейбл становиться видимым/невидимым в процессе работы
2 - Если ответ на 1 вопрос "да", то в каком случае и не прыгает ли интерфейс от изменения марджина?

2023-04-07 08:37 UTC, strizh78 commented on interface/basicForms/labeledComponents/labeledFrame.cpp
> +    auto marginTop = isVisible ? 5 : 0;
1 - да, в расписании в одном месте, но мы возможно его выпилим
2 - нет, оно это делает не массово, и вероятно потом не будет делать

но функция в таком виде мне нравится больше, чем сувать очередной аргумент в конструктор
почему: 
1 - большие конструкторы заставляют идти кровь из глаз
2 - аргумент надо вписывать перед QWidget* parent [потому что всё, относяшееся к текущему виджету - выше], но тогда чтобы указать родителя, надо будет явно вписывать true/false, что очень неочевидно и каждый раз надо будет комментарий добавлять

2023-04-07 08:37 UTC, strizh78 commented on interface/basicForms/labeledComponents/labeledFrameStyle.qss
> -
поправлю

2023-04-07 08:38 UTC, strizh78 commented on interface/file/filesTabbedEditor/fileButton.cpp
> +    : LabeledButtonWithHover("", parent)
надо бы, но отдельно лучше
там надо вынести тогда часть логики и распределить правильно + проверить что q_property про текст от этого не навернется
могу тикет завести

2023-04-12 14:16 UTC, rust379 approved these changes

2023-04-13 15:55 UTC, merged