timeline popup as widget
rust379/MApp pull request #292
Opened 2023-04-02 21:18 UTC by strizh78

<img width="665" alt="Снимок экрана 2023-04-03 в 00 14 39" src="https://user-images.githubusercontent.com/38105548/229379350-b11737ac-c7ed-4a6e-af45-a22c58e7b1c2.png">

у нас вот этот попап раньше "рисовался" (т е не был виджетом, а именно рисовался цветными пикселями вручную)
у этого 2 минуса:
 1 - рисовать руками не круто)
 2 - он требовал чтобы виджет таймлайна был достаточно высоким, чтобы его в себя вместить, а дизайн предусматривает что этот попап может выходить за "зону" таймлайна 

соответсвенно, тут происходит 2 вещи
1 - делаем попап не картинкой, а виджетом
2 - подгоняем размеры таймлайна и в целом верхнего блока расписания под фигму

2023-04-07 09:07 UTC, rust379 requested changes

2023-04-07 09:07 UTC, rust379 commented on interface/timetable/timetableTop/dailyTimeline/widgets/dailyTimelineLine.h
> +#include <QLabel>
а где используется?

2023-04-07 09:07 UTC, rust379 commented on interface/timetable/timetableTop/dailyTimeline/widgets/dailyTimelineLine.cpp
> +    popupWidget_->setTimeText(hovered_->begin.toString("hh:mm") + " — " + hovered_->end.toString("hh:mm"));
Давай эту логику закинем внутрь `DailyTimelinePopup`

2023-04-07 09:09 UTC, strizh78 commented on interface/timetable/timetableTop/timetableTop.h
> +    int collapsedHeight_ = 117;
с целью?

2023-04-07 10:30 UTC, strizh78 commented on interface/timetable/timetableTop/timetableTop.h
> +    int collapsedHeight_ = 117;
в любом случае, эта штука скоро уйдет, меня бесят эти цифры в коде
или в qss переедут, или будет автоматом значение высчитываться

2023-04-12 14:21 UTC, rust379 approved these changes

2023-04-13 15:34 UTC, merged