MAPP-72 Tabs data update
rust379/MApp pull request #293
Opened 2023-04-06 15:33 UTC by strizh78

### По сути
Обновляем данные в табиках с помощью обсервера 

Чтобы это делать, делаем для каждого табика класс TabSmallForm
В котором каждый табик может выбирать какие в нём будут данные и как они отображаются + подключить себе обсервер на нужные объекты/действия
Пока только обновление (удаление у нас пока не поддержано нигде)

### Визуально
До этого у нас только 3 типа табиков были "проработаны" (у них был дизайн из фигмы), а остальным просто ставился WindowTitle из формы объекта
Тут все типы табиков получают дизайн из фигмы (его раньше не было у пациента/услуги/лекарства/etc)

### Дополнительно (aka рефакторинг)
 - Убираем из tabCreator.cpp свалку функций (там было много функций на "все случаи жизни" - для разных типов табиков)
 - Убираем дурацкие файлики, в которых 90% было дублирования в последнее время
 - начинаем все текстовые приписки держать в одном месте - если надо будет что-то пофиксить, то не надо будет по миллиону мест ходить
 - задаем стили текстов в табиках в одном месте (и это не код, а qss файлик)
 - раньше каждый табик сам создавал себе виджет и лейаут для смолл формы --> дублировалось много дурацкких созданий одинакового лейаута и его настроек --> тут это все унифицируется, теперь табик создаёт только лейблики для своих данных

да, они остаются немного похожими
но похожа только общая оберточка, вся суть - разная
если объединять их дальше, то из чистых и понятных классов получим монстра-месиво, не хотю так(

2023-04-12 15:15 UTC, rust379 requested changes

2023-04-12 15:15 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/smallForms/patientTabSmallForm.cpp
> +    updateData();
а если пришел не тот объект, почему все равно апдейт вызываем?

2023-04-12 15:15 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/smallForms/patientTabSmallForm.cpp
> +      , nameLabel_(new QLabel)
съехало

2023-04-12 15:15 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/smallForms/homeopathyTabSmallForm.cpp
> +      , groupLabel_(new QLabel)
съехало

2023-04-12 15:15 UTC, rust379 commented on interface/tabs/tabsManager/tabsCreator/smallForms/calendarWidgetTabSmallForm.cpp
> +    todayButton->connect(todayButton, &QPushButton::clicked, calendar, [calendar] () { calendar->setSelectedDate(QDate::currentDate()); });
не супер длинная строка?

2023-04-29 09:00 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/smallForms/tabSmallForm.cpp
> +{
да, это конструктор

2023-04-29 09:00 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/tabsCreator.h
>  #include "database/databaseInterface.h"
ну я поменяла просто потому что смотрится лучше

но вообще база тут сильно менее важна, она же просто прокидывается внутрь и всё

2023-05-24 14:53 UTC, rust379 approved these changes

2023-05-25 13:07 UTC, merged