MApp-20 - Add query filters.
rust379/MApp pull request #294
Opened 2023-04-14 17:03 UTC by rust379

Добавлены классы `TableInfo `для получения информации о таблицах БД (название + колонки)
Добавлены классы `Clause` для возможности делать более точные запросы, в т.ч. `WhereClause` для фильтрации данных в запросе
Порефакторены классы запросов
Добавлена возможность получения значения из колонки результата запроса по имени колонки, а не ее номеру

2023-04-19 15:29 UTC, strizh78 commented on database/prod/queryClauses/queryClauses.h
> +using ClausePtr = std::shared_ptr<const BaseClause>;
внутрь класса / в неймспейс?

2023-04-19 15:30 UTC, strizh78 commented on database/prod/queryClauses/queryClauses.h
> +
```suggestion
```

2023-04-19 15:31 UTC, strizh78 commented on database/prod/queryClauses/queryClauses.h
> +    LimitClause(int offset, int limit);;
```suggestion
    LimitClause(int offset, int limit);
```

2023-04-19 15:35 UTC, strizh78 commented on database/prod/queryClauses/queryClauses.h
> +    QueryClauses(const std::vector<const BaseClause*> clauses);
константный указатель?
https://metanit.com/cpp/tutorial/4.4.php

2023-04-19 16:04 UTC, strizh78 commented on database/prod/appointmentDB.h
> +private:
```suggestion
```

2023-04-19 16:07 UTC, strizh78 commented on database/prod/appointmentDB.cpp
```suggestion
```

2023-04-19 16:07 UTC, strizh78 commented on database/prod/appointmentDB.cpp
> +    table_ = new AppointmentsTableInfo();
в лист инициализации?

2023-04-21 18:02 UTC, strizh78 commented
21.04.2023 20:59:37:065  [INFO]     [DATABASE] Inserting into appointments FAILURE
21.04.2023 20:59:37:065  [INFO]     [DATABASE] Started insert into appointments
21.04.2023 20:59:37:065  [Error]    [DATABASE] Field 'patient' doesn't have a default value
21.04.2023 20:59:37:065  [Error]    [DATABASE] QMYSQL3: Невозможно выполнить выражение
21.04.2023 20:59:37:065  [Error]    [DATABASE] INSERT INTO appointments (id,
	isDeleted,
	date,
	isConducted) VALUES (?, ?, ?, ?);

2023-04-23 08:38 UTC, rust379 commented
> 21.04.2023 20:59:37:065 [INFO] [DATABASE] Inserting into appointments FAILURE 21.04.2023 20:59:37:065 [INFO] [DATABASE] Started insert into appointments 21.04.2023 20:59:37:065 [Error] [DATABASE] Field 'patient' doesn't have a default value 21.04.2023 20:59:37:065 [Error] [DATABASE] QMYSQL3: Невозможно выполнить выражение 21.04.2023 20:59:37:065 [Error] [DATABASE] INSERT INTO appointments (id, isDeleted, date, isConducted) VALUES (?, ?, ?, ?);

У меня не воспроизводится, ветка отведена от свежего мастера, проверял на новой базе
Надо смотреть, почему у тебя возникает ошибка. Судя по сообщению - при инсерте в appointment не прокидываются гомеопатия услуга и пациент, это может возникнуть, если у приема нет этих полей или у них код 0

2023-04-23 08:47 UTC, rust379 commented on database/prod/queryClauses/queryClauses.h
> +    QueryClauses(const std::vector<const BaseClause*> clauses);
Не получилось в такое, где-то прочитал, что вектор вообще не может в константы внутри из-за каких-то внутренних причин, но вот потерял ссылку, где это неплохо описывалось

2023-04-23 08:54 UTC, rust379 commented on database/prod/query.cpp
> +    LOG_INFO("DATABASE") << QString("Started update item in %1").arg(table_) << Qt::endl;
Видимо, изначально это было сделано "в процессе работы", а потом не возвращено обратно,
пока верну и заведу задачу на переделку этого места,
пусть в лог пишется просто таблица, с которой идет взаимодействие, а where и другие опции - только при падении.
Возможно, в какой-то момент можно будет убрать и сообщение с таблицей, оставить только варнинги и ошибки

2023-04-23 09:17 UTC, rust379 commented on database/prod/appointmentDB.cpp
> +    table_ = new AppointmentsTableInfo();
appointmentDB.cpp:14:7: Member initializer 'table_' does not name a non-static data member or base class

2023-04-23 10:06 UTC, strizh78 commented
> > 21.04.2023 20:59:37:065 [INFO] [DATABASE] Inserting into appointments FAILURE 21.04.2023 20:59:37:065 [INFO] [DATABASE] Started insert into appointments 21.04.2023 20:59:37:065 [Error] [DATABASE] Field 'patient' doesn't have a default value 21.04.2023 20:59:37:065 [Error] [DATABASE] QMYSQL3: Невозможно выполнить выражение 21.04.2023 20:59:37:065 [Error] [DATABASE] INSERT INTO appointments (id, isDeleted, date, isConducted) VALUES (?, ?, ?, ?);
> 
> У меня не воспроизводится, ветка отведена от свежего мастера, проверял на новой базе Надо смотреть, почему у тебя возникает ошибка. Судя по сообщению - при инсерте в appointment не прокидываются гомеопатия услуга и пациент, это может возникнуть, если у приема нет этих полей или у них код 0

> ветка отведена от свежего мастера
1. хард-ресетнула явно на мастер текущий (взяла прям с гита номер коммита)
3. счекаутила ветку твою
<img width="576" alt="Снимок экрана 2023-04-23 в 13 02 26" src="https://user-images.githubusercontent.com/38105548/233833190-ad6d4c32-22cd-40d4-ae55-15dd8394fbf4.png">

4. полностью удалила папку с текущей сборкой
5. заменила имя базы, чтобы она была новая
6. нажала заполнить базу
-->
всё равно падает с теми же ошибками

2023-04-23 11:50 UTC, strizh78 commented
Клаусы расслеляем по разным файлам
Можно в общей подпапке

2023-04-29 08:17 UTC, strizh78 commented on database/prod/config.h
> +    const QString DATABASE_NAME = "mapp-test-2";
не надо, наверное

2023-05-31 16:52 UTC, strizh78 commented on database/prod/tables/field/field.cpp
> +QString toString(const std::vector<Field>& src, std::string sep) {
заиспользовать String toString(const std::vector<T>& src, std::string sep = " ") {

2023-05-31 16:58 UTC, strizh78 requested changes

2023-05-31 16:58 UTC, strizh78 commented on database/prod/tables/field/field.cpp
> +bool Field::operator ==(const Field& other) const {
перед не-Field методами

2023-05-31 16:58 UTC, strizh78 commented on database/prod/tables/field/field.cpp
> +std::ostream& operator<<(std::ostream& out, const Field& f) {
std::ostream& operator <<(std::ostream& out, const Field& f) {

2023-06-11 10:35 UTC, rust379 commented on database/prod/tables/field/field.cpp
> +QString toString(const std::vector<Field>& src, std::string sep) {
Чтот не удалось) завел тикет, там разберемся
https://tracker.yandex.ru/MAPP-82

2023-06-12 09:24 UTC, strizh78 approved these changes

2023-06-12 09:24 UTC, strizh78 commented on database/prod/query.h
> +    const QString SELECT_PART_TEMPLATE = "SELECT\n%1";
я бы отделила саб-класс от переменных отдельной привейт секцией
как отделяем функции от переменных

```suggestion
private:
    const QString SELECT_PART_TEMPLATE = "SELECT\n%1";
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/queryClauses/baseClause.cpp
> +BaseClause::~BaseClause() {}
в .h ещё можно спорить, но в cpp все функции раскрываем
тогда виднее начало-конец функции при чтении по диагонали и виднее что она задумана как пустая // вроду считается что это как с пустым фором и ';' - если скобки остались сверху, то это могло быть случайно
плюс если станет не-пустой, то просто пишешь тело и всё - не надо двиганием скобок заниматься

вроде и куте сейчас поставили стиль с раскрытием (хотя вроде он и так стоял?)

строки бесконечные, экономить не надо)

```suggestion
BaseClause::~BaseClause() {
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/queryClauses/baseClause.cpp
> +{};
а зачем точка с запятой в конце?
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/queryClauses/limitClause.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/queryClauses/limitClause.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/queryClauses/orderClause.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/queryClauses/orderClause.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/queryClauses/queryClauses.cpp
> +QueryClauses::QueryClauses() {}
```suggestion
QueryClauses::QueryClauses() {
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/queryClauses/whereClause.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/queryClauses/whereClause.cpp
> +WhereStatement::~WhereStatement() {}
если в конструкторах со списком инициализации ешё можно подумать ад скобками, то вот здесь без их переноса вообще теряется что это функция.

```suggestion
WhereStatement::~WhereStatement() {
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/queryClauses/queryClauses.cpp
> +    clauses_.clear();
clear вроде сам вызывается при уничтожении вектора?
путаю?

2023-06-12 09:24 UTC, strizh78 commented on database/prod/queryClauses/whereClause.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/queryClauses/whereClause.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/queryClauses/whereClause.h
> +    SQL_OPERATORS oper_;
oper_ -> operator_?

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/appointmentFilesTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/appointmentFilesTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/appointmentFilesTable.h
> +    const AppointmentFilesFields* fields;
```suggestion
public:
    const AppointmentFilesFields* fields;
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/appointmentsTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/appointmentsTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/baseTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/baseTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/baseTable.h
> +
```suggestion

public:
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/eventsFilesTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/eventsFilesTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/field/field.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/field/field.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/filesTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/filesTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/homeopathyTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/homeopathyTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/medicinesTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/medicinesTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/patientsTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/personalEventsTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/personalEventsTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/prescribedMedicationsTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/serviceFilesTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/serviceFilesTable.cpp
> +{}
```suggestion
{
}
```

2023-06-12 09:24 UTC, strizh78 commented on database/prod/tables/servicesTable.cpp
> +{}
```suggestion
{
}
```

2023-07-25 10:58 UTC, strizh78 approved these changes

2023-07-25 11:03 UTC, strizh78 requested changes

2023-07-25 11:03 UTC, strizh78 commented on database/prod/query.cpp
> +    auto replace = [](const QString& str) -> QString {
А это зачем вообще?
У QString есть replace встроенный ведь

2023-07-25 16:11 UTC, strizh78 approved these changes

2023-07-26 03:56 UTC, merged