Templates
rust379/MApp pull request #295
Opened 2023-05-11 08:33 UTC by strizh78

2023-05-11 09:25 UTC, strizh78 commented on interface/file/templateParser.cpp
>  void TemplateParser::parseAppointment(QString& templateData, const Appointment& appointment) {
этот файл в будущем сильно похудеет по идее (если вообще не умрёт, не знаю)

пока он остаётся в таком виде, потому что я не для всех блоков успела его "перенести"
тут есть закомменченные строки - пусть они пока останутся, в текущем виде они уже не работают, но я хочу чтобы они остались до следующего ревью, где они переедут в настройку внешнего вида блока

(тип где для длительности ты можешь выбрать как эта длительность будет написана)


+ тут пока остаётся выбор лекарств, потому что мы так и не согласовали пока что это за блок такой и как он должен выглядеть

2023-05-11 09:25 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/fileTab.cpp
> +        fullForm = new FileForm(tabBase, database_);
файловая форма снова жива!)
кстати, ей нужен дизайн

2023-05-11 09:25 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/fileTab.cpp
> +    infoLay->setContentsMargins(0, 0, 0, 0);
```suggestion
```

2023-05-11 09:25 UTC, strizh78 commented on interface/textEditor/textEditor.cpp
> +    // процесс загрузки
в следующих ревью возможно тут немного переделаю загрузку, но прямо сейчас
1 - тут и так почти 2к строк)
2 - смотреть на эту загрузку не могу уже 🥲

2023-05-11 09:25 UTC, strizh78 commented on interface/textEditor/textEditor.cpp
> +    if (!jsInteractor_->isConnected()) {
если мы вызываем метод раньше, чем загрузки всякие завершились, то мы ставим его в очередь и запускаем в правильное время

возможно эта часть переедет в jsInteractor, но пока не знаю
он и так самый непонятный из всех наших классов уже)

2023-06-11 10:26 UTC, rust379 requested changes

2023-06-11 10:26 UTC, rust379 commented on interface/file/template/templateForm.cpp
> +
тут не лишняя пустая строка?

2023-06-11 10:26 UTC, rust379 commented on interface/file/template/widgets/blockEditors/templateSubBlockEditor.cpp
> +                             "}";
нужен таб

2023-06-11 10:26 UTC, rust379 commented on interface/file/template/widgets/blockEditors/templateSubBlockEditor.cpp
> +    for (const auto& [editorText, dataText, dataRef] : data_) {
не знал, что так можно,
оно возвращает поля в порядке описания структуры?

2023-06-11 10:26 UTC, rust379 commented on interface/file/template/widgets/blockEditors/templateSubBlockEditor.h
> +    };
кажется, под это стоит завести функцию заполнения,

2023-06-11 10:26 UTC, rust379 commented on interface/file/template/widgets/templateBlockEditorTab.cpp
> +
лишняя пустая строка

2023-06-11 10:26 UTC, rust379 commented on interface/file/template/widgets/templateBlockEditorTab.cpp
> +    if (data.blockType == "block") {
blockType не заслуживает енама?

2023-06-11 10:26 UTC, rust379 commented on interface/file/template/widgets/templateCreator.cpp
> +    connect(fileEditor_, &TemplateViewer::blockLoaded, this, &TemplateCreator::processLoadedBlock);
коннекты как-то вперемешку, давай их в каком-то порядке отсортим, например сначала для `blocksManager_`, потом для `fileEditor_`

2023-06-11 10:26 UTC, rust379 commented on interface/file/template/widgets/templateCreator.cpp
> +    data.blockName = "block_" + QString::number(++maxBlockNumber_);
если создался блок с названием `block_0` потом я его переименовал (а у нас сейчас есть переименование?) назвал `block_1`, новый блок тоже будет иметь такое название,
может идти от 0 (или от 1), пока не найдем число, которое нам подходит для суффикса?

2023-06-11 10:26 UTC, rust379 commented on interface/file/template/widgets/templateCreator.cpp
> +    blocksManager_->addBlock(data);
в `subBlockCreate мы устанавливаем тип блока, а почему тут это не делается? оно где-то по умолчанию ставится на "block"?

2023-06-11 10:26 UTC, rust379 commented on interface/file/template/widgets/templateCreator.cpp
> +    blockData.blockName = "block_" + QString::number(++maxBlockNumber_);
аналогично комментарию выше про переименование

2023-06-11 10:26 UTC, rust379 commented on interface/file/template/widgets/templateCreator.cpp
> +    QString numberString = data.blockName.mid(data.blockName.lastIndexOf("_") + 1);
где-то читал, что предпочтительнее использовать sliced, вместо `mid` если возможно,
почему - не помню)

2023-06-11 10:26 UTC, rust379 commented on interface/file/template/widgets/templateBlocksSelector.cpp
> +                  "}");
таб бы добавить)

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blockFullEditMode.js
> +            activeElement == zone.nextSibling)
стоит использовать `===`, более строгое сравнение

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +        blockData["blockName"] = block.id;
в js к полям можно через точку обращаться, `blockData.blockName`, в скобках обычно если у тебя название поля лежит в переменной

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    for (const block of blocks) {
через forEach как-то больше по JS-овски)

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +            parent.blockLoaded(blockData);
можно немного упростить,
```
const blockData = {
    blockName: subblock.id,
    blockType: "sub_block",
    dataText: blockContent.textContent,
    dataRef: blockContent.dataset.data_link,
    parentBlockName: block.id,
}
```

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    const parentBlock = blockData["parentBlockName"];
используется только в 1 месте, парой строк ниже, может туда сразу и положить, без доп переменной? или хотя бы внутрь ветки ифа, где используется

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    if (blockData["blockType"] == "sub_block") {
в js лучше сравнивать через `===`

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +        const p = parentB.querySelector('.content-block');
`const p = document.querySelector('#' + parentBlock).querySelector('.content-block')` ?
если слишком длинно - можно по точке переносить
```
const p = document
    .querySelector('#' + parentBlock)
    .querySelector('.content-block');
```

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    if (blockType == "sub_block") {
`===`

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +        // btn.target = "_blank";
?

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    const blockType = blockData["blockType"];
Можно воспользоваться деструктуризацией
`const { blockType } = blockData;`

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    link.dataset.data_link = blockData["dataRef"];
данные из `blockData` можно через точку получать, blockData.dataRef

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/script.js
> +    var scale =  iframeWidth / idealWidth;
const?

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/script.js
> +      }
```
mutationsList
    .filter(m => ['childList', 'characterData'].includes(m.type))
    .forEach(m => parent.iframeHtmlChanged());
```

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/script.js
> +    if (event.key === 'Enter') {
давай заретурнимся, если не та кнопка, чтоб лишнего сдвига не было

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/script.js
> +        const focusNode = window.getSelection()?.focusNode;
Воу, новый синтаксис) а если в `window.getSelection()` не будет `focusNode` оно что вернет? ниже не упадет?

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/script.js
> +        const allowedText = ["p", "br", "b", "em"];
это наверно `allowedTags`?

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/script.js
> +    if (wasinited == false) {
`===`

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/script.js
> +        wasinited = true;
wasInited или isInited, давай добавим большую букву, не сразу понял, что это 2 разных слова)

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/script.js
> +    var blocks = document.querySelectorAll(`.block`);
const?

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/script.js
> +        window.setupBlock(block);
`blocks.forEach(block => window.setupBlock(block));`

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/script.js
> +    }
аналогично тому что выше, forEach

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/script.js
> +    if (editMode == "READ_ONLY") {
1 - `===`
2 - ну прям тянет же на енам)

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    if (blockType != "sub_block") {
1 - `!==`
2 - `blockType` не тянет на енам?)

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/iframe/style.css
> +}
github ругается, просит пустую строку в конце)

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/optionsScript.js
> +document.getElementById('foreColorButton').addEventListener('click', () => {
вызов теряется в окружении, может все вызовы ниже тоже обернуть в функции, а потом из одного места вызвать сначала их, а потом `initializer`?

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/optionsScript.js
> +    const defaultFont = 12;
дефолтный шрифт от ОС не зависит? вроде был какой-то косяк, что на маке и винде шрифты отличаются, или это не то?

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/qtScript.js
> +let qtChannel = new QWebChannel(qt.webChannelTransport, () => {
а почему оно не const?

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/qtScript.js
> +    });
давай тут стрелочную заиспользуем, мы же современные)
просто `function()` заменить на `() =>`

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/qtScript.js
> +    document.getElementById('output').contentWindow.changeBlock(blockDataStruct)
а зачем тут пустая строка?

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/qtScript.js
> +    document.getElementById('output').contentWindow.createBlock(blockData);
и тут пустая строка

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/qtScript.js
> +    qtChannel.objects.textEditorInteractor.clickSubBlock(data_link);
А можно `qtChannel.objects.textEditorInteractor` вынести в константу наверх? чтоб убрать большое количество обращений через точку

2023-06-11 10:26 UTC, rust379 commented on interface/textEditor/textEditor/script.js
> +    var height = window.innerHeight - paddingTop - paddingBottom;
const?

2023-06-11 10:34 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/fileTab.cpp
> +        fullForm = new FileForm(tabBase, database_);
Отдельно, там FileForm переписать надо будет
Это ещё ооочень старая форма, надо нее немного проверить и может передизайнить

2023-06-11 10:35 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/fileTab.cpp
> +        tabType =  "шаблон";
2 строки? А зачем?
Не люблю енамы)

2023-06-11 10:36 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blockFullEditMode.js
> +    }
И сделать менее понятно тем самым(

2023-06-11 10:38 UTC, strizh78 commented on interface/file/template/templateForm.cpp
> +void TemplateForm::saveForm() {
Просто close занят Qt)

2023-06-11 10:39 UTC, strizh78 commented on interface/file/template/templateForm.cpp
> +    }
Я давно говорю что хочу просто вызывать условный update
А оно пусть само решает изменить данные или сначала создать, а потом изменить)

2023-06-11 10:40 UTC, strizh78 commented on interface/file/template/templateForm.cpp
> +    close();
Эта штука должна просто закрыть форму

closeForm должна обрабатывать закрытие без сохранения и тут её звать не надо

У нас же точно также во всех других формах...

2023-06-11 10:41 UTC, strizh78 commented on interface/file/template/widgets/blockEditors/templateSubBlockEditor.cpp
> +    for (const auto& [editorText, dataText, dataRef] : data_) {
Да

2023-06-11 10:41 UTC, strizh78 commented on interface/file/template/widgets/blockEditors/templateSubBlockEditor.h
> +    };
Зачем? 
Тут оно сразу определяется, не вызывая лишние функции

2023-06-11 10:42 UTC, strizh78 commented on interface/file/template/widgets/templateBlockEditorTab.cpp
> +    if (data.blockType == "block") {
В js мы можем передавать строки.

2023-06-11 10:43 UTC, strizh78 commented on interface/file/template/widgets/templateCreator.cpp
> +    data.blockName = "block_" + QString::number(++maxBlockNumber_);
У нас нет переименования

2023-06-11 10:44 UTC, strizh78 commented on interface/file/template/widgets/templateCreator.cpp
> +    blockData.blockName = "block_" + QString::number(++maxBlockNumber_);
У нас пока нет переименования
Когда оно будет - это будет внутренний id блока и его все равно нельзя будет менять

2023-06-11 10:46 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    for (const block of blocks) {
Переделаю, видимо

2023-06-11 10:47 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    if (blockData["blockType"] == "sub_block") {
Кто придумал этот ваш js 🙈

2023-06-11 10:49 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    const blockType = blockData["blockType"];
Зачем?
Я точно запутаюсь
Простое обращение выглядит понятнее, учитывая то что мне это потом понимать

То что ты предлагаешь глобально быстрее?

2023-06-11 10:50 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/script.js
> +      }
И сразу ничего не понятно с первого взгляда(

2023-06-11 10:50 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/script.js
> +    if (event.key === 'Enter') {
Мы же потом и комбинации переопределять будем
Будет огромное условие у реторна в будущем тогда

2023-06-11 10:54 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/script.js
> +    if (editMode == "READ_ONLY") {
Ну не передам я тебе енам из плюсов

А и там и тут кастовать - тупо миллиард функций по касту плодить

2023-06-11 10:55 UTC, strizh78 commented on interface/textEditor/textEditor/qtScript.js
> +let qtChannel = new QWebChannel(qt.webChannelTransport, () => {
Потому что не работает
Оно вообще вроде на ладан дышит иногда)

2023-06-11 10:56 UTC, strizh78 commented on interface/textEditor/textEditor/optionsScript.js
> +    const defaultFont = 12;
Шрифт везде одинаковый уже - монсеррат

2023-06-11 10:57 UTC, strizh78 commented on interface/textEditor/textEditor/qtScript.js
> +    qtChannel.objects.textEditorInteractor.clickSubBlock(data_link);
Нельзя

2023-06-11 10:57 UTC, strizh78 commented on interface/textEditor/textEditor/qtScript.js
> +    qtChannel.objects.textEditorInteractor.clickSubBlock(data_link);
Уже пробовали в прошлый раз

2023-06-11 10:57 UTC, strizh78 commented on interface/textEditor/textEditor/qtScript.js
> +    qtChannel.objects.textEditorInteractor.clickSubBlock(data_link);
Не работает и всё тут

Оно там как-то динамически меняется из плюсов магией

И если ты пихаешь в переменную, то переменная ссылается на "необновленную" версию, которая не работает

2023-06-11 11:01 UTC, strizh78 commented on interface/file/template/widgets/templateCreator.cpp
> +    blocksManager_->addBlock(data);
Оно уже в blockData стоит
Мы тут только айтишник получаем

2023-06-11 11:02 UTC, strizh78 commented on interface/tabs/tabsManager/tabsCreator/fileTab.cpp
> +        tabType =  "шаблон";
Дубль того что выше (прям строки совпадают), там ответила

2023-06-11 11:03 UTC, strizh78 commented on interface/textEditor/blockData.h
> +    QString parentBlockName;
Не, оно передаётся в js
хочется чтобы смысл точно не потерялся 
(Названия структуры самой там уже не будет)

2023-06-11 11:03 UTC, strizh78 commented on interface/textEditor/jsInteractor.h
> +    // отослать данные в JS
Если делать, то отдельно
Мы один то канал еле научились нормально добавлять
А тут надо 2)

2023-06-11 11:06 UTC, strizh78 commented on interface/textEditor/textEditor/qtScript.js
> +    document.getElementById('output').contentWindow.createBlock(blockData);
Я не понимаю о какой строке речь

2023-06-28 08:35 UTC, strizh78 commented on file/fileConverter/fileConverter.cpp
> +    }
тут надо бы с Андреем обсудить и с тобой
потому что мы получаем пустой текстовый блок, который вроде как по нашим правилам должен иметь нулевую высоту --> в него невозможно попасть?

2023-06-28 08:37 UTC, strizh78 commented on file/fileConverter/defaultHTMLFile
да

2023-06-28 08:38 UTC, strizh78 commented on interface/basicForms/stackedWidget/stackedWidgetArea.cpp
> +    }
не вызывается сигнал изменения индекса, если на самом деле он не поменялся

2023-06-28 08:43 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blockFullEditMode.js
> +            }
можно было бы и замену предложить :)

2023-06-28 08:45 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +            var blockData = {};
> через forEach
лучше предложением было бы

2023-06-28 08:47 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +        blockData["blockType"] = "block"; // брать из class-list?
странная тема
в ревью коммент есть, а у меня в коде нет

при этом статус показывает что изменений нет)

2023-06-28 08:48 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blockReadOnlyMode.js
> +            parent.clickSubBlock(data_link);
длиннее)

2023-06-28 08:49 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blockReadOnlyMode.js
гит задвоил коммент?

<img width="848" alt="Снимок экрана 2023-06-28 в 11 48 54" src="https://github.com/rust379/MApp/assets/38105548/074770a1-cf79-4ae5-b496-6588ff72ba0f">

2023-06-28 08:50 UTC, strizh78 commented on interface/file/displayWidgets/templateViewer.cpp
> +    appointment.setStartDateTime(QDateTime(QDate(2022, 11, 07), QTime(17, 15)));
надо обсудить тогда

дату - можно
время - хотелось бы нет, чтобы не получилось двусмысленности и человек не подумал "видимо тут не назначенное время приёма, а текущее время проведения будет"

2023-06-28 08:54 UTC, strizh78 commented on interface/file/template/widgets/templateBlockEditorTab.cpp
> +
предложением

2023-06-28 08:55 UTC, strizh78 commented on interface/file/template/widgets/templateCreator.cpp
> +    QString numberString = data.blockName.mid(data.blockName.lastIndexOf("_") + 1);
а тут возможно?

2023-06-28 08:55 UTC, strizh78 commented on interface/file/template/widgets/templateBlocksSelector.cpp
> +                  "}");
предложением бы добавить :)

2023-06-28 08:57 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    for (const block of blocks) {
ой нет, там несущий фор
на нём разменивать читабельность на модность не готова, мне с ним ещё работать
остальные поправила

2023-06-28 09:01 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/script.js
> +        const focusNode = window.getSelection()?.focusNode;
вроде работает норм)

2023-06-28 09:02 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/script.js
> +    if (wasinited == false) {
даже на бул он не может без 3х равно норм проверить?!
странный ваш язык)

2023-06-28 09:03 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/script.js
> +    }
аналогично предложением.

2023-06-28 09:06 UTC, strizh78 commented on interface/textEditor/textEditor/qtScript.js
> +    });
предложением бы оно заменилось быстрее :)

2023-06-28 09:11 UTC, strizh78 commented on interface/textEditor/textEditor.cpp
> +        if (slotsQueue.contains("setHtml")) {
не знаю, хочется тут вообще на ссылки на слоты как-то перейти попробовать, но может в рамках отдельного тикета придумать такую очередь, которая будет такое уметь

2023-06-29 15:42 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    block.appendChild(blockContent);
```suggestion
    block.appendChild(blockContent);
    block.append('\u2028');
```

2023-07-14 14:25 UTC, rust379 commented on interface/textEditor/textEditor/optionsScript.js
> +    const defaultFont = 12;
Я про размер шрифта, что тип на винде он 12, на маке 8 (или наоборот), и оно как-то не матчилось поначалу

2023-07-14 14:51 UTC, rust379 requested changes

2023-07-14 14:51 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blockFullEditMode.js
> +        document.querySelectorAll('.dropzone').forEach((zone1) => {
а что за `zone1` `zone2`, у них нет более понятного названия? или может этот индекс просто убрать?

2023-07-14 14:51 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
>          blockData["parentBlockName"] = "main_layout";
```
const blockData = {
  blockName: block.id,
  blockType: "block",
  parentBlockName: "main_layout",
};

```
?

2023-07-14 14:51 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +            const blockData = {
просто оставлю это здесь)
https://eslint.org/docs/latest/rules/no-shadow
В данном случае не критично, но все же

2023-07-14 14:51 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +                    .querySelector('.content-block');
```suggestion
          .querySelector('#' + parentBlock)
          .querySelector('.content-block');
```

2023-07-15 08:55 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +                    .querySelector('.content-block');
а почему?
хочу чтобы выделялось

2023-07-15 08:56 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blockFullEditMode.js
> +        })
```suggestion
        document.querySelectorAll('.dropzone').forEach((zone) => {
            zone.style.visibility = 'visible';
        })
```

2023-07-15 08:56 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blockFullEditMode.js
>      })
```suggestion
        document.querySelectorAll('.dropzone').forEach((zone) => {
            zone.style.visibility = 'hidden';
        })
    })
```

2023-07-15 08:58 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blockFullEditMode.js
> +    })
```suggestion
        document.querySelectorAll('.dropzone').forEach((zone) => {
            zone.style.visibility = 'hidden';
        })
    })
```

2023-07-15 09:02 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +        blockData["parentBlockName"] = "main_layout";
```suggestion
        const blockData = {
                blockName: block.id,
                blockType: "block",
                parentBlockName: "main_layout",
        };
```

2023-07-15 09:05 UTC, strizh78 commented on interface/textEditor/textEditor/optionsScript.js
> +    const defaultFont = 12;
нет,
это было из-за того что дефолтный шрифт самих операционных систем разный и они по разному выглядят в одинаковых размерах

сейчас у нас одинаковый шрифт - Montserrat и он одинаково выглядит на маке и винде

2023-07-16 15:11 UTC, strizh78 commented on interface/file/filesTabbedEditor/verticalTabbedListWidget.cpp
> +    auto scrollArea = new QScrollArea(this);
если у приёма все ок, то у услуг, при числе шаблонов больше X, оч плохо выводились они
там не было скролла --> если суммарная высота больше данной, то они начинали сжиматься и в итоге мало того что некрасиво, так ещё и усложняло выбор/клик

теперь всё ок

2023-07-26 04:11 UTC, rust379 approved these changes

2023-07-26 04:11 UTC, rust379 commented on interface/basicForms/buttonsExclusiveList/buttonsExclusiveList.h
> +    void setSizeConstraint(QLayout::SizeConstraint constraint);
const& тут будет лишним?

2023-07-26 04:11 UTC, rust379 commented on interface/file/filesTabbedEditor/verticalTabbedListWidget.cpp
> +    return filesList;
Может сразу ретурнить?
`return static_cast<ButtonsExclusiveList*>(scrollArea->widget());`

2023-07-26 05:13 UTC, strizh78 commented on interface/basicForms/buttonsExclusiveList/buttonsExclusiveList.h
> +    void setSizeConstraint(QLayout::SizeConstraint constraint);
Это элемент енама, мне казалось они меньше ссылки весят

2023-07-26 05:14 UTC, strizh78 commented on interface/file/filesTabbedEditor/verticalTabbedListWidget.cpp
> +    return filesList;
Не, тогда не до конца понятно что это без имени переменной
+ кажется сюда в каком-то ревью я добавляла ещё строк

2023-07-26 05:19 UTC, merged