Service fixes
rust379/MApp pull request #299
Opened 2023-06-29 11:34 UTC by strizh78

микро магия, которая чуть правит дизайн (это вообще не финальный вариант, но шажок к нему :) )
и из важного, оно фиксит что сейчас вообще никак нельзя было привязать/отвязать шаблоны (там поломалась магия и выделение работало неверно), тут добавляется способ это сделать
он НЕ финальный и не очень удобный, но пока не согласуем дизайн - пусть будет хоть такой, а то совсем неработающая муть - плохо

<img width="785" alt="Снимок экрана 2023-06-29 в 14 31 33" src="https://github.com/rust379/MApp/assets/38105548/85e617fb-1aae-416e-bd43-b3c5f18de123">

2023-07-29 18:39 UTC, rust379 requested changes

2023-07-29 18:39 UTC, rust379 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +        blockData["parentBlockName"] = "main_layout";
Странные изменения пролезли

2023-07-29 18:41 UTC, strizh78 commented on interface/file/filesTabbedEditor/filesTabbedEditor.qss
> +    max-width: 16px;
нет, из-за лейаутов qt не умеет в фиксированный размер 
если так написать - для него это будет просто рекомендация (которую он чаще всего игнорит) )

2023-07-29 18:45 UTC, strizh78 commented on interface/service/serviceForm.cpp
> +    if (service_.duration <= QTime(/*hours*/ 0, /*mins*/ 0)) {
там стандартная кутешная муть, от неё что угодно можно ожидать)

2023-07-29 18:46 UTC, strizh78 commented on interface/service/serviceForm.cpp
> +    noTemplatesStub_->setCommentText("Создайте новый вручную! 🐱");
это не продовые формулировки, Андрей пока не смотрел
просто нечто короткое и передающее суть

2023-07-29 18:46 UTC, strizh78 commented on interface/service/serviceForm.cpp
> +    noTemplatesStub_->setCommentText("Создайте новый вручную! 🐱");
потом надо будет все пересогласовать
потому что те что есть в фигме тоже немного не про то сейчас

2023-07-29 19:08 UTC, strizh78 commented
переделала мерж на мастер,
все замечания выше или поправила или ответила

2023-08-18 13:05 UTC, rust379 commented on interface/file/filesTabbedEditor/filesTabbedEditor.qss
> +    max-width: 16px;
Даже если ему написать !important - все равно игнорит?

2023-08-18 13:07 UTC, strizh78 commented on interface/file/filesTabbedEditor/filesTabbedEditor.qss
> +    max-width: 16px;
прям где-то в доке написано что пользуйтесь min и max

2023-08-18 13:08 UTC, strizh78 commented on interface/file/filesTabbedEditor/filesTabbedEditor.qss
> +    max-width: 16px;
обычная для него просто совет

2023-08-18 13:09 UTC, rust379 commented on interface/service/serviceForm.cpp
> +    if (service_.duration <= QTime(/*hours*/ 0, /*mins*/ 0)) {
А может воспользоваться QTime::isNull() ?
И сверху еще навесить QTime::isValid()?)

2023-08-18 13:09 UTC, strizh78 commented on interface/file/filesTabbedEditor/filesTabbedEditor.qss
> +    max-width: 16px;
<img width="675" alt="Снимок экрана 2023-08-18 в 16 09 40" src="https://github.com/rust379/MApp/assets/38105548/40e08982-b428-4f67-be13-a5cb2a310880">

2023-08-18 13:14 UTC, strizh78 commented on interface/service/serviceForm.cpp
> +    if (service_.duration <= QTime(/*hours*/ 0, /*mins*/ 0)) {
оно не может быть ни тем, ни тем
а когда там появится нормальный виждет для выбора времени, то QTime вообще перестанет фигурировать

2023-08-26 06:44 UTC, rust379 approved these changes

2023-08-26 15:35 UTC, merged