Patient design
rust379/MApp pull request #301
Opened 2023-07-15 17:48 UTC by strizh78

добавила новый виджет, который используется у пациента в фио/инициалах и дате рождения/возрасте
заодно немного поправила createWidgetForLayout - он теперь требует передачи ему родителя (это надо чтобы в содержимое лейаута верно передавались стили, иначе они затираются, особенно на винде)

получилось что-то такое
<img width="1091" alt="Снимок экрана 2023-07-15 в 20 41 45" src="https://github.com/rust379/MApp/assets/38105548/57d70844-88fb-4467-8440-e71238e06bf6">

было так
<img width="1065" alt="Снимок экрана 2023-07-15 в 20 43 27" src="https://github.com/rust379/MApp/assets/38105548/38a4f1a7-b8f5-44c6-9b0a-ab58276798f8">

2023-07-26 04:29 UTC, rust379 requested changes

2023-07-26 04:29 UTC, rust379 commented on interface/basicForms/labeledComponents/labeledDoubleLineEdit/labeledDoubleLineEdit.h
> +    void setSecondVisible(bool isVisible);
А в каком случае у нас не видна вторая часть? пока первая не введена?

2023-07-26 04:29 UTC, rust379 commented on interface/basicForms/labeledComponents/labeledDoubleLineEdit/labeledDoubleLineEdit.cpp
> +    connect(secondLineEdit_, &QLineEdit::editingFinished, this, &LabeledDoubleLineEdit::secondEditingFinished);
А как это работает? тип проброска сигнала дальше?

2023-07-26 04:29 UTC, rust379 commented on interface/basicForms/labeledComponents/labeledDoubleLineEdit/labeledDoubleLineEdit.cpp
> +    setSecondVisible(false);
Хорошо ли тут сразу ставить ее невидимой? не должна ли это решать сторона, которая использует класс?
А если в этом классе все же предполагается, что одна часть главная, а другая дополнительная, предлагаю это и в именах отразить
сейчас `first second` довольно равноправны

2023-07-26 04:29 UTC, rust379 commented on interface/basicForms/labeledComponents/labeledDoubleLineEdit/labeledDoubleLineEdit.h
Функционал first и second совпадает практически, и совпадает с [labeledLineEdit](https://github.com/rust379/MApp/blob/master/interface/basicForms/labeledComponents/labeledLineEdit/labeledLineEdit.h)
Давай это как-то объединим

2023-07-26 05:11 UTC, strizh78 commented on interface/basicForms/labeledComponents/labeledDoubleLineEdit/labeledDoubleLineEdit.h
> +    void setSecondVisible(bool isVisible);
По дефолту да

2023-07-26 05:11 UTC, strizh78 commented on interface/basicForms/labeledComponents/labeledDoubleLineEdit/labeledDoubleLineEdit.cpp
> +    connect(secondLineEdit_, &QLineEdit::editingFinished, this, &LabeledDoubleLineEdit::secondEditingFinished);
Да

2023-07-26 05:12 UTC, strizh78 commented on interface/basicForms/labeledComponents/labeledDoubleLineEdit/labeledDoubleLineEdit.cpp
> +    setSecondVisible(false);
Метод установки видимости публичный
Родитель, если хочет изменить дефолтное поведение, может это сделать

2023-07-26 05:12 UTC, strizh78 commented on interface/basicForms/labeledComponents/labeledDoubleLineEdit/labeledDoubleLineEdit.h
Поясни подробнее

2023-08-26 06:49 UTC, rust379 commented on interface/basicForms/labeledComponents/labeledDoubleLineEdit/labeledDoubleLineEdit.h
Выделить базовый класс, в котором будут методы `setText()` `text()` `signal textEditingFinished()` `lineEdit()`

2023-08-26 10:00 UTC, strizh78 commented on interface/basicForms/labeledComponents/labeledDoubleLineEdit/labeledDoubleLineEdit.h
это просто дублирование QLineEdit

2023-08-26 11:00 UTC, rust379 approved these changes

2023-08-26 11:47 UTC, merged