MAPP-84 Medicines redesign
rust379/MApp pull request #302
Opened 2023-07-15 18:50 UTC by strizh78

Удаляем дозировки, удаляем цену (её давно удалили, но почему-то в ui файлике осталось поле)
Добавила скролл, иначе не влезают в текущем виде торговые наименования

ещё начала немного править формы выпуска, потом может докину

по дизайну тут ничего нового пока, только немного паддинги поправила и делиметер поставила
Потом докину скрин

2023-07-16 08:37 UTC, strizh78 commented on interface/basicForms/adaptiveLayout/adaptiveLayout.cpp
> +    int left, top, right, bottom;
страшная магия, у qt есть пример для этого лейаута - взято оттуда
я поубирала ненужные нам методы, немного поправила куски некоторые

тут не трогала - очень магическая магия)

2023-07-16 08:55 UTC, strizh78 commented on interface/medicine/medicineDrugReleaseFormSelectForm.ui
тут был только лейаут, поэтому снесла

2023-07-16 08:56 UTC, strizh78 commented on interface/medicine/medicineDrugReleaseFormSelectForm.cpp
> +        checkBox->setFixedWidth(maxWidth);
если не менять ширину, то у всех чекбоксов разная ширина и они плохо встают в колонки (они плавают и очень плохо читается)

2023-08-04 16:19 UTC, rust379 requested changes

2023-08-14 15:52 UTC, strizh78 commented on interface/basicForms/adaptiveLayout/adaptiveLayout.cpp
> +int AdaptiveLayout::doLayout(const QRect &rect, bool setGeometry) const {
> тут не трогала - очень магическая магия)
это кутешный код

2023-08-14 15:53 UTC, strizh78 commented on interface/basicForms/adaptiveLayout/adaptiveLayout.cpp
> +            item->setGeometry(QRect(QPoint(x, y), item->sizeHint()));
> тут не трогала - очень магическая магия)

это кутешный код

2023-08-14 15:53 UTC, strizh78 commented on interface/basicForms/adaptiveLayout/adaptiveLayout.cpp
> +        const QWidget *wid = item->widget();
> тут не трогала - очень магическая магия)

это кутешный код

2023-08-26 06:57 UTC, rust379 commented on interface/basicForms/adaptiveLayout/adaptiveLayout.cpp
> +int AdaptiveLayout::doLayout(const QRect &rect, bool setGeometry) const {
В каком плане "кутешный код"? он же лежит у нас в basicForms, а не где-то еще, и вызываем эти методы мы, а не передаем куда-то в магию qt (или передаем?)

2023-09-07 08:40 UTC, strizh78 commented on interface/basicForms/adaptiveLayout/adaptiveLayout.cpp
> +int AdaptiveLayout::doLayout(const QRect &rect, bool setGeometry) const {
ну я попыталась, но там какой-то страшной магией они это все считают

2023-09-07 08:45 UTC, strizh78 commented on interface/basicForms/adaptiveLayout/adaptiveLayout.cpp
> +int AdaptiveLayout::doLayout(const QRect &rect, bool setGeometry) const {
там они пересчитывают сразу много и поделить это красиво не получается
или целиком дублировать или mutable ставить

2023-09-13 11:11 UTC, rust379 requested changes

2023-09-13 11:11 UTC, rust379 commented on interface/basicForms/adaptiveLayout/adaptiveLayout.cpp
> +        }
Как предложение, 
а может это вынести в отдельную функцию `setItemsGeometry` или как-то еще, и убрать тут передачу setItemGeometry
1 - Получается мы в константном методе что-то меняем
2 - В методе с названием "посчитать ..." мы что-то устанавливаем

При написании комментария увидел, что тут используются `x, y` которые вычисляются чуть выше. Но в целом идею с отделением "установки" и "подсчета" я бы рассмотрел

2023-09-16 10:10 UTC, strizh78 commented on interface/basicForms/adaptiveLayout/adaptiveLayout.cpp
> +    return { };
нет

2023-09-16 10:11 UTC, strizh78 commented on interface/basicForms/adaptiveLayout/adaptiveLayout.cpp
> +        }
я пыталась, но там дублирование 90% вычислений, мне не нравится

2023-09-16 10:13 UTC, strizh78 commented on interface/basicForms/adaptiveLayout/adaptiveLayout.cpp
> +    return itemList_.value(index);
1 - оно не умрет, а вернет дефолтное значение просто
2 - это согласовано с другими лейаутами куте

2023-09-16 10:14 UTC, strizh78 commented on interface/basicForms/adaptiveLayout/adaptiveLayout.cpp
> +    while (itemList_.size() > 0) {
```suggestion
    while (!itemList_.empty()) {
```

2023-09-16 10:14 UTC, strizh78 commented on interface/basicForms/adaptiveLayout/adaptiveLayout.h
> +
```suggestion

```

2023-09-23 13:06 UTC, strizh78 commented on interface/basicForms/adaptiveLayout/adaptiveLayout.cpp
> +    return { };
вроде наоборот дефолт говорит что ограничений нет

2023-09-27 09:22 UTC, rust379 approved these changes

2023-09-27 15:00 UTC, merged