Homeopathy design
rust379/MApp pull request #303
Opened 2023-07-16 10:10 UTC by strizh78

редизайн разведений и паддинги/дивайдеры у самой формы

<img width="1377" alt="Снимок экрана 2023-07-16 в 13 09 11" src="https://github.com/rust379/MApp/assets/38105548/d38394e9-1d31-48b9-84fd-56983ce055d7">

2023-08-04 16:19 UTC, rust379 requested changes

2023-08-14 15:59 UTC, strizh78 commented on interface/homeopathy/homeopathyDrugDilutionsSelectForm.cpp
> +        if (prefix != dilutionsByPrefix.firstKey()) {
у кутешного мапа почему-то нет красивого разложения, а некрасивое хуже этого


> contentLay.count() > 0

тогда мы завязываемся на лейаут и то, что в нем должно лежать
смотреть по добавляемому контенту правильнее

2023-08-14 15:59 UTC, strizh78 commented on interface/homeopathy/homeopathyDrugDilutionsSelectForm.cpp
> +    for (auto checkBox : findChildren<QCheckBox*>()) {
это же указатели

2023-08-14 16:00 UTC, strizh78 commented on interface/homeopathy/homeopathyDrugDilutionsSelectForm.cpp
> +    for (auto checkBox : findChildren<QCheckBox*>()) {
```suggestion
    for (const auto checkBox : findChildren<QCheckBox*>()) {
```

2023-08-26 07:01 UTC, rust379 approved these changes

2023-08-26 10:11 UTC, merged