Template medicines
rust379/MApp pull request #305
Opened 2023-07-29 17:46 UTC by strizh78

2023-07-29 18:14 UTC, strizh78 commented on interface/textEditor/textViewMode.h
> +enum class TextViewMode {
смотрела - оно не совсем совпадает по логике с readOnly/fullEdit и т д
те - больше про то можно ли редактировать контент и насколько сильно

это - про то как отображаются "сабблоки" - как прототипные штучки для редактора шаблонов или как модные разные виджеты во время превью/проведения приёма

по сути - по этой штуке переключаем разные css файлики -> меняется внешний вид виджетов

потом сюда ещё добавим принт - чтобы для печати убирать всё лишнее

2023-07-29 18:17 UTC, strizh78 commented on interface/events/appointment/appointmentForm.cpp
>  void AppointmentForm::homeopathyChoosed(QVariant data) {
совсем умрут чуть позже
пока пусть побудут заглушками

2023-07-29 18:22 UTC, strizh78 commented on interface/events/appointment/appointmentForm.cpp
> +        auto name = "medicine_" + QString::number(medicine.code());
да, тут кусочки похожи
но они похожи только пока мы не сделаем лекарства полноценно
потом у лекарств и имя и текст будут задаваться иначе
а объединять с шаблонами и кучей аргументов ради 3х строк - у нас так уже было и в итоге я теперь пытаюсь такие места искоренять
если есть идеи как сделать это красиво - можно подумать
если нет - просто ждем как в итоге получатся лекарства с настройкой внешнего вида и тогда уже смотреть

2023-08-13 08:39 UTC, rust379 requested changes

2023-08-13 08:43 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/script.js
> +    var link = document.createElement('link');
```suggestion
    const link = document.createElement('link');
```

2023-08-13 08:44 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/script.js
> +    var linkNode = document.getElementById(cssId);
```suggestion
    const linkNode = document.getElementById(cssId);
```

2023-08-13 08:44 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/prototype.css
> +    background-color:#EBEBEB;
```suggestion
    background-color: #EBEBEB;
```

2023-08-13 08:47 UTC, strizh78 commented on interface/events/appointment/appointmentForm.cpp
> +        blockData.dataText = medicine.tradeNames[0];
v0, пока нельзя
это заглушка, пока ждем нормальный дизайн

2023-08-13 08:48 UTC, strizh78 commented on interface/events/appointment/appointmentForm.cpp
> +MAppTable* AppointmentForm::createSingleSelectionForm(ItemDBInterface<T>* databaseItem, CreateRowFunc createRowFunc,
её надо убить)

2023-08-13 08:50 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +        }
с расчетом на то что сабтайпов будет больше 2х

2023-08-13 08:51 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/preview.css
> +}
```suggestion
}

```

2023-08-13 08:51 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +        var blockSubtype = "";
```suggestion
        let blockSubtype = "";
```

2023-08-13 08:54 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/script.js
> +    var cssPrototype = 'prototype';
```suggestion
    const cssPreview = 'preview';
    const cssPrototype = 'prototype';
```

2023-08-13 08:54 UTC, strizh78 commented on interface/textEditor/textViewMode.h
> +Q_DECLARE_METATYPE(TextViewMode);
```suggestion
};

Q_DECLARE_METATYPE(TextViewMode);
```

2023-08-16 10:03 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    } else {
оно сразу в предположении что тут обрабатываются много видов блоков
явно делим одно от другого

2023-08-16 10:04 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +        btn.textContent = blockData["dataText"] ? blockData["dataText"] : "Выберите данные";
это строка

2023-08-16 10:05 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +
не, мне он нравится

2023-08-16 10:07 UTC, strizh78 commented on interface/file/filesTabbedEditor/filesTabbedEditor.cpp
> +    return File();
опшнл медленнее в разы + его надо обрабатывать

создавать файл ничего не стоит
мы ж не данные в него грузим, по сути там только код и тот нулевой

2023-08-16 10:08 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    const blockTag = (blockType === "sub_block") ? "span" : "div";
следующим ревью лучше
там как раз запланировано вот эту твою константную магию сделать + унифицировать общение бека с фронтом
чтобы бек не парсил html, а получал-отдавал блоки всегда

2023-08-16 10:09 UTC, strizh78 commented on interface/textEditor/textEditor/iframe/blocksScript.js
> +    if (blockData.blockSubtype === "link") {
https://github.com/rust379/MApp/pull/305#discussion_r1295676739

2023-08-26 07:07 UTC, rust379 approved these changes

2023-08-26 07:07 UTC, rust379 commented on interface/textEditor/textEditor.cpp
> -    case TextViewMode::PROTOTYPE:
У нас вроде case не идет с доп отступом

2023-08-26 09:29 UTC, strizh78 commented on interface/textEditor/textEditor.cpp
> -    case TextViewMode::PROTOTYPE:
сделала аналогично свитчу, который на 10 строк выше

<img width="479" alt="Снимок экрана 2023-08-26 в 12 29 25" src="https://github.com/rust379/MApp/assets/38105548/6e11f963-4f00-4457-80ab-9b9801a656b0">

2023-08-26 09:54 UTC, merged