Timetable update
rust379/MApp pull request #307
Opened 2023-07-30 09:44 UTC by strizh78

дизайна тут нет (и скринов не будет)

делаем обновление расписания не по таймеру, а по изменениям
если добавили/удалили/перенесли приём - то расписание обновится под эти изменения, не надо ждать минуту или перезапускать приложение

2023-08-26 07:35 UTC, rust379 requested changes

2023-08-26 07:35 UTC, rust379 commented on interface/timetable/dailyTimetable/dailyTimetable.cpp
> +        Observer::instance().subscribe(this, object, DB_ACTIONS::UPDATE);
Можно воспользоваться https://github.com/rust379/MApp/blob/6bfbed3e581a782c33f7e5dccfeba11257231ad7/observer/observer.h#L32

2023-08-26 07:35 UTC, rust379 commented on interface/timetable/dailyTimetable/widgets/eventButtons/dailyTimetableEvent.h
> +    }
cpp?

2023-08-29 06:06 UTC, strizh78 commented on interface/timetable/dailyTimetable/dailyTimetable.cpp
> +        Observer::instance().subscribe(this, object, DB_ACTIONS::UPDATE);
```suggestion
        Observer::instance().subscribe(this, object, { DB_ACTIONS::ADD, DB_ACTIONS::UPDATE });
```

2023-09-23 13:04 UTC, strizh78 commented on interface/timetable/timetableForm.cpp
> +    QueryClauses findByDateAndNotDeleted(const QDate& date) {
```suggestion
QueryClauses findByDateAndNotDeleted(const QDate& date) {
```

2023-09-23 17:51 UTC, strizh78 commented on interface/timetable/dailyTimetable/widgets/listWidgets/dailyTimetableSortedEventsList.cpp
> +//    insertPosition = (insertPosition == eventsLay_->count()) ? insertPosition - 1 : insertPosition;
```suggestion
```

2023-09-27 09:30 UTC, rust379 approved these changes

2023-09-27 09:30 UTC, rust379 commented on interface/timetable/dailyTimetable/widgets/listWidgets/dailyTimetableSortedEventsList.cpp
> +        if (item && newEventWidget->getEvent() < item->getEvent()) {
Мне тут не очень нравится использование "<", может сделать метод 'earlier'?

2023-09-27 14:48 UTC, strizh78 commented on interface/timetable/dailyTimetable/widgets/listWidgets/dailyTimetableSortedEventsList.cpp
> +        if (item && newEventWidget->getEvent() < item->getEvent()) {
ок

2023-09-27 14:48 UTC, merged