Prefix tree for ICD
rust379/MApp pull request #309
Opened 2023-07-30 21:47 UTC by rust379

Добавлено префиксное дерево с поддержкой хранения некоторого значения в вершинах. Для значения необходима реализация std::hash. Лучше всего использовать указатели. 
Т.е. работа с деревом следующая. Где-то хранятся данные, для которых определено представление (строка их описывающая), в префиксное дерево передаются эти представления и ссылки на данные.

Добавлены классы для работы с МКБ

2023-08-14 13:32 UTC, strizh78 requested changes

2023-08-14 13:32 UTC, strizh78 commented on ICD/ICD.cpp
> +    return QString("%1 - %2").arg(code, name);
а зачем этот метод?
если чтобы возвращать строки, то не лучше возвращать отдельно код и данные?
они же разными шрифтами могут быть

2023-08-14 13:32 UTC, strizh78 commented on ICD/ICD.h
> +public:
а почему public?

2023-08-14 13:32 UTC, strizh78 commented on database/prod/databaseSQL.cpp
> +    std::vector<std::pair<QString, QString>> staticDataFiles = {
а тут не лучше просто map<string, string> сделать?
меньше буковок будет)

2023-08-14 13:32 UTC, strizh78 commented on database/prod/databaseSQL.cpp
> +        }
```suggestion
        if (query.exec(str)) {
            LOG_INFO("DATABASE") << QString("Data inserted successfully") << Qt::endl;
        } else {
            LOG_ERROR("DATABASE") << QString("Fail to create tables") << Qt::endl;
            LOG_ERROR("DATABASE") << query.lastError().databaseText() << Qt::endl;
            LOG_ERROR("DATABASE") << query.lastError().driverText() << Qt::endl;
        }
```

2023-08-14 13:32 UTC, strizh78 commented on database/prod/databaseSQL.cpp
> +    if (!queries.open(QIODevice::ReadOnly)){
```suggestion
    if (!queries.open(QIODevice::ReadOnly)) {
```

2023-08-14 13:32 UTC, strizh78 commented on database/prod/databaseSQL.cpp
> +    while(!queries.atEnd()) {
```suggestion
    while (!queries.atEnd()) {
```

2023-08-14 13:32 UTC, strizh78 commented on database/prod/databaseSQL.cpp
> +    return query.value(0) != 0;
а что делает query.first()?
и не может ли тут вернуться совсем ничего, если таблица пустая (не будет ли выхода за границы)?

2023-08-14 13:32 UTC, strizh78 commented on database/prod/databaseSQL.h
> +    bool isEmpty(const QString& table);
const не получится сделать?

2023-08-14 13:32 UTC, strizh78 commented on database/prod/databaseSQL.cpp
> +        if (query.exec(str)) {
сииильно на будущее:
надо бы понять где в релизе куте лежат файлы из qrc (и как)
а то если их можно поменять с пользовательской стороны, то надо добавлять какую-то магию, чтобы чел не мог запустить свои запросы и достать данные

2023-08-14 13:32 UTC, strizh78 commented on database/prod/tables/ICDTable.h
> +    const ICDFields* fields;
не к этому ревью, а в целом:

может тут и указатель константным сделать?
а то он публичный
то есть я могу его где-то взять и делитнуть
а тут потом деструктор упадет, ибо освобождать уже нечего

2023-08-14 13:32 UTC, strizh78 commented on structures/trie/trie.cpp
> +    root_ = new TrieNode(0, 0, 1);
я бы написала в комментарии что это за цифры
а то без чтения кода это магия)

например 
root_ = new TrieNode(/*urr*/ 0, /*murr*/ 0, /*kus'*/ 1);

2023-08-14 13:32 UTC, strizh78 commented on structures/trie/trie.cpp
> +    root_ = new TrieNode(0, 0, 1);
root_ создали, но не удалили [или я не нашла) ]
может тут тогда unique сделать или деструктор добавить?

2023-08-14 13:32 UTC, strizh78 commented on structures/trieWithNodeData/trieWithNodeData.h
> +    TrieWithNodeData(const std::vector<std::pair<QString, NodeData>>& data)
а что тут такое data?
это не мап ключа в значение?
// не стоит его мапом сделать?

2023-08-14 13:32 UTC, strizh78 commented on structures/trieWithNodeData/trieWithNodeData.h
> +        for (const auto& [sentense, node] : data) {
(можно забить)

меня немного смущает, что мы тут завязываемся на то как должны лежать данные в неком темплейтном классе NodeData и нигде это не проверяем

тут не лучше было бы перенести сделать NodeData конкретной структурой (может темплейтной), чтобы node/sentence[или сразу слова? мало ли какие делиметры бывают] было сразу "в контракте"

или вынести ее во вне, чтобы сюда явно передавались слова и другие нужные данные?

2023-08-23 14:48 UTC, rust379 commented on ICD/ICD.cpp
> +    return QString("%1 - %2").arg(code, name);
Убрал, добавил методы для каждого поля отдельно

2023-08-23 14:53 UTC, rust379 commented on database/prod/databaseSQL.cpp
> +    std::vector<std::pair<QString, QString>> staticDataFiles = {
Кажется вектор больше по смыслу подходит, да и функционал и фишки мапы тут не нужны

2023-08-23 14:55 UTC, rust379 commented on database/prod/databaseSQL.cpp
> +    return query.value(0) != 0;
query.first() - начинает указывать на первый результат (первую строку), 
результат будет не пустой, если таблица пустая, то COUNT(*) - выдаст 0

2023-08-23 14:55 UTC, rust379 commented on database/prod/databaseSQL.h
> +    bool isEmpty(const QString& table);
сделал

2023-08-23 15:00 UTC, rust379 commented on structures/trieWithNodeData/trieWithNodeData.h
> +    TrieWithNodeData(const std::vector<std::pair<QString, NodeData>>& data)
data - Список каких-то строк и связанных с ними данных, например Название диагноза + сам диагноз
Допускаются одинаковые строки

Данные сюда лучше передавать по ссылке (внутри есть всякие копирования и перемещения)

2023-08-24 06:54 UTC, strizh78 commented on database/prod/databaseSQL.cpp
> +    if (!queries.open(QIODevice::ReadOnly)){
пинг)

2023-08-24 06:55 UTC, strizh78 commented on database/prod/databaseSQL.cpp
> +    return query.value(0) != 0;
first - оч странный выбор названия, конечно)

2023-08-24 06:58 UTC, strizh78 commented on structures/trieWithNodeData/trieWithNodeData.h
> +        for (const auto& [sentense, node] : data) {
а, окей, ошиблась
имела ввиду sentence

мне, если я захочу юзать эту штуку, надо будет что-то знать про то как должна выглядеть эта строка?
или пихаю свою любуи и радуюсь?

2023-08-24 08:10 UTC, rust379 commented on structures/trieWithNodeData/trieWithNodeData.h
> +        for (const auto& [sentense, node] : data) {
Нет, абсолютно любая строка, но ее деление, для поиска по префиксу слов, происходит по пробелу
Если в какой-то момент нужно будет использовать другой разделитель - можно будет доработать без особых проблем

2023-08-24 08:13 UTC, strizh78 commented on structures/trieWithNodeData/trieWithNodeData.h
> +        for (const auto& [sentense, node] : data) {
слушай, а ты не помнишь
фор запомнит список и будет по нему итерироваться
или будет каждый шаг вычислять список заново?

я про этот фор
for (const QString& word : sentense.split(' ')) {

2023-08-24 08:13 UTC, rust379 commented on database/prod/tables/ICDTable.h
> +    const ICDFields* fields;
Давай задачку заведем на это, потом сразу везде проставим

2023-08-24 08:19 UTC, rust379 commented on structures/trieWithNodeData/trieWithNodeData.h
> +        for (const auto& [sentense, node] : data) {
Не знаю, давай потестирую
Если вычисляется каждый раз - вынесу это в переменную

2023-08-24 08:20 UTC, strizh78 commented on structures/trieWithNodeData/trieWithNodeData.h
> +        for (const auto& [sentense, node] : data) {
окей)
в целом то не должен перевычислять по идее, но было бы интересно узнать точно

2023-08-24 08:43 UTC, rust379 commented on structures/trieWithNodeData/trieWithNodeData.h
> +        for (const auto& [sentense, node] : data) {
видимо все же вычисляется 1 раз, как и надо
<img width="518" alt="image" src="https://github.com/rust379/MApp/assets/38105637/d6dae653-a404-42b0-92da-0483b4f37b7c">

2023-08-24 20:35 UTC, rust379 commented on database/prod/tables/ICDTable.h
> +    const ICDFields* fields;
https://tracker.yandex.ru/MAPP-97

2023-08-26 06:52 UTC, strizh78 approved these changes

2023-08-26 07:44 UTC, merged