Add event class; fix small issues with appointment
rust379/MApp pull request #50
Opened 2021-07-20 06:36 UTC by strizh78

2021-07-20 09:36 UTC, strizh78 commented
<img width="462" alt="Снимок экрана 2021-07-20 в 12 36 16" src="https://user-images.githubusercontent.com/38105548/126299411-68f2800c-e687-4d5c-aee2-a0d6b50bf14c.png">

<img width="840" alt="Снимок экрана 2021-07-20 в 12 36 31" src="https://user-images.githubusercontent.com/38105548/126299468-730d0728-1343-4331-bb22-985fe558e21a.png">

<img width="435" alt="Снимок экрана 2021-07-20 в 12 36 42" src="https://user-images.githubusercontent.com/38105548/126299499-c6f1bc58-37e4-498b-abde-d94c9a5a5072.png">

2021-07-22 05:52 UTC, rust379 requested changes

2021-07-22 05:52 UTC, rust379 commented on timetable/event.h
> +    QString comment = "";
Почему для комментария задаешь ="", а для заголовка - нет?
и оно вообще нужно это начальное значение?

2021-07-22 05:52 UTC, rust379 commented on timetable/timetableUtils.cpp
> +bool isTimeSlotsIntersect(QDateTime b1, QDateTime e1, QDateTime b2, QDateTime e2) {
вот вроде b и e понятно что такое, но хотелось бы более подробные названия
тип startTime beginTime или что-то такое

2021-07-22 05:52 UTC, rust379 commented on timetable/timetableUtils.cpp
> +    }
много ифов и они очень похожи
кажется, тут проще сделать так: берем как первый отрезок тот, у которого меньше левая граница,
проверяем что его правая - левее левой второго

2021-07-22 05:52 UTC, rust379 commented on timetable/timetableUtils.cpp
> +    }
Еще как предложение - можно передавать в функцию 2 пары, тогда должно получиться что-то подобное
return min(pair1, pair2).second < max(pair1, pair2).first

2021-07-22 05:52 UTC, rust379 commented on timetable/timetableUtils.h
> +int seconds(const QTime& time);
не сразу понятно, что делает функция, 
кажется лучше "timeInSeconds"

2021-07-22 05:52 UTC, rust379 commented on timetable/timetableUtils.h
> +int seconds(const QTime& time);
не сразу понятно, что делает функция, 
кажется лучше "timeInSeconds"

2021-07-22 05:52 UTC, rust379 commented on timetable/timetableUtils.h
> +    db->appointments(a);
опять названия из 1 буквы, не очень хорошо

2021-07-22 05:52 UTC, rust379 commented on timetable/timetableUtils.h
> +        if (x != obj &&
и тут,
а почему x - вообще непонятно

2021-07-22 05:52 UTC, rust379 commented on appointment/appointment.cpp
> +}
Подскажи пожалуйста,где это используется, не увидел

2021-07-22 05:52 UTC, rust379 commented on interface/timetable/event/eventForm.cpp
> +                     OpenMode mode,
одна буква в имени переменной, не надо так

2021-07-22 05:52 UTC, rust379 commented on interface/timetable/event/eventForm.cpp
> +    , event_(e.value_or(Event("", QDateTime(QDate::currentDate(), QTime::currentTime()), QTime(1, 0))))
а вот эти значения 
("", QDateTime(QDate::currentDate(), QTime::currentTime()), QTime(1, 0))
нельзя закинуть просто в пустой конструктор Event() ?

2021-07-22 05:58 UTC, strizh78 commented on timetable/timetableUtils.cpp
> +bool isTimeSlotsIntersect(QDateTime b1, QDateTime e1, QDateTime b2, QDateTime e2) {
Если понятно, то зачем усложнять?
Особенно учитывая что она внутренняя и наружу не используется 

Объяснишь - заменю
Пока выглядит как лишнее ненужное усложнение читаемости

2021-07-22 06:04 UTC, strizh78 commented on timetable/timetableUtils.h
> +int seconds(const QTime& time);
Согласна на toSeconds
По входному параметру понятно что это время

2021-07-22 06:09 UTC, strizh78 commented on timetable/timetableUtils.h
> +    db->appointments(a);
оно используются только в 2х строчках ниже же...

2021-07-22 10:01 UTC, strizh78 commented on appointment/appointment.cpp
> +}
проверю, казалось что будет в следующем ревью надо, но сейчас уже не уверена

2021-07-22 10:02 UTC, strizh78 commented on interface/timetable/event/eventForm.cpp
> +    , event_(e.value_or(Event("", QDateTime(QDate::currentDate(), QTime::currentTime()), QTime(1, 0))))
меня смущает QTime::currentTime()
не уверена что это будет ожидаемым поведением


но в целом согласна - сделаю

2021-07-22 10:03 UTC, strizh78 commented on timetable/timetableUtils.h
> +        if (x != obj &&
![IMAGE 2021-07-22 13:03:13](https://user-images.githubusercontent.com/38105548/126622357-4216afcc-04d4-4991-bac0-fe3fefb7a0cf.jpg)

2021-07-22 10:03 UTC, strizh78 commented on timetable/timetableUtils.h
> +    db->appointments(a);
![IMAGE 2021-07-22 13:03:28](https://user-images.githubusercontent.com/38105548/126622395-a83c8b68-af5c-4ec6-97c2-23a07c00d789.jpg)

2021-07-22 10:04 UTC, strizh78 commented on timetable/timetableUtils.cpp
> +bool isTimeSlotsIntersect(QDateTime b1, QDateTime e1, QDateTime b2, QDateTime e2) {
согласна на begin и end
Time выглядит переусложнением, учитывая что в названии функции оно фигурирует

2021-07-22 10:04 UTC, strizh78 commented on timetable/event.h
> +    QString comment = "";
убедил, косякнула
поправлю

2021-08-03 13:56 UTC, strizh78 commented on timetable/event.h
> +    QString comment = "";
```suggestion
    QString comment;
```

2021-08-03 13:58 UTC, strizh78 commented on interface/timetable/event/eventForm.cpp
> +    , event_(e.value_or(Event("", QDateTime(QDate::currentDate(), QTime::currentTime()), QTime(1, 0))))
нет, всё же мне кажется неочевидным делать конструктор с текущим временем по умолчанию
давай ещё обсудим

2021-08-03 13:58 UTC, strizh78 commented on appointment/appointment.cpp
> +}
```suggestion
```

2021-08-03 13:59 UTC, strizh78 commented on appointment/appointment.h
> +
```suggestion
```

2021-08-06 07:51 UTC, rust379 requested changes

2021-08-06 07:51 UTC, rust379 commented on timetable/event.h
> +    Event(QString text, QDateTime dateTime, QTime time);
Давай переименуем переменные, не понятно при прочтении, за что каждое поле отвечает
В полях класса как раз понятные имена

2021-08-06 07:51 UTC, rust379 commented on timetable/event.h
> +    QString comment;
А почему оставляем паблик полями?

2021-08-06 07:51 UTC, rust379 commented on timetable/timetableUtils.h
> +bool isTimeSlotAvailable(DatabaseInterface* db, const T& obj, QDateTime dateTime, QTime duration) {
Сюда нельзя передавать только db + obj, а уже внутри функции доставать время из obj ?

2021-08-06 07:51 UTC, rust379 commented on timetable/timetableUtils.h
> +#include <QColor>
А этот модуль где используется ?

2021-08-10 13:49 UTC, strizh78 commented on timetable/timetableUtils.h
> +bool isTimeSlotAvailable(DatabaseInterface* db, const T& obj, QDateTime dateTime, QTime duration) {
давай пока так оставим
следующим ревью попробую добавить доп метод, который будет позволять так делать
сейчас нельзя, потому что у нас в разных местах приёма и эвента лежит информация про время

2021-08-10 13:49 UTC, strizh78 commented on timetable/event.h
> +    QString comment;
решили что норм, всё делать пабликами будем

2021-08-10 13:51 UTC, strizh78 commented on timetable/event.cpp
> +    , duration(time)
```suggestion
Event::Event(QString title, QDateTime dateTime, QTime duration)
    : title(title)
    , dateTime(dateTime)
    , duration(duration)
```

2021-08-10 13:51 UTC, strizh78 commented on timetable/event.h
> +    Event(QString text, QDateTime dateTime, QTime time);
```suggestion
    Event(QString title, QDateTime dateTime, QTime duration);
```

2021-08-10 13:51 UTC, strizh78 commented on timetable/timetableUtils.h
> +#include <QColor>
```suggestion
```

2021-08-10 14:54 UTC, rust379 approved these changes

2021-08-10 18:17 UTC, merged