Files
rust379/MApp pull request #51
Opened 2021-07-23 04:13 UTC by rust379

Тут не все доделано, но уже есть что показать. 
1 - Нет редактирования файлов
2 - Нет пока привязки файлов к приему/пациенту

2021-07-23 07:35 UTC, strizh78 requested changes

2021-07-23 07:35 UTC, strizh78 commented on contrib/clickableWidget/clickableWidget.cpp
> +#include "clickableWidget.h"
А что это за файлы? Почему они в контрибе? Выглядит будто их ты писал

2021-07-23 07:35 UTC, strizh78 commented on database/databasetest.cpp
> -
Эта строчка была специально

Она показывает что прошлые штуки зависят только сами от своих данных, а приём зависит от других

То есть нельзя, например, переставить инит пациента и приема

2021-07-23 07:35 UTC, strizh78 commented on database/databasetest.cpp
> +    const QString FILE_TEST_DIR = "C:/Qt/Projects/MApp/testFiles";
Ой ой ой 
Давай уберём такое и придумаем как сделать путь не абсолютным

У меня же оно не заработает так:(

Что будет если только директорию указать, а не полный путь? Где он будет создавать?

2021-07-23 07:35 UTC, strizh78 commented on files/fileInterface.h
> +class FileInterface : public MAppBaseObj
А почему оно так называется? Это же не интерфейс

2021-07-23 07:35 UTC, strizh78 commented on files/fileInterface.h
> +#include "vector"
Другие кавычки у внешних библиотек

2021-07-23 07:35 UTC, strizh78 commented on files/fileInterface.h
> +{
Скобка:)

2021-07-23 07:35 UTC, strizh78 commented on files/fileInterface.cpp
> +FileInterface::FileInterface(QString path) {
Не вижу причины не передавать по константной ссылке путь
Что-то ломается от этого?

2021-07-23 07:35 UTC, strizh78 commented on files/fileInterface.cpp
> +#include "QFile"
Другие кавычки у внешних инклудов

2021-07-23 07:35 UTC, strizh78 commented on files/fileInterface.cpp
> +    QFileInfo info(file);
Может сначала проверять существует ли файл, а потом уже получать info?

2021-07-23 07:35 UTC, strizh78 commented on files/fileInterface.cpp
> +    for (auto ext : SUPPORTED_EXTENSIONS)
ссылка потерялась?
&

2021-07-23 07:35 UTC, strizh78 commented on files/fileInterface.h
> +const std::vector<QString> SUPPORTED_EXTENSIONS = {"Изображения (*.png *.jpg)",
Давай постараемся убрать это из хедера, все же сейчас это глобальная переменная, которая будет во всех файлах
Такое не очень хорошо, кажется

2021-07-23 07:35 UTC, strizh78 commented on interface/files/fileForm.cpp
> +#include <QDebug>
Не думаю что он нужен

2021-07-23 07:35 UTC, strizh78 commented on interface/files/fileForm.h
> +{
Скобка :)

2021-07-23 07:35 UTC, strizh78 commented on interface/files/fileForm.h
> +              FileInterface file,
Давай подумаем почему нельзя передавать по ссылке
И если можно, то так и сделаем)

2021-07-23 07:35 UTC, strizh78 commented on interface/files/fileForm.h
> +;
Внезапная точка с запятой)

2021-07-23 07:35 UTC, strizh78 commented on interface/files/fileForm.h
> +#include <optional>
Напомни, зачем опшнл? Там умные указатели лежат?

2021-07-23 07:35 UTC, strizh78 commented on interface/files/fileForm.cpp
> +    ui->lastUpdTimeValLablel->setText(file_.lastEditTime().toString());
Label в конце с опечаткой

2021-07-23 07:35 UTC, strizh78 commented on interface/files/fileForm.cpp
> +    ui->extensionValLabel->setText(file_.extension());
А в целом зачем тут Val в названии? Там есть такие же без Val?

Может тогда просто ...Value?

2021-07-23 07:35 UTC, strizh78 commented on interface/files/fileForm.cpp
> +    ui->uploadTimeValLabel->setText(file_.uploadTime().toString());
А мы не хотим тут формат представления даты свой какой-то задать?

[это не требование к исправлению, просто напоминаю о такой возможности]

2021-07-23 07:35 UTC, strizh78 commented on interface/files/fileForm.cpp
> +
Очень полезная функция
А зачем она?)

2021-07-23 07:35 UTC, strizh78 commented on interface/files/fileForm.cpp
> +        emit fileEditSignal(file_);
Я запуталась:(

Я не вижу в этом коде никаких функций, которые бы как-то изменяли переменную file_
(Конструктор не считается)

Тогда зачем? Мы разве могли что-то изменить?

isModified тоже не меняет своё значение
Чего я не понимаю?

2021-07-23 07:35 UTC, strizh78 commented on interface/files/filesListForm.h
> +{
Скобка:)

2021-07-23 07:35 UTC, strizh78 commented on interface/files/filesListForm.h
> +
Лишняя пустая строка

2021-07-23 07:35 UTC, strizh78 commented on interface/files/filesListForm.cpp
> +    for (FileInterface file : fileList) {
const ..&

2021-07-23 07:35 UTC, strizh78 commented on interface/files/filesListForm.cpp
> +#include "QDir"
Опять инклуды не в тех кавычках

2021-07-23 07:35 UTC, strizh78 commented on interface/files/filesListForm.cpp
> +    ui->fileTable->editData(file, CreateRows::createFileRow(file));
Я глупенькая и не вижу где эта функция используется :(

2021-07-23 07:56 UTC, rust379 commented on database/databasetest.cpp
> +    const QString FILE_TEST_DIR = "C:/Qt/Projects/MApp/testFiles";
Можно попробовать получить директорию с проектом и уже от нее отталкиваться

2021-07-23 07:57 UTC, rust379 commented on database/databasetest.cpp
> -
Да, ок
случайно удалилась)

2021-07-23 07:58 UTC, rust379 commented on files/fileInterface.h
> +class FileInterface : public MAppBaseObj
Изначально задумывался как интерфейс, потом как-то ушло от этого, а имя поменять забыл, ок

2021-07-23 07:59 UTC, rust379 commented on files/fileInterface.cpp
> +FileInterface::FileInterface(QString path) {
Нет, просто забыл

2021-07-23 08:15 UTC, strizh78 commented on database/databasetest.cpp
> +    const QString FILE_TEST_DIR = "C:/Qt/Projects/MApp/testFiles";
Мне кажется там автоматом рабочая директория - директория проекта или что-то такое


И точно есть метод cd у QDir
Мне кажется надо узнать какая папка там по умолчанию
И если что попробовать как-то с помощью встроенных методов cd и mkdir сделать папку для файлов и перейти в нее

[и поставить какой-нибудь временный вывод бы, чтобы знать что за папка создалась]

2021-07-24 08:59 UTC, rust379 commented on contrib/clickableWidget/clickableWidget.cpp
> +#include "clickableWidget.h"
а куда стоит их положить? 
вот такие вспомогательные вещи, basic forms ?

2021-07-24 09:02 UTC, rust379 commented on database/databasetest.cpp
> +    const QString FILE_TEST_DIR = "C:/Qt/Projects/MApp/testFiles";
Я пока константу там объявил, потом под свое расположение ее поправишь
*Объявил ее прям в этой функции,  может стоит ее вынести в другое место

2021-07-24 09:08 UTC, rust379 commented on files/fileInterface.h
> +const std::vector<QString> SUPPORTED_EXTENSIONS = {"Изображения (*.png *.jpg)",
Почему? 
подключил файлы - получаешь поддерживаемые форматы

2021-07-24 09:11 UTC, rust379 commented on interface/files/fileForm.cpp
> +    ui->uploadTimeValLabel->setText(file_.uploadTime().toString());
Думаю, это можно будет переделать на этапе стиля

2021-07-24 09:12 UTC, rust379 commented on interface/files/fileForm.cpp
> +
Я предполагал по клику на иконку открывать файл,
хотя все больше мне не кажется это интуитивно понятным
@ittaidrew что скажешь ?

2021-07-24 09:13 UTC, rust379 commented on interface/files/fileForm.cpp
> +        emit fileEditSignal(file_);
Это пока просто одно из множетсва сырых мест,
как менять файл я еще не придумал) пока просто поставил такую затычку

2021-07-24 09:17 UTC, rust379 commented on interface/files/filesListForm.cpp
> +    ui->fileTable->editData(file, CreateRows::createFileRow(file));
Вызывается после редактирования файла через форму файла

2021-07-24 09:33 UTC, strizh78 commented on files/fileInterface.h
> +const std::vector<QString> SUPPORTED_EXTENSIONS = {"Изображения (*.png *.jpg)",
1. А зачем доступ к этому массиву из других файлов? Почему не хватит функции getSupp...() ?

2. Потому что если где-то ещё появится вектор с таким названием - будет косяк
Форматы бывают не только у файлов
Ещё у статистики могут быть, например

2021-07-24 09:33 UTC, strizh78 commented on interface/files/fileForm.cpp
> +    ui->uploadTimeValLabel->setText(file_.uploadTime().toString());
Что такое этап стиля?)

2021-07-24 09:36 UTC, strizh78 commented on interface/files/fileForm.cpp
> +
Я не Андрей, конечно)

Но

А давай сделаем как в других системах?
При двойном клике/открытии открывается сам файл

А если кликнуть пкм, то там можно открыть свойства, где можно посмотреть всю эту инфу/переименовать

Все же открыть содержимое - намного более популярная операция, чем уточнить время добавления [или я нерепрезентативна и у врачей все иначе?) ]

2021-07-24 09:37 UTC, strizh78 commented on interface/files/filesListForm.cpp
> +    ui->fileTable->editData(file, CreateRows::createFileRow(file));
Ок, подзабыла эту систему всю )

2021-07-24 09:40 UTC, strizh78 commented on contrib/clickableWidget/clickableWidget.cpp
> +#include "clickableWidget.h"
Не знаю
Давай заведём папку style, например?

contrib это по стандарту папка, в котором лежит чужой код
Например всякие библиотеки сторонние, фреймворки т д

Класть туда собственный код кажется странным

2021-07-25 11:57 UTC, rust379 commented on interface/files/fileForm.cpp
> +    ui->uploadTimeValLabel->setText(file_.uploadTime().toString());
когда дизайнить будем

2021-07-25 12:07 UTC, rust379 commented on contrib/clickableWidget/clickableWidget.cpp
> +#include "clickableWidget.h"
Да, ок,
но style больше как-то с css файлами ассоциируется, 
interfaceElements ? или что-то со словом suppot/suppotring

2021-07-25 12:31 UTC, strizh78 commented on contrib/clickableWidget/clickableWidget.cpp
> +#include "clickableWidget.h"
у меня вообще нет такой ассоциации, как и таких файлов в нашем проекте

support мне не очень нравится

как тебе 
interface/elements или
interface/widgets
?

2021-07-25 12:31 UTC, strizh78 commented on interface/files/fileForm.cpp
> +    ui->uploadTimeValLabel->setText(file_.uploadTime().toString());
хорошо)

2021-07-25 12:35 UTC, rust379 commented on contrib/clickableWidget/clickableWidget.cpp
> +#include "clickableWidget.h"
Давай interface/elements
а еще я думаю выпилить этот класс, а добавлять его когда в этом будет необходимость.

2021-07-25 15:24 UTC, rust379 commented on interface/files/fileForm.cpp
> +
Погоди, такое поведение будет в форме списка,
а тут - форма самого файла, я думал около всякой информации выводить какую-то иконку, по нажати. на которую - открывается сам файл.
но сейчас, больше склоняюсь к замене этого всего на простую кнопку, ибо не факт, что в итоговом дизайне где-то понадобится кликабельный виджет

2021-07-26 17:07 UTC, strizh78 commented on database/databasetest.cpp
> +std::vector<File> DatabaseTest::fileList_ = {};
```suggestion
std::vector<File> DatabaseTest::filesList_ = {};
```

2021-07-26 17:41 UTC, strizh78 commented on database/databasetest.cpp
> +std::vector<File> DatabaseTest::fileList_ = {};
может filesList?
по аналогии с остальными

2021-07-26 17:41 UTC, strizh78 commented on files/file.cpp
> +    if (!file.exists())
я не знаю про остальные формы (как это там сделано у тебя будет)

но давай там тоже как-то проверять, что файл существует? чтобы можно было пользователю написать ошибку
типа алярм! файла нет

иначе сейчас не ясно что произойдет, если файла не будет
просто ничего?

2021-07-26 17:41 UTC, strizh78 commented on files/file.cpp
> +}
напомни, мы разве не выпилили все геттеры?

2021-07-26 17:41 UTC, strizh78 commented on interface/files/filesListForm.cpp
> +                                                    toString(getSupportedExtensions(), ";; "));
а расскажешь что за строчечка ";; "?

2021-07-26 20:04 UTC, rust379 commented on files/file.cpp
> +    if (!file.exists())
В данной версии файл будет всегда, ибо мы выбираем его через диалоговое окно,
но сейчас подумал, может быть такое что у нас нет доступа чтения, и тогда хорошо бы как-то это отобразить или просто зафиксировать.
А вообще да, переработаю конструктор

2021-07-26 20:05 UTC, rust379 commented on files/file.cpp
> +}
Нет,
сеттеры же выпиливали

2021-07-26 20:07 UTC, rust379 commented on interface/files/filesListForm.cpp
> +                                                    toString(getSupportedExtensions(), ";; "));
Ей разделяются форматы для диалогового окна выбора файла
https://doc.qt.io/qt-5/qfiledialog.html#getOpenFileName

2021-07-26 20:08 UTC, rust379 commented on database/databasetest.cpp
> +std::vector<File> DatabaseTest::fileList_ = {};
Что ты имеешь в виду?

2021-07-26 20:32 UTC, strizh78 commented on database/databasetest.cpp
> +std::vector<File> DatabaseTest::fileList_ = {};
Все остальные названия списков строятся по принципу <множественное число объекта>+List

patientsList
medicinesList
И т д


А fileList - файл в единственном числе получается

2021-07-26 20:32 UTC, strizh78 commented on files/file.cpp
> +    if (!file.exists())
Если условие всегда верно, то давай уберём его)

2021-07-26 20:33 UTC, strizh78 commented on files/file.cpp
> +}
Обидно)

2021-07-26 20:33 UTC, strizh78 commented on interface/files/filesListForm.cpp
> +                                                    toString(getSupportedExtensions(), ";; "));
Поняла, спасибо

2021-07-27 04:12 UTC, rust379 commented on database/databasetest.cpp
> +std::vector<File> DatabaseTest::fileList_ = {};
А, ок
Я заметил эту ошибку в названиях классов, там поменял, а тут забыл,
Исправлю

2021-07-29 18:43 UTC, strizh78 requested changes

2021-07-29 18:43 UTC, strizh78 commented on database/databaseinterface.h
> +#include "files/file.h"
а не лучше #include "file/file.h" (без множественного числа), по аналогии с остальными?

2021-07-29 18:43 UTC, strizh78 commented on database/databasetest.cpp
> +std::vector<int> DatabaseTest::fileParentAppointmentCode_ = {};
а расскажи, пожалуйста, зачем нам целых 3 вектора? звучит как будто всё это связано и должно быть в одном

2021-07-29 18:43 UTC, strizh78 commented on database/databasetest.cpp
> +    QFileInfoList list = FILE_TEST_DIR.entryInfoList();
давай подробнее назовём переменную?
мне по названию метода .entryInfoList(); не очень понятно что за список там лежит(

2021-07-29 18:43 UTC, strizh78 commented on database/databasetest.cpp
> +
пустая строка

2021-07-29 18:43 UTC, strizh78 commented on files/file.cpp
> +    lastEditTime_ = QDateTime::currentDateTime();
может единожды запросить текущие данные времени, а потом присвоить обеим переменным?
сейчас есть мелкий-мелкий риск, что в эту микросекунду сменится минута и эти данные не будут равны между собой

2021-07-29 18:43 UTC, strizh78 commented on files/file.cpp
> +QString File::name() const{
```suggestion
QString File::name() const {
```

2021-07-29 18:43 UTC, strizh78 commented on interface/files/fileDisplayForm.h
> +{
скобка

2021-07-29 18:43 UTC, strizh78 commented on interface/files/filesListForm.cpp
> +    File file = Files::add(database_, 1, this);
а зачем мы это в переменную локальную записываем? она ж умрёт при выходе из функции

2021-07-29 18:43 UTC, strizh78 commented on interface/files/filesListForm.cpp
> +    ui->fileTable->setHorizontalHeaderLabels({"Имя"});
может не "имя", а "документы", например?
хотя в целом пофиг. просто предложила

2021-07-29 18:43 UTC, strizh78 commented on interface/files/filesListForm.h
> +
случайно пустая строка ?

2021-07-29 18:43 UTC, strizh78 commented on interface/files/filesUtils.cpp
> +    return File();
а зочем?
он же пустой возвращается

2021-07-29 18:43 UTC, strizh78 commented on interface/files/filesUtils.cpp
> +              QWidget* parent) {
скобка

2021-07-29 18:46 UTC, strizh78 requested changes

2021-07-29 18:46 UTC, strizh78 commented on files/file.h
> +    QDateTime lastEditTime_;
не понимаю почему мы тут не храним ещё и содержимое файла(
давай тогда это не называть файлом, а называть настройками/свойствами/(крутится слово на языке, но вспомнить не могу)?


кажется тогда и в коде понятнее станет

2021-07-30 06:29 UTC, rust379 commented on database/databasetest.cpp
> +std::vector<int> DatabaseTest::fileParentAppointmentCode_ = {};
Потому что в классе файла нет информации про данные и связанный прием,
можно сделать внутри тестовой базы структуру fullFileInfo, в котором будут все 3 поля и делать 1 вектор
так лучше ?

2021-07-30 06:59 UTC, strizh78 commented on database/databasetest.cpp
> +std::vector<int> DatabaseTest::fileParentAppointmentCode_ = {};
Вот именно рассказ _почему_ их там нет и как это работает я и хотела)
Нет, править не нужно

2021-07-30 07:09 UTC, rust379 commented on database/databasetest.cpp
> +std::vector<int> DatabaseTest::fileParentAppointmentCode_ = {};
данных нет, потому что не хочу их там хранить,
кажется, удобнее подтягивать их по необходимости, а код связанного приема тоже по сути нигде не отображается,
не вижу смысла его тоже таскать за собой.
Хотя, есть один сценарий, на встрече можно будет обсудить

2021-07-30 07:20 UTC, rust379 commented on interface/files/filesListForm.cpp
> +    File file = Files::add(database_, 1, this);
Это я там забыл еще одну строчку дописать)

2021-07-30 07:21 UTC, rust379 commented on interface/files/filesListForm.cpp
> +    ui->fileTable->setHorizontalHeaderLabels({"Имя"});
В mappTable сделал настройку, что если не переданы имена заголовков - скрывать верхнюю плашку,
на скринах выше уже видно новое поведение

2021-07-30 07:24 UTC, rust379 commented on interface/files/filesUtils.cpp
> +    return File();
Я тут не придумал, что возвращать, если не удалось добавить файл

2021-07-30 07:26 UTC, rust379 commented on files/file.h
> +    QDateTime lastEditTime_;
Мне не нравится, что если хранить и содержимое - мы подгружаем много данных, которые нам вообще могут не пригодиться,
а так, подтягиваем данные из базы по необходимости

2021-07-30 07:27 UTC, rust379 commented on files/file.h
> +    QDateTime lastEditTime_;
Можно будет переименовать класс, но давай это тоже на стадию рефакторинга оставим

2021-07-30 08:53 UTC, strizh78 commented on files/file.h
> +    QDateTime lastEditTime_;
А почему не сейчас?

2021-07-30 08:59 UTC, rust379 commented on files/file.h
> +    QDateTime lastEditTime_;
Тогда жду предложений по наименованию)

2021-07-31 10:13 UTC, rust379 commented
Исправить:
Падает открытие приема без файлов
Падает открытие пациента без файлов
Добавить отображение картинок (.png)
Убрать кнопку добавления файла в форме пациента
Скорректировать спейсеры в формах.
Добавить линку к приему в форме файла, если открытие через форму пациента.
Скрыть Error text label в форме файла
Доработать форму меню, на случай скрытия шапки.
Скрыть шапку в корзине.

2021-08-03 14:37 UTC, strizh78 requested changes

2021-08-03 14:37 UTC, strizh78 commented on database/databasetest.cpp
> +    }
а я может глупенькая, но вроде договорились нагенерить файлы не в папке, а прямо тут в вектора сложить инфу нужную

как минимум сейчас не ясно: мне чтобы у себя начать работать с файлами, получается, надо создать папку и нагенерить туда файлов? звучит грустнее, чем если в коде будет явное заполнение векторов
+ можно будет у разным приёмам подцепить

тестовая база всё же для отладки всего приложения и хочется чтобы из коробки работало всё, а не "пойди-создай"

2021-08-03 14:37 UTC, strizh78 commented on interface/appointment/appointmentForm.ui
> +      <number>7</number>
внезапно

2021-08-03 14:37 UTC, strizh78 commented on interface/basicForms/mappTable.cpp
> +    setHorizontalHeaderLabels({});
хочу пояснение этого вызова функции? тип изначально полагаем то названий нет?

2021-08-03 14:37 UTC, strizh78 commented on interface/file/fileDisplayForm.cpp
> +FileDisplayForm::FileDisplayForm(const QString& fileName,
давай разберемся с неймингом, раз ты хочешь разделять характеристики/свойства файла и его содержимое?

я сейчас несколько минут пыталась понять что за форма такая странная, в которой нет названия файла и свойств, хотя она вроде как форма его отображения

давай тогда думать над явным разделением этих сущностей во всех названиях?
то есть: (названия условные)
есть fileProperties и fileContent
и тогда везде используются они --> слово file без этого уточнения встречаться не должно

(это не приказ, а предложение), но других способов не путаться в коде я не вижу
если у вас есть иные варианты, то давайте их в студию:)

2021-08-05 21:50 UTC, rust379 commented
> * [ ]  Нет реакции формы приема на сохранить/отмена
Странная тема, форма пациента нормально реагирует на solutionBox

2021-08-06 06:13 UTC, rust379 commented on interface/file/filesUtils.h
> +}
В целом, сейчас эти штуки вызываются только из формы списка файлов, можно fileUtils убрать.
Или оставить ?

2021-08-10 13:54 UTC, strizh78 commented on interface/file/filesUtils.h
> +}
а планируется где-то ещё их ипсользовать? в целом если сейчас не используются нигде кроме списка, то давай в список пока кинем

2021-08-10 13:55 UTC, strizh78 commented
ты же починишь локаль после сохранения файлов?

2021-08-10 17:26 UTC, strizh78 requested changes
урр

2021-08-11 05:29 UTC, rust379 commented on interface/file/filesListForm.cpp
> +}
Тут виджет преобразован к filesListForm и qt просит конструктор только по QWidget *parent
поэтому пришлось допом прокидывать БД

2021-08-11 06:18 UTC, strizh78 commented on interface/file/fileForm.cpp
> +    else if (ext == "png" || ext == "jpg") {
Сейчас ок
Но в рефакторинге давай что нибудь придумаем типа енама/мапа/вектора, чтобы не перечислять тут все типы?

Если будем поддержку вордообразных документов добавлять, то там же миллион форматов

2021-08-11 06:18 UTC, strizh78 commented on interface/file/fileForm.cpp
> +    switch (ui->tabWidget->currentIndex()) {
Отступы в этом свитче конечно смерть глазам)

Но ок, в рефакторинге заменим

2021-08-11 06:18 UTC, strizh78 commented on interface/file/filesListForm.cpp
> +}
А мы не решили избавиться от этой формы в пользу mapptable?

2021-08-11 10:53 UTC, strizh78 requested changes

2021-08-11 10:53 UTC, strizh78 commented on database/databasetest.cpp
> +        FullFileData(File("fileTXT_en", "txt"), QString("qwerty_123").toLocal8Bit(), parentCode),
давай хотя бы один файл сделаем с чуть более длинным текстом?  чтобы мы могли увидеть косяки при растяжении/переносе строк/ отсутствии скролла и видели, когда они исправляются

кажется что для тестовой базы будет полезно


можно не явный текст вбивать, а сделать какой-нибудь форик, который что-то +- рандомное нагенерирует (только не забыть пробелы и переводы строк туда повставлять)

2021-08-11 10:58 UTC, strizh78 commented on database/databasetest.cpp
> +        FullFileData(File("fileTXT_en", "txt"), QString("qwerty_123").toLocal8Bit(), parentCode),
и картинки можно тоже подобрать разные

точно нужны по одной png и jpg

но можно придумать, чтобы у нас была картинка огромная сама по себе (найти в интернетах условный рентген или сделать скрин целого экрана и загрузить в полном размере)
чтобы мы тут тоже видели нужно ли сделать скролл (не сейчас)/нужно ли зумить уметь/как мы вообще себя ведём с такими файлами

2021-08-12 06:05 UTC, rust379 commented on database/databasetest.cpp
> +        FullFileData(File("fileTXT_en", "txt"), QString("qwerty_123").toLocal8Bit(), parentCode),
Я длинный текст добавлю, png тоже
а jpg - давай добавлю вместе с изменением тестовых данных

2021-08-12 06:06 UTC, rust379 commented on interface/file/fileForm.cpp
> +    else if (ext == "png" || ext == "jpg") {
Да, уже есть мысли, как это организовать,  на рефакторинге сделаю

2021-08-12 06:08 UTC, rust379 commented on database/databaseinterface.h
> +#include "files/file.h"
Исправлено

2021-08-12 06:11 UTC, rust379 commented on database/databasetest.cpp
> +    QFileInfoList list = FILE_TEST_DIR.entryInfoList();
Исправлено

2021-08-12 06:14 UTC, rust379 commented on interface/file/fileDisplayForm.cpp
> +FileDisplayForm::FileDisplayForm(const QString& fileName,
Обговорили этот момент. Объединил формы

2021-08-12 06:15 UTC, strizh78 commented on database/databasetest.cpp
> +        FullFileData(File("fileTXT_en", "txt"), QString("qwerty_123").toLocal8Bit(), parentCode),
Ок)

2021-08-12 06:17 UTC, rust379 commented on interface/file/fileForm.cpp
> +        ui->pngDisplay->pixmap(Qt::ReturnByValue).save(&buffer, "PNG");
Добавил, чтоб с ним тоже все было хорошо

2021-08-12 06:17 UTC, rust379 commented on interface/file/fileForm.cpp
> +//            TODO: Show error. Add error log with custom text;
Добавил

2021-08-12 06:17 UTC, rust379 commented on interface/file/filesListForm.cpp
> +}
Не помню такого разговора

2021-08-12 06:18 UTC, rust379 commented on interface/file/filesListForm.h
> +    int parentAppointmentCode;
Исправил

2021-08-12 06:22 UTC, strizh78 commented on interface/file/filesListForm.cpp
> +}
Хорошо, давай поговорим заново)

Зачем нам дополнительная обертка над стандартной табличкой? В чем суть заведения этой формы?

2021-08-13 05:42 UTC, rust379 commented on interface/file/filesUtils.h
> +}
Перекинул

2021-08-13 05:43 UTC, rust379 commented on file/file.h
> +protected:
Исправил

2021-08-13 05:43 UTC, rust379 commented on interface/basicForms/mappTable.cpp
> +
исправил

2021-08-13 05:52 UTC, rust379 commented on interface/file/filesUtils.cpp
> +    return File();
Добавил проверку, что смогли его открыть на чтение.

2021-08-13 05:56 UTC, rust379 commented on interface/file/filesListForm.cpp
> +}
В целом, у нас все списки - обертки над базовой таблицей. 
т.к.список файлов используется в 2 местах, то кажется вполне логичным выделить его в отдельный класс

2021-08-13 05:59 UTC, rust379 commented on interface/file/fileForm.cpp
> +    ui->appointmentLabel->setText(app.patient.nameInfo().getInitials() + " " + app.date.toString());
Эту тудушку потом закрою, вдруг в дизайне Андрей все переделает и это не понадобится.

2021-08-13 06:24 UTC, strizh78 commented on interface/file/filesListForm.cpp
> +}
Аппрувну, но я вообще не понимаю логику тут)

Давай подробнее рассказ) можно на встрече

2021-08-13 06:27 UTC, strizh78 approved these changes

2021-08-13 19:41 UTC, merged