Add timetable classes/forms
rust379/MApp pull request #53
Opened 2021-08-10 18:23 UTC by strizh78

2021-08-10 18:26 UTC, strizh78 commented
<img width="1333" alt="Снимок экрана 2021-08-10 в 21 24 42" src="https://user-images.githubusercontent.com/38105548/128914433-c21017be-3223-4363-81ff-79d0bad8900c.png">

<img width="1136" alt="Снимок экрана 2021-08-10 в 21 25 01" src="https://user-images.githubusercontent.com/38105548/128914477-01e06702-535d-42a1-89f5-162b5b111bac.png">


<img width="1333" alt="Снимок экрана 2021-08-10 в 21 25 11" src="https://user-images.githubusercontent.com/38105548/128914501-7dc32937-da88-4c0c-b264-c9579376ea7d.png">


<img width="1333" alt="Снимок экрана 2021-08-10 в 21 25 24" src="https://user-images.githubusercontent.com/38105548/128914529-11120bfb-613f-48de-8751-1b89d6df6b94.png">

<img width="781" alt="Снимок экрана 2021-08-10 в 21 25 38" src="https://user-images.githubusercontent.com/38105548/128914552-3c054583-db30-4ed7-b81c-dc758742127a.png">

2021-08-11 06:03 UTC, rust379 requested changes

2021-08-11 09:07 UTC, strizh78 commented on interface/appointment/appointmentForm.cpp
> +    if (ui->openRecordBtn->isEnabled()) {
Мне кажется может быть конфликт с тем что у виджета может быть собственная функция такая

Но я попробую

2021-08-11 10:09 UTC, rust379 commented on interface/appointment/appointmentForm.cpp
> +void AppointmentForm::enableEditFields(bool enabled) {
аналогично с hide, в названии говорим, что не "делаем элементы активными", а "устанавливаем активность"

2021-08-11 10:41 UTC, strizh78 commented on interface/appointment/appointmentForm.cpp
> +void AppointmentForm::enableEditFields(bool enabled) {
я не согласна, мне больше нравится enable(bool), чем setEnabled(bool)
выглядит как лишняя нагрузка на название для меня
но вы главный, сделаю)

2021-08-12 05:36 UTC, rust379 requested changes

2021-08-12 05:36 UTC, rust379 commented on interface/timetable/dailyTimetable.cpp
> +        if (x.isDeleted() == false) {
почему не !x.isDeleted?

2021-08-12 05:36 UTC, rust379 commented on interface/appointment/appointmentRecordForm.cpp
> +
а для чего это? создаем переменную чтобы что?

2021-08-12 05:36 UTC, rust379 commented on interface/appointment/appointmentForm.cpp
>  }
тут какой-то диссонанс между именем функции и аргументом,
setRecordVisible(true) -> вроде как должен отображать элементы, а не скрывать их

2021-08-12 05:36 UTC, rust379 commented on interface/timetable/dailyTimetable.cpp
> +}
Этот цикл очень похож на вышестоящий, давай их вынесем в отдельную функцию

2021-08-12 05:36 UTC, rust379 commented on interface/timetable/dailyTimetable.cpp
> +    painter.drawText(QRect(0 + 5, x, width(), drawSettings_.startYCoordinate / 2), Qt::AlignLeft | Qt::AlignVCenter, date_.toString("dddd"));
почему используется 0 + 5?

2021-08-12 05:36 UTC, rust379 commented on interface/timetable/dailyTimetable.cpp
> +    std::vector <int> clickedMins = {10, 23, 37, 53, 60};
Если в clickedMins берем некие средние минуты, почему начинаем с 10, а не с 7-8?
и если берем среднее, давай от левой границы делать одинаковый отступ, т.е. брать либо +7мин от левой, либо +8.

2021-08-12 05:36 UTC, rust379 commented on interface/timetable/dailyTimetable.cpp
> +    const int maxHour = minHour + drawSettings_.timetableHoursCount;
не стоит сделать переменные static?

2021-08-12 09:50 UTC, strizh78 commented on interface/timetable/dailyTimetable.cpp
> +        if (x.isDeleted() == false) {
Вроде бы считается что так проще читать код
Восклицательный знак можно и не заметить при диагональном прочтении

Но не настаиваю

2021-08-12 09:50 UTC, strizh78 commented on interface/appointment/appointmentRecordForm.cpp
> +
Света хотела спать и не заметила)

Уберу

2021-08-12 09:50 UTC, strizh78 commented on interface/appointment/appointmentForm.cpp
>  }
Света хотела спать и не заметила)

Поменяю

2021-08-12 09:52 UTC, strizh78 commented on interface/timetable/dailyTimetable.cpp
> +    const int maxHour = minHour + drawSettings_.timetableHoursCount;
Тогда они будут постоянно заниматься место в оперативке
Кажется они достаточно быстро считаются, чтобы не загрязнять ими память

2021-08-12 09:54 UTC, strizh78 commented on interface/timetable/dailyTimetable.cpp
> +    painter.drawText(QRect(0 + 5, x, width(), drawSettings_.startYCoordinate / 2), Qt::AlignLeft | Qt::AlignVCenter, date_.toString("dddd"));
Нужен маленький отступ от самого края, иначе выглядит не очень

0 + 5 вместо 5, чтобы показать явно, что это отступ от 0, а не конкретное число 5


Если вопрос в "магической константе", то очень не хотелось наводнять настройки миллионом переменных
Но в целом можно ее туда убрать, да

2021-08-12 10:33 UTC, strizh78 commented on interface/timetable/dailyTimetable.cpp
> +}
тип постараться зашаблонить?

2021-08-12 22:21 UTC, strizh78 commented on interface/appointment/appointmentForm.cpp
>  }
поменяла

но вообще эта функция скоро исчезнет, вероятнее всего

2021-08-12 22:23 UTC, strizh78 commented on interface/timetable/dailyTimetable.cpp
> +}
неть, не понимаю(

их нельзя зашаблонить в таком виде

2021-08-12 22:23 UTC, strizh78 commented on interface/timetable/dailyTimetable.cpp
> +}
тогда зачем выносить?

туплю? глупая?

2021-08-13 12:07 UTC, rust379 requested changes

2021-08-13 12:07 UTC, rust379 commented on interface/timetable/dailyTimetable.cpp
> +}
Почему нельзя?
кидаем в функцию vector<T>, там прогоняется этот фор
вызывать не getAppointmentEntry / getEventEntry, а привести функции к одному имени, например getEntry или что-то еще

2021-08-13 12:15 UTC, strizh78 commented on interface/timetable/dailyTimetable.cpp
> +}
аааааа
я думала ты целиком эти кусочки вынести хочешь

а ты тупо фор перенести хочешь

2021-08-13 12:16 UTC, strizh78 commented on interface/appointment/appointmentForm.h
> +    void setRecordVisible(bool flag);
мне не понравилось слово visible)
оно какое-то более глагольное, чем булевое, в моей голове

исправить?

2021-08-13 12:18 UTC, rust379 commented on interface/appointment/appointmentForm.h
> +    void setRecordVisible(bool flag);
Я слово взял из файла qt
но да, кажется оно все же больше подходит

2021-08-21 16:45 UTC, rust379 commented on interface/timetable/dailyTimetable.cpp
> +}
А как сейчас происходит заполнение расписания? выгружаются все приемы/события и подставляются в нужное место? 
Просто почему не идет запрос на получение приемов/событий по конкретному дню?

2021-08-21 17:57 UTC, strizh78 commented on interface/timetable/dailyTimetable.cpp
> +}
потому что особый запрос в базу усложняет кучу кода
(что я кстати уже почувствовала сегодня с файлами :) )

и пока нет проблемы с производительностью - не очень ясно зачем усложнять

я вроде пыталась генерировать сколько-то приёмов и всё оставалось быстрым

2021-08-21 18:01 UTC, strizh78 commented on interface/timetable/dailyTimetable.cpp
> +}
в общем я пока морально не очень согласна давать много смысловой нагрузки на базу

в моей голове база это всё же хранилище, а не что-то, что должно влиять на код(

2021-08-21 18:12 UTC, strizh78 commented on interface/timetable/dailyTimetable.cpp
> +}
В общем думаю это надо будет обсудить потом в целом
Не только относительно этой штуки

И тогда уже переделать, если решим так

2021-08-21 19:58 UTC, rust379 commented on interface/timetable/dailyTimetable.cpp
> +}
База и есть хранилище, но запрашивать надо у нее только те данные, которые нужны, а не просто так все,
ок, обсудим это

2021-08-21 20:01 UTC, strizh78 commented on interface/timetable/dailyTimetable.cpp
> +}
можешь завести на это тикет
и тогда обсудим его и там же, если что, перепишем все места, где запрашиваем слишком много данных

2021-08-22 19:18 UTC, rust379 approved these changes

2021-08-22 19:23 UTC, merged