MAppTable - Make table flags.
rust379/MApp pull request #70
Opened 2021-08-19 06:19 UTC by rust379

2021-08-19 11:53 UTC, strizh78 requested changes

2021-08-19 11:53 UTC, strizh78 commented on interface/utils.h
> +    SelectionOpenMode = 0x0004,
мне не очень нравится название SelectionOpenMode
возможно лучше просто SelectionMode?

2021-08-19 11:53 UTC, strizh78 commented on interface/utils.h
> +enum class TableFlag {
почему этот класс в utils внезапно?

2021-08-19 11:53 UTC, strizh78 commented on interface/basicForms/mappTable.cpp
> -void MAppTable::setFlag(MAppTable::TableSettings flag, bool value) {
меня смущает момент, что если мы захотим вырубить один конкретный флаг, то надо будет вспоминать какие уже были включены и снова перечислять их
может для такого всё же оставить функцию с передачей bool и одного флага?

или если понадобится, то тогда и сделаем?

2021-08-19 11:53 UTC, strizh78 commented on interface/basicForms/mappTable.h
> +    void makeSelectionForm();
> makeSelectionForm

где это используется?

2021-08-19 11:53 UTC, strizh78 commented on interface/utils.h
> +enum class TableFlag {
кажется ему тут совсем-совсем не место
он должен быть рядом с таблицей

2021-08-19 12:00 UTC, rust379 commented on interface/utils.h
> +    SelectionOpenMode = 0x0004,
Изначально так и было, но там еще есть selectionMode - тип выбора элементов (выбор одного или нескольких)Ё
надо было как-то разделить эти вещи

2021-08-19 12:05 UTC, rust379 commented on interface/utils.h
> +enum class TableFlag {
Потому что у таблицы есть метод setFlags, который принимает этот класс, а а у нас не все формы подключают заголовочник с таблицей
Стоит сделать инклуды везде?

2021-08-19 12:07 UTC, rust379 commented on interface/basicForms/mappTable.cpp
> -void MAppTable::setFlag(MAppTable::TableSettings flag, bool value) {
Пока кажется, что флаги устанавливаются один раз - при создании формы.
Да, не исключено, что может потребоваться в какой-то момент начать переключать флаги, в зависимости от чего-то. Добавлю штуку с отключением флага

2021-08-19 12:09 UTC, rust379 commented on interface/basicForms/mappTable.h
> +    void makeSelectionForm();
При установке флага SelectionOpenMode, не заметил, что не добавил

2021-08-19 12:24 UTC, strizh78 commented on interface/utils.h
> +    SelectionOpenMode = 0x0004,
Open всё равно странно смотрится
Вроде флаг с открытием явно никак не связан

может выбор как-то через choice обыграть?

2021-08-19 12:25 UTC, strizh78 commented on interface/utils.h
> +enum class TableFlag {
инклуд с таблицей есть неявно везде, где она используется
как и инклуды всех элементов, присутствующий в дизайнере формы

2021-08-19 12:25 UTC, strizh78 commented on interface/utils.h
> +enum class TableFlag {
кажется логичным, что если ты можешь вызвать setFlags, то тебе и сами флаги без отдельного подключения должны быть доступны

2021-08-19 12:26 UTC, strizh78 commented on interface/utils.h
> +enum class TableFlag {
и тем более я не догадалась бы искать из в utils

он всё же utils, а не misc

2021-08-19 12:26 UTC, strizh78 commented on interface/basicForms/mappTable.cpp
> -void MAppTable::setFlag(MAppTable::TableSettings flag, bool value) {
> или если понадобится, то тогда и сделаем?

можно и так, я не против.

2021-08-19 12:35 UTC, rust379 commented on interface/utils.h
> +enum class TableFlag {
> инклуд с таблицей есть неявно везде, где она используется
> как и инклуды всех элементов, присутствующий в дизайнере формы
> если не ошибаюсь.

Как бы да, но qt ругался,
Еще раз посмотрю, что можно будет с делать с флагами в файле таблицы

2021-08-19 13:35 UTC, strizh78 commented on interface/utils.h
> +enum class TableFlag {
Давай точно уберём из утилс, а дальше поразбираемся где их не видно и почему ?
Может там просто в 1-2 местах инклуда не хватает

2021-08-22 18:07 UTC, strizh78 requested changes

2021-08-22 18:07 UTC, strizh78 commented on interface/basicForms/mappTable.cpp
> +        modelFrom = modelTo == mainTableModel.get() ?
Лучше добавить скобки у выражения

2021-08-22 18:07 UTC, strizh78 commented on interface/basicForms/mappTable.cpp
> +{
А объясни что это за функция и что она должна делать, пожалуйста?
Человеческим языком, но подробно

Хочу понять кое что

2021-08-22 18:07 UTC, strizh78 commented on interface/basicForms/mappTable.cpp
> +    setButtonsEnabled();
А почему это функции тут вызываются? По чтению этой функции не очень ясно

2021-08-22 20:03 UTC, rust379 commented on interface/basicForms/mappTable.cpp
> +{
Она смотрит, в какой таблице был элемент до редактирования, его выпиливает и ставит отредактированную версию,
если элемент до и после редактирования был в одной таблице - вставляет в то же место,
иначе - добавляет в конец

2021-08-22 20:07 UTC, rust379 commented on interface/basicForms/mappTable.cpp
> +    setButtonsEnabled();
Срабатывает при показе формы, чтоб изначально устанавливался фокус на первую строку главной таблицы + ставились кнопки в нужное состояние

2021-08-22 20:12 UTC, rust379 commented on interface/basicForms/mappTable.cpp
> +        case QAbstractItemView::SingleSelection:
Так лучше вот почему, если мы говорим, что хотим выбирать только 1 элемент, то и вернуться нам должен 1 элемент,
странно получать вектор.
Вроде у нас нет (и не предполагается) такого, что в одном месте, у нас может быть как мульти выбор, так и выбор 1 значения

2021-08-22 20:16 UTC, strizh78 commented on interface/basicForms/mappTable.cpp
> +        case QAbstractItemView::SingleSelection:
Да, хорошо
Просто предложила)

2021-08-22 20:18 UTC, rust379 commented on interface/basicForms/mappTable.cpp
> +    int baseWidth = (ui->mainTable->width() - 10 * columnCount) / dimension_;
Это некоторая базовая ширина, или единичная ширина, 
которую потом умножаем на соотв. значение scale_, чтоб получить итоговую ширину колонки
вычитаем 10 * columnCount - это компенсация за отрисовку вертикальных полос

2021-08-22 20:20 UTC, strizh78 commented on interface/basicForms/mappTable.cpp
> +{
Ммммм
Давай попробуем ее чуть-чуть читабельнее сделать

Меня очень смутило из начальное приравнивание ...To и ...From

[я завтра на свежую голову ещё перечитаю, может изменю это сообщение)]

2021-08-22 20:29 UTC, rust379 commented on interface/basicForms/mappTable.cpp
> +{
Обновил

2021-08-22 20:32 UTC, rust379 commented on interface/basicForms/mappTable.cpp
> +        modelFrom = modelTo == mainTableModel.get() ?
Обновил код в этом месте

2021-08-22 20:32 UTC, rust379 commented on interface/basicForms/mappTable.cpp
> +    if (scale_.empty())
пропустил, добавил

2021-08-23 06:26 UTC, strizh78 approved these changes

2021-08-23 06:48 UTC, merged